### ISSUE TITLE
Unable to load tests.(2.0.0 beta)

### ISSUE THREAD

**Issue by cx20** [KhronosGroup/WebGL#1008]
I became an error when trying to test.
I think because the probably file (core/00_test_list.txt) has been removed.

http://localhost:8000/webgl-conformance-tests.html?version=2.0.0

 Loading Tests...
 Results:
 --------------------------------------------------------------------------
 Unable to load tests. 
 --------------------------------------------------------------------------

Console:
 --------------------------------------------------------------------------
 Failed to load resource: the server responded with a status of 404 (File not found)
 http://localhost:8000/conformance2/core/00_test_list.txt 
 --------------------------------------------------------------------------

**Comment by toji** [comment]
Already fixed (https://github.com/KhronosGroup/WebGL/commit/48cae24116221a3a47fb3135941500870cac1c0a), but thanks for the report!

**Comment by cx20** [comment]
thanks!
