### ISSUE TITLE
Clarify behavior of ternary operator with arrays

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1031]
In #1024 @Oletus pointed out that the ESSL 3.00.4 spec is ambiguous in its definition of the ternary operator's behavior. In Section 5.9 "Expressions", the restriction from ESSL 1.0.17, where the ternary operator may not operate on arrays, was removed. However, in section 5.7 "Structure and Array Operations" the table defining which operators may operate on structures and arrays as whole entities was not updated. Clarification is needed in the WebGL spec and conformance suite.

**Comment by Oletus** [comment]
Khronos discussion on this issue in the ESSL specs: https://cvs.khronos.org/bugzilla/show_bug.cgi?id=13837

**Comment by Oletus** [comment]
Ran into this old bug that should have been closed ages ago. Good to sometimes decrease the open count a bit. :)

**Comment by kenrussell** [comment]
Thanks @Oletus for helping clean things up. :)
