### ISSUE TITLE
Fix dEQP GLES3 shader tests to have #version directive on the first line

### ISSUE THREAD

**Issue by Oletus** [KhronosGroup/WebGL#1042]
Several dEQP GLES3 shader tests can report incorrect failures due to not having "#version 300 es" on the first line of the shader as required by the spec. Instead they have an empty line before the line that contains the #version directive.

These failures are reproducible at least on newest versions of Chromium.

**Comment by Oletus** [comment]
@jasomobica @kenrussell : FYI, it would be nice to get this issue fixed.

**Comment by jasomobica** [comment]
Any specific example of a broken shader?

On 5 June 2015 at 09:48, Olli Etuaho <notifications@github.com> wrote:

> Several dEQP GLES3 shader tests can report incorrect failures due to not
> having "#version 300 es" on the first line of the shader as required by the
> spec. Instead they have an empty line before the line that contains the
> #version directive.
>
> These failures are reproducible at least on newest versions of Chromium.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/WebGL/issues/1042>.
>



-- 
Janusz Sobczak
Mobica Ltd
COO Mobica Mexico
Tel. (Mexico) +52 (1) 33 1430 0494
Tel (VOIP): +48 42 209 27 32
Skype: janusz.sobczak
www.mobica.com <http://www.mobica.com>


*Mobica is a provider of software engineering, testing and consultancy
services based in the UK, Poland Mexico and the USA, with a worldwide
customer
base. We have a proven track record in delivering innovative solutions to
some of the world’s best-known companies in a range of sectors including
Automotive, Mobile, Semiconductor, Finance, TV, Marine and Aviation.*

**Comment by kenrussell** [comment]
Did https://github.com/KhronosGroup/WebGL/pull/1044 fix this? Please close if so.

**Comment by Oletus** [comment]
#1044 fixed this. Before that, lots of cases in data/gles3/shaders/arrays.test were failing, for example.
