### ISSUE TITLE
Spec new behavior of DEPTH, STENCIL and DEPTH_STENCIL attachment points

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1047]
In ES 3.0 section 4.4.2 "Attaching Images to Framebuffer Objects", under the description of FramebufferRenderbuffer, the DEPTH_STENCIL attachment point is basically an alias for the DEPTH and STENCIL attachment points. Attaching an image to the DEPTH_STENCIL attachment point simply sets both the DEPTH and STENCIL attachments. Querying the DEPTH_STENCIL attachment point generates an INVALID_OPERATION error if the DEPTH and STENCIL attachments are different (section 6.1.13 "Framebuffer Object Queries").

Support for separate depth/stencil which was present in ES 2.0 is removed.

This simplifies the behavior quite a bit and eliminates the need for the text in section 6.6 "Framebuffer Object Attachments". The WebGL 2.0 spec should be updated and cleaned up.

**Comment by jdashg** [comment]
I am so OK with this. The WebGL 1 behavior is extremely annoying to implement, because we need to delay setting the attachment points until draw time.

**Comment by djg** [comment]
+1

**Comment by zhenyao** [comment]
https://github.com/KhronosGroup/WebGL/pull/1054
