### ISSUE TITLE
WebGL 2 Conformance - state/gl-object-get-calls

### ISSUE THREAD

**Issue by djg** [KhronosGroup/WebGL#1061]
I'm trying to understand what is going with the setup in this test.

```javascript
gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, gl.RENDERBUFFER, renderbuffer);
if (contextVersion > 1)
  gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.STENCIL_ATTACHMENT, gl.RENDERBUFFER, renderbuffer);
```
If the version is WebGL 2, then the `DEPTH_COMPONENT16` is bound to `STENCIL_ATTACHMENT` which results in an incomplete attachment.

I don't understand the intention of the code and I'm seeking clarification.

**Comment by kenrussell** [comment]
I think there's a bug in the test and it should allocate a gl.DEPTH24_STENCIL8 type renderbuffer if contextVersion is greater than 1. Can you try this? I'm having difficulty verifying the fix either with Firefox's or Chrome's WebGL 2 prototypes.

**Comment by djg** [comment]
After submitting this issue, I changed the test to create gl.DEPTH24_STENCIL8. Currently it fails on Firefox because gl.renderbufferStorage hasn't been updated to accept ES3/WebGL2 enums. I'll fix Firefox.
