### ISSUE TITLE
Resfresh problems in Android stock browser(almost all versions).

### ISSUE THREAD

**Issue by Cy-Bo-Rg** [KhronosGroup/WebGL#1093]
This explains the issue and shows how I fixed it.
https://www.youtube.com/watch?v=2KPVoaEOKfM
That's another demo of the problem in action in which I show real-time screen updates.
https://www.youtube.com/watch?v=P_i0uOPWBuI

Tested on Android stock browser 4.1.2 running on a PowerVR SGX540(blacklisted on chrome and crosswalk chromium webview).
With this fix I can run almost all Three.js demos at the full frame rate possible by this device.
The shadow not rendering correctly is a three.js problem,it works with the latest revision (72dev).
On crosswalk , if I force it to run webgl , I have a slightly lower frame rate than with this fix and some three.js demos are crashing (because of too many polygons on the screen) while on stock browser the demos are running fine and if they won't load I can just switch demo without any problem whatsoever.The same happens on Firefox beta for android(39.0), some demos are crashing the software.

I have mixed results with your demo repository without the fix; some demos are refreshing properly, some aren't.
I guess the problem resides in the implementation logic.

**Comment by Cy-Bo-Rg** [comment]
A few words are much appreciated.

**Comment by Cy-Bo-Rg** [comment]
https://github.com/mrdoob/three.js/pull/6787
In this pull request you can find the modified index_mobile.html I've used if you want to try it.

**Comment by Cy-Bo-Rg** [comment]
This is three.js rev72 dev on Android 4.2.2 on Mali 400 with its stock browser.

Rev72dev without code and refresh fix
![screenshot_2015-07-05-10-46-19](https://cloud.githubusercontent.com/assets/5455606/8511282/b0f68186-230f-11e5-8583-2d84fc8cf5d7.png)

Rev72dev with code added and fix
![screenshot_2015-07-05-11-32-30](https://cloud.githubusercontent.com/assets/5455606/8511287/d5b12a94-230f-11e5-9924-7153beef8141.png)
Rev72dev with code added and fix
![screenshot_2015-07-05-10-48-16](https://cloud.githubusercontent.com/assets/5455606/8511293/1d836792-2310-11e5-97cc-9c1316d7fc2e.png)
Rev72dev with code added and fix
![screenshot_2015-07-05-11-34-03](https://cloud.githubusercontent.com/assets/5455606/8511294/25028980-2310-11e5-994d-6862d29ae234.png)
Rev72dev with code added and fix
![screenshot_2015-07-05-11-35-16](https://cloud.githubusercontent.com/assets/5455606/8511296/2b4df450-2310-11e5-892b-f92672079c2d.png)


For a comparison with my blacklisted device I've tested the latest chrome dev on this Mali 400 (which isn't blacklisted) versus stock android browser on my Power VR SGX540.

Mali400 running "parallaxmap" demo on rev72dev
![screenshot_2015-07-05-11-57-21](https://cloud.githubusercontent.com/assets/5455606/8511305/557f4b48-2310-11e5-8081-a405bb8b8de8.png)
Mali400 running "parallaxmap" demo on rev72dev
![screenshot_2015-07-05-11-57-50](https://cloud.githubusercontent.com/assets/5455606/8511309/5dde5a18-2310-11e5-90f4-efd89c217fc8.png)

Power VR SGX540 running "parallaxmap" on rev72dev (modified)
![screenshot_2015-07-05-12-10-50](https://cloud.githubusercontent.com/assets/5455606/8511311/6d2fefe0-2310-11e5-8bc4-d4d26f02ef17.png)

**Comment by kenrussell** [comment]
It looks to me like the key change in https://github.com/mrdoob/three.js/pull/6787 is to emulate requestAnimationFrame on top of setTimeout. Does the stock Android browser on these devices not properly support requestAnimationFrame? mrdoob asked the same question on the pull request above.

Devices running JellyBean should be able to run Chrome. If you disable Chrome's GPU blacklist via about:flags, does this content run correctly on the current version of Chrome?

**Comment by Cy-Bo-Rg** [comment]
pull request updated; more infos are there.

**Comment by kenrussell** [comment]
The indication from https://github.com/mrdoob/three.js/pull/6787 is that the Android browser on these devices is broken; if you have to add a div behaving as a marquee in order to get the page to refresh properly, that's a massive hack.

Like it or not, the Android browser isn't being actively developed any more. Firefox and Chrome are. The best way to help improve WebGL for all users would be to file bugs about any crashes you've seen. We'd very much like to track down their root cause.

I'm sorry, but I don't see anything concrete in this issue report to fix in Khronos' WebGL repository. Again, if you can reproduce crashes of WebGL implementations on certain pages, please file bugs against the browsers so we can fix them, and add conformance tests to avoid reintroducing them. Thanks.

**Comment by Cy-Bo-Rg** [comment]
Then I'm a pro! x)
And browsers devs are just lazy... :P
But I'll try to help by sharing what I've found so far, even though , with my hack, personally, I won't need to wait for Firefox or Chrome to be developed further since I can stick to my "old"-"unsupported"-stock browser considering I've got better performance and compatibility on it...
For example, the cloth demo on Firefox Beta 40 doesn't even show up while on stock browser it's almost perfect.
Thanx for the attention though.
I thought there could have been a way to implement the hack directly in webgl , my fault.

**Comment by Cy-Bo-Rg** [comment]
By the way , to make things clear, closing this is an error because , on this device , some of your demos are refreshing properly without my fix while some aren't... (I didn't show them on video,my fault...)
It's a WebGL problem , not a browser problem.
