### ISSUE TITLE
Merge tests into web-platform-tests.

### ISSUE THREAD

**Issue by Ms2ger** [KhronosGroup/WebGL#1105]
WebGL is a web API, so its tests should live along with all other web API tests in https://www.github.com/w3c/web-platform-tests, so that they can benefit from the infrastructure there, rather than reinventing the wheel once more.

**Comment by jdashg** [comment]
I think this also applies to WebGL: "However, for mainly historic reasons, the CSS WG testsuite is in a separate repository, csswg-test." I do not think this push for centralization is useful when we're already as far along as we are.

What are the non-philosophical reasons in favor of this proposal?

**Comment by Ms2ger** [comment]
That you can run the tests without creating a whole bunch of new, one-off infrastructure. That's why Servo is running wpt tests and not these.

**Comment by Ms2ger** [comment]
As for the comparison with csswg-tests: we're actually moving towards sharing ever more code with wpt. The main reason that it's still in a separate repository is that it requires a build step to create a useful test suite; this does not appear to be the case for WebGL.

> when we're already as far along as we are.

This is a typical instance of the sunk cost fallacy.

**Comment by jgraham** [comment]
FWIW we are also trying to remove the build step from the CSS testsuite. Having everything run with a single set of infrastructure is of great benefit to everyone. For example it will mean that the same tools used to do ~weekly two-way syncs of wpt into the gecko repository would also work for other testsuites.

**Comment by kenrussell** [comment]
A productive path forward would be for the w3c to pull in this repository as a Git submodule. We'd be happy to review pull requests that adapt the WebGL conformance tests to run within the w3c's framework, so long as they don't change the existing framework too radically. Many of the WebGL working group members already have automated test infrastructure built around this repository. Also, it's not desirable to the WebGL working group to merge this repository wholesale into the w3c's. Would this be an agreeable direction?

**Comment by kenrussell** [comment]
Glad to see the W3C has figured out a mechanism for pulling these tests into the web-platform-tests suite. Please file issues here if you see bugs in the tests. The ideal workflow would be to fix them in this repository, and then pull them into the web-platform-tests repo.

The WebGL working group has discussed merging workspaces with the w3c and the consensus is that doing so would be too disruptive to the WebGL WG's workflow. Apologies, but closing this issue.
