### ISSUE TITLE
Should TIMEOUT_IGNORED be -1 instead of 0xFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by djg** [KhronosGroup/WebGL#1127]
JS doesn't have 64 bit integers, although they may come, one day.

I wonder if we should change TIMEOUT_IGNORED from uint64 to int64, allowing negative values (ie -1) to represent the ignore value? (and can also be represented by double)

**Comment by jdashg** [comment]
I thought we already resolved to do this.

**Comment by zhenyao** [comment]
@toji 

Brandon finds out that the 0xFFFFFFFFFFFFFFFF happens to be a number that can be represented as double.  Not sure if it's just a V8 thing or it's all across js engines.  If the latter, than we can just use double to represent this constant.

**Comment by toji** [comment]
Sorry, I was wrong about that. The number it resolves to is actually off by
about 300. But at least in Chrome it's consistent enough that we can still
check it against static_cast<double>(0xFFFFFFFF) in the C++ code.

I wouldn't object to using -1, though. It's simpler conceptually and
doesn't rely on casting to get right.

**Comment by zhenyao** [comment]
If that's the case, I feel -1 is a better representation.

**Comment by kenrussell** [comment]
Discussed this on today's working group conference call. Yes, this was discussed at the last face-to-face meeting. The plan is to try changing the typedef for TIMEOUT_IGNORED to GLint64 and represent it with -1 in the IDL, and see if the conformance tests can be made to pass. If so, we'll submit a pull request updating the IDL. Brandon was going to work on this, so assigning the issue to him, but Dan, if you verify this works in Firefox, please feel free to submit a pull request too.

**Comment by djg** [comment]
I've been using GLint64 & -1 in Firefox's webidl. This is `out-of-spec` given the current spec. I'm happy to submit a PR with the changes to the spec documents.

**Comment by toji** [comment]
I was going to update the spec and conformance test first thing tomorrow, but if you want to put up a change before then be my guest!

**Comment by kenrussell** [comment]
Let's go ahead with this change. Whoever can put up the pull request first wins!

**Comment by toji** [comment]
Fixed.
