### ISSUE TITLE
Add query arg that forces shader source to output

### ISSUE THREAD

**Issue by toji** [KhronosGroup/WebGL#1154]
As requested in #1153 it would be useful to have a debugging flag that forces all compiled shaders to output to either the console or page output, ideally with shader info logs and translated source when available. This should be off by default, since otherwise it will create gargantuan amounts of log spew.

**Comment by kenrussell** [comment]
Let me please give this one to you. :)

**Comment by jdashg** [comment]
This seems like something solvable in browser devtools, or even a WebGL JS shim.
