### ISSUE TITLE
WebGL 2 - InvalidateSubFramebuffer test

### ISSUE THREAD

**Issue by djg** [KhronosGroup/WebGL#1222]
Test https://www.khronos.org/registry/webgl/sdk/tests/conformance2/renderbuffers/invalidate-framebuffer.html?webglVersion=2&quiet=0 is failing with the following:

`FAIL getError expected: INVALID_VALUE. Was NO_ERROR : calling invalidateSubFramebuffer should generate INVALID_VALUE if width < 0 or height < 0.`

I've checked the WebGL 2 spec, OpenGL ES 3.0.4 spec and man page for glInvalidateSubFramebuffer and none of those documents specify this error.

If this is a WebGL 2 extension to InvalidateSubFramebuffer then it should be documented.

**Comment by jdashg** [comment]
IIRC, any time a GLsizei receives a negative value, an INVALID_VALUE should
be generated. (Because GLsizei is a pseudo-unsigned type)

**Comment by zhenyao** [comment]
Jeff is correct.  It is specified in ES 3.0 section 2.5, GL Errors

**Comment by djg** [comment]
Is that documented somewhere?

**Comment by djg** [comment]
Thanks for the explanation.
