### ISSUE TITLE
Inform user why WebGL is not available

### ISSUE THREAD

**Issue by pyalot** [KhronosGroup/WebGL#1225]
It is frequently the case that a WebGL context cannot be obtained for reasons todo with blacklists, performance caveats etc.

The Web Application programmer has insufficient information to devise a meaningful message to the user in such cases.

A UA should offer the capability to a Web Application to display the reason why WebGL will not run, and if possible offer an actionable advise to the user how this situation can be rectified.

**Comment by pyalot** [comment]
Previous discussion on blacklists, performance caveats and other things: https://www.khronos.org/webgl/public-mailing-list/archives/1203/msg00013.php

Current discussion: https://www.khronos.org/webgl/public-mailing-list/archives/1509/msg00021.php

**Comment by kenrussell** [comment]
As discussed on the mailing list, the webglcontextcreationerror's statusMsg should provide some baseline information. Is that information inadequate?

**Comment by treeform** [comment]
Hey @kenrussell, I wrote the original email I was not aware that statusMessage has any thing useful. So far I only managed to make it produce "Web page was not allowed to create a WebGL context." by disabling webGL in about://flags in chrome. I will be tracking other messages that it gets to see if its good enough. If it is - great - thats exactly what I want, maybe i was just missing documentation.

**Comment by jdashg** [comment]
That's what it's supposed to be for! I don't think we do a great job of this in Firefox yet, but I'm happy to take a bug against Firefox for it.
