### ISSUE TITLE
Specify behavior of getActiveUniforms when INVALID_INDEX is passed

### ISSUE THREAD

**Issue by toji** [KhronosGroup/WebGL#1262]
The ES3 spec states that GetUniformIndices can return INVALID_INDEX if given a name that doesn't match an active uniform. The documentation for getActiveUniforms doesn't specify what happens if you pass that (or any other invalid index) into it, though. Seems like an area that WebGL should clarify.

I suggest one of two responses: If any invalid index is detected generate and INVALID_VALUE error and return null or return an array with a value for each index provided, but set the values corresponding to the invalid indices to null. This is perhaps more developer friendly, but can result in awkward non-homogonous arrays ([0, 4, 8, null, 16]). I'm personally in favor of the first approach.

Thoughts?

**Comment by zhenyao** [comment]
The underlying ES3 spec specified this: "If index or any value in
uniformIndices is greater than or equal to the value of ACTIVE_UNIFORMS , the
error INVALID_VALUE is generated."

**Comment by kenrussell** [comment]
Right. If you think the WebGL spec should copy that spec text please put up a pull request. Thanks.

**Comment by toji** [comment]
No, I think it's fine as is. I don't know how I missed that text in the spec. Thanks for pointing it out!
