### ISSUE TITLE
uniform buffer test cases make no sense

### ISSUE THREAD

**Issue by jrmuizel** [KhronosGroup/WebGL#1272]
glsUniformBlockCase.UniformBlockCase.prototype.render() is called by glsUniformBlockCase.UniformBlockCase.prototype.iterate() with an argument of program.getProgram() which returns a WebGLProgram. glsUniformBlockCase.UniformBlockCase.prototype.render then calls program.program.program on it as well as program.getProgram(). Neither of these will work.

**Comment by kenrussell** [comment]
Janusz mentioned in a chat he'd look into this.
