### ISSUE TITLE
transform_feedback test fails on llvmpipe

### ISSUE THREAD

**Issue by jrmuizel** [KhronosGroup/WebGL#1285]
The test for whether a query's results are available too early fails because llvmpipe finishes the work during the call to glFinish. It seems better to just remove this 'too early' test.

**Comment by kenrussell** [comment]
This is a difference between WebGL 2.0 and OpenGL ES 3.0 that was decided upon by the working group in recent meetings. Queries' results must not become available until control returns to the browser's main loop. Please see https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.23 . Fixing this in Firefox involves adding a little bit of state to the WebGLQuery objects; it's not difficult. It's been implemented in Chrome in https://codereview.chromium.org/1408803003 so you can see what's involved.
