### ISSUE TITLE
GLSL struct constructors/initializers bug on Chrome on Andriod in fragment (maybe vertex?)

### ISSUE THREAD

**Issue by bhouston** [KhronosGroup/WebGL#1302]
(Per @kenrussell's request here: https://github.com/mrdoob/three.js/pull/7556#issuecomment-155528006)

So on the ThreeJS project we ran into a unique problem on Chrome on Android after we adopted structs in a lighting code refactoring.  On Chrome on Android (but no on Chrome on OSX, Chrome on Windows, IE/Edge on Windows, Firefox on Andriod, Firefox on Windows, or Safari anywhere) it appears that struct constructors/initializers (I'm not sure of the proper name) do not actually initialize the struct contents, they remained zeros.  We worked around this bug with this PR:

https://github.com/mrdoob/three.js/pull/7556

You can see that this above PR didn't do anything but avoid using the struct initializer/constructors.  This fixed the issue.

I am not complete sure, but think that the struct initializers in the vertex shader worked, but not in the fragment shader, but I avoided their use in both cases in this PR anyhow, just to be safe.

Here it the light refactoring PR in ThreeJS that exposed this issue: https://github.com/mrdoob/three.js/pull/7324

Thus I suggest that struct initializer in both the vertex and fragment shader be added as a test to the WebGL conformance suite.

**Comment by bhouston** [comment]
Reproduceable issue on Nexus 5 with latest Andriod OS and Chrome as of November 7, 2015.

**Comment by kenrussell** [comment]
Thanks @bhouston for this bug report. Could you please help us out by creating a small test case for this problem? We have multiple outstanding bug reports against multiple GPUs right now (most of which are probably bugs in the drivers) and it would really speed up the process if you could create a small test in this directory: https://github.com/KhronosGroup/WebGL/tree/master/sdk/tests/conformance/glsl/bugs which you've verified reproduces the problem.

**Comment by kenrussell** [comment]
P.S. It would be best if you didn't copy the shader verbatim but rather reduced it to the minimum one which reproduces the problem.

**Comment by mrdoob** [comment]
#1316

**Comment by kenrussell** [comment]
Yes. A conformance test's been added for this problem and a bug's been filed with Qualcomm. I hope it will be fixed in a future Android release. Closing as fixed (there's nothing more that can be done from the WebGL implementers' standpoint).
