### ISSUE TITLE
An official version of DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js

### ISSUE THREAD

**Issue by tmcw** [KhronosGroup/WebGL#1313]
I'm building a large application around WebGL and would like to have a great debugging page for users whose browsers or hardware isn't playing along. get.webgl.org is fantastic, and I can see that there's some good logic in it for recommending resources: I'd love to use this logic directly.

The file that contains the debugging data is named DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js

Is this updated somewhere? If so, could I get a reference to where? I would love to, for instance, maintain a npm module that _would_ be updated for people who use it as a dependency in their web applications.

**Comment by kenrussell** [comment]
The recommendation in that file is to link to http://get.webgl.org/troubleshooting in your web app. Does this not work for your uses? If not, can you describe why not?

Could you describe how a node module would wrap this sort of code, and be kept up to date? We recently created a repository https://github.com/KhronosGroup/WebGLDeveloperTools on request of someone who wanted an ES6 module for webgl-debug.js. We'd be happy to something similar for the get.webgl.org sources if doing so doesn't break maintainability or introduce version skew. Your recommendations would be welcome.

**Comment by tmcw** [comment]
@kenrussell Here's what I ended up building for my app: https://github.com/mapbox/webgl-help - it's a function that takes a `userAgent` and returns an object of help documents derived from the get.webgl.org page - in the process it also uses ua-parser-js to robustly parse browsers and simplifies the logic of selecting a page.

Ideally the page itself would use a reusable module like this, and the module would be versioned to permit for applications to upgrade quickly. For my application, there's the concern of branding (it's an [IDE-like environment for editing maps](https://www.mapbox.com/mapbox-studio/)) as well as the real potential for eventual end-users to be offline or airgapped; hence the emphasis on being able to run this logic locally.

**Comment by kenrussell** [comment]
If you could advise us on how to set up such a module (for example, does it need to be in its own workspace?) and how it can be easily integrated into the get.webgl.org sources we'll be happy to do the setup/reorganization needed and would be glad to receive pull requests.

**Comment by greggman** [comment]
get.webgl.org sources is already in the public repo and should auto update if a pull request is made to the repo.


https://github.com/KhronosGroup/WebGL/tree/master/other/get.webgl.org

**Comment by tmcw** [comment]
Okay, going to keep using https://github.com/mapbox/webgl-help for my application use case.
