### ISSUE TITLE
RFE: OES_draw_elements_base_vertex

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1333]
A customer has pointed out that the OES_draw_elements_base_vertex extension would be highly useful and allow a huge performance speedup in their rendering code. Even though this is a relatively new OpenGL ES extension, the hardware has supported it for a long time and it's likely that it will roll out fairly quickly. On desktop platforms it's trivially supportable.

**Comment by kenrussell** [comment]
It looks like the most official version of this extension is https://www.khronos.org/registry/gles/extensions/OES/OES_draw_elements_base_vertex.txt , but it also looks like some devices support https://www.khronos.org/registry/gles/extensions/EXT/EXT_draw_elements_base_vertex.txt .

**Comment by Groovounet** [comment]
Like

**Comment by jdashg** [comment]
This is moving forward: #2936
