### ISSUE TITLE
Behaviour of getExtension for WEBGL_color_buffer_float

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/WebGL#1472]
I'm not sure I should ask this question to this repository, but I wonder some of browser returns null when call getExtension("WEBGL_color_buffer_float") even if the browser supports the extension.

It needs making a framebuffer to bind with a floating value texture for making sure that extension is really supported or not.

Is this valid for the specification? Or, shouldn't it need to be clearly specified?

**Comment by zhenyao** [comment]
https://www.khronos.org/registry/webgl/extensions/OES_texture_float/

"Implementations supporting float rendering via this extension will implicitly enable the WEBGL_color_buffer_float extension and follow its requirements"

**Comment by zhenyao** [comment]
"Although this feature has historically been allowed, new implementations should not implicitly support float rendering and applications should be modified to explicitly enable WEBGL_color_buffer_float."

So which browser you are talking about?

**Comment by zhenyao** [comment]
Actually Chrome implements EXT_color_buffer_float.

**Comment by LimeStreem** [comment]
Fmm... Why WebGL needed to specify the new specification for drawing float value into floating value texture although these feature was historically allowed?

And, is there any difference between EXT_color_buffer_float and WEBGL_color_buffer_float?

**Comment by msc-** [comment]
> On Feb 13, 2016, at 4:12 PM, ライム野郎 <notifications@github.com> wrote:
> 
> Fmm... Why WebGL needed to specify the new specification for drawing float value into floating value texture although these feature was historically allowed?
> 
> 

The feature was not historically allowed. There is no color_buffer_float extension for OpenGL ES 2.0. If, by historically allowed, you mean that some WebGL implementations supporting WebGL’s OES_texture_float allowed rendering to float textures, that was an error. It was not intended and as a result the operations were underspecified leading to issues such as fragment shader outputs being clamped to 0 to 1.

WEBGL_color_buffer_float and the changes to OES_texture_float are intended to remedy those problems.
> And, is there any difference between EXT_color_buffer_float and WEBGL_color_buffer_float?
> 
Yes. Functionality-wise WEBGL_color_buffer float supports blending operations on float-point color buffers which means it can only be implemented on OpenGL not OpenGL ES. Also it is for WebGL 1.0.

EXT_color_buffer_float is for WebGL 2.0 and wraps the matching OpenGL ES extension. In WebGL 2 the functionality equivalent to WEBGL_color_buffer_float is exposed via EXT_color_buffer_float in combination with EXT_float_blend.

Regards

    -Mark

Hire me!

**Comment by kenrussell** [comment]
In the Chrome browser the decision was made to not expose WEBGL_color_buffer_float and EXT_color_buffer_half_float for WebGL 1.0.

In WebGL 2.0, however, EXT_color_buffer_float covers this functionality well, and very precisely. Chrome implements this extension.

We strongly encourage developers to upgrade their WebGL 1.0 code to WebGL 2.0, not only to take advantage of new functionality, but also to clarify areas of the WebGL 1.0 specification. This was not the only problematic area.

Closing this bug; we don't plan to take any action here.
