### ISSUE TITLE
Extension function handling under context loss is ambiguous

### ISSUE THREAD

**Issue by jdashg** [KhronosGroup/WebGL#1596]
Under "5.14.14 Detecting and enabling extensions":
Any use of a disabled extension or its referenced objects generates an INVALID_OPERATION error.

The process at the top of "5.14 The WebGL context" however lists a different process that does not unconditionally generate INVALID_OPERATION.

This test wants there to be no INVALID_OPERATION:
https://www.khronos.org/registry/webgl/sdk/tests/conformance/context/context-lost.html?webglVersion=1

**Comment by kenrussell** [comment]
Thanks for catching the ambiguity.

The steps in "5.14 The WebGL Context":
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14

are newer, and more precise, than the wording in "5.14.14 Detecting and enabling extensions":
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.14

I propose we resolve the ambiguity by making section 5.14.14 refer to the steps defined in 5.14. What do you think?

**Comment by jdashg** [comment]
Sounds good to me.
