### ISSUE TITLE
WebGL2: Web IDL typedef definitions cannot be nested inside interfaces

### ISSUE THREAD

**Issue by arronei** [KhronosGroup/WebGL#1600]
https://github.com/KhronosGroup/WebGL/blob/master/specs/latest/2.0/webgl2.idl

Inside the interface WebGL2RenderingContextBase { ... } the following typedefs are incorrectly placed (invalid) and should be moved outside of the interface members list:

typedef (Uint32Array or sequence<GLuint>) UniformUIVSource;
typedef (Float32Array or sequence<GLfloat>) UniformMatrixFVSource;
typedef (Int32Array or sequence<GLint>) VertexAttribIVSource;
typedef (Uint32Array or sequence<GLuint>) VertexAttribUIVSource;
typedef (Int32Array or sequence<GLint>) ClearBufferIVSource;
typedef (Uint32Array or sequence<GLuint>) ClearBufferUIVSource;
typedef (Float32Array or sequence<GLfloat>) ClearBufferFVSource;

**Comment by kenrussell** [comment]
Thanks for the report.
