### ISSUE TITLE
conformance2/textures/misc/copy-texture-image.html was written against outdated spec

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/WebGL#1628]
The test is testing copies like the following should succeed:
 - RGBA/UNSIGNED_BYTE -> R8
 - RGBA/UNSIGNED_BYTE -> SRGB8
 - RGBA32I -> RGBA8I
 
However these formats do not have the same effective format sizes (and the right hand size is sized), which should cause the call to CopyTexImage2D to fail as described in section 3.8.5 of the OpenGL ES 3.0.4 specification.

I believe the wording for this function was changed after OpenGL ES 3 was released.

**Comment by zhenyao** [comment]
OK, I agree the case 2 and 3 should generate INVALID_OPERATION, 2 because the encoding is different, 3 because the effective format component sizes differ.

However, why case 1 should fail?  RGBA/UNSIGNED_BYTE effective internalformat is RGBA8, and RGBA8 -> R8 is valid.

**Comment by Kangz** [comment]
It should fail because the format sizes is (8, 8, 8, 8) vs. (8, 0, 0, 0)

**Comment by zhenyao** [comment]
My reading is component sizes need to match only a component exists in the destination internalformat.

**Comment by Kangz** [comment]
The spec says: If internalformat is sized, the internal format of the new texel array is internalformat,
and this is also the new texel array’s effective internal format. If the
component sizes of internalformat do not exactly match the corresponding component
sizes of the source buffer’s effective internal format, described below, an
INVALID_OPERATION error is generated.

I think ANGLE interpreted "exactly" to mean that 8 vs. 0 is not valid.
@shannonwoods I believe you wrote that part of the spec, what is the valid interpretation?

**Comment by zhenyao** [comment]
If your interpretation is correct, then
RGBA/UNSIGNED_BYTE -> LUMINANCE is OK, but
RGBA/UNSIGEND_BYTE-> R8 is not OK?  That's just weird.

@shannonwoods Please clarify.
@kenrussell @toji FYI

**Comment by zhenyao** [comment]
Another example is:

RGBA/UNSIGNED_BYTE -> RGB is OK, but
RGBA/UNSIGNED_BYTE -> RGB8 is not OK?

**Comment by kenrussell** [comment]
That seems like an overly strict interpretation. Chromium interpreted this to mean that the components in the destination texture must exist in the source texture, as @zhenyao pointed out above.

**Comment by shannonwoods** [comment]
RGBA/UNSIGNED_BYTE -> R8 (or RGB8) is valid.

The intention is that for each component that exists in both source and destination, the size matches exactly. Components may be dropped as per the final paragraph on p139 of the 3.0.4 spec:

"internalformat is further constrained such that color buffer components can be dropped during the conversion to internalformat, but new components cannot be added."

This got a considerable amount of discussion on the ES WG list in September of 2013-- I can point interested parties with Khronos mailing list access at the threads for background if desired.

**Comment by zhenyao** [comment]
Thanks @shannonwoods for clarification.

**Comment by Kangz** [comment]
So we'll need to fix ANGLE too, thanks Shannon!

**Comment by Kangz** [comment]
Fixed the ANGLE side in https://chromium-review.googlesource.com/#/c/340382/

**Comment by kenrussell** [comment]
Great @Kangz . Is this issue resolved at this point? Please close if so. Thanks.

**Comment by Kangz** [comment]
Per discussion in the ANGLE meeting we'll fix the tests that test sizes smaller in the target than in the destination.

**Comment by Kangz** [comment]
Fixed by Mo in 8e009656d911d5f643e83757329cb33f838552af
