### ISSUE TITLE
Should allow stencil != depth in conformance2/renderbuffers/framebuffer-object-attachment.html

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/WebGL#1640]
This test: https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html#L171

Checks that color + depth + stencil: depth != stencil is unsupported, however looking at the WebGL 2 and  OpenGL ES 3 it seems that it should be allowed (and is actually the whole point of having separate attachment points for DEPTH and STENCIL).

Am I missing something?

**Comment by kenrussell** [comment]
"Whole Framebuffer Completeness" in Section 4.4.4 "Framebuffer completeness" defines this behavior. It is different between ES 2.0 and 3.0. "Depth and stencil attachments, if present, are the same image."

ES 2.0 allowed separate depth and stencil renderbuffers.

ES 3.0 does not allow separate depth and stencil renderbuffers. If you want depth+stencil, it's necessary to use packed depth/stencil.

Please close this if you agree. Thanks.

**Comment by Kangz** [comment]
Thanks for the pointer, I didn't realize there was a backwards incompatible change.
