### ISSUE TITLE
No way to upload slices of an image losslessly to a 3D texture

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#1740]
It's possible I'm just missing it.

Let say you have 64x8 image and you'd like to upload that as an 8x8x8 3D texture.

If I understand correctly the only way to do this is through a canvas. Copy each 8x8 slice of the texture to an 8x8 canvas and then call `gl.texSubImage3D` with that slice. Unfortunately canvas is lossy because of its alpha-premultiplication so whereas there is a path to get 2D images into 2D textures losslessly there is no way to get 3D image data into 3D textures losslessly if those are stored in a 2D image.

being able to pass in width and height to the version of `texImage3D` that takes an `TexImageSource` seems like it would allow that. Since you can use `UNPACK_SKIP_XXX` to select the starting source pixel if you could specify the width and height then you could select subrect from an `TexImageSource`

The same would be true of `texSubImage2D`. If you could pass in the width and the height then again you could select sub rects.

WebGL 1 didnt't have the `UNPACK_SKIP_XXX` stuff so this wasn't possible. Now it is. Shouldn'y the spec allow this? 

Of course I vote Yes it should 😁

But if the answer is no then it the spec needs to cover what `UNPACK_SKIP_XXX` do on `tex(Sub)ImageXX` functions that take a `TexImageSource`.

**Comment by zhenyao** [comment]
We are pushing for ImageBitmap so that might be a solution to your problem.

**Comment by greggman** [comment]
It might but it still leaves `UNPACK_SKIP_XXX` unspecified for `TexImageSource`. It just seems like since we already know that calling any of the functions that take a `TexImageSource` the image will first be converted to the specified format/type then we also know exactly what `UNPACK_SKIP_XXX` would do in those contexts. It doesn't *seem* hard to implement. The code is already doing the conversion and already passing a pointer to the converted image so the user can already know what size the passed image will be an easily pass width, height, and set `UNPACK_SKIP_PIXELS`, `UNPACK_SKIP_ROWS`, and `UNPACK_SKIP_IMAGES` appropriately. Those 3 parameters are basically sourceX, sourceY and sourceZ and should be easy to validate

**Comment by zhenyao** [comment]
Sure.  We can discuss that in the next working group meeting.

**Comment by kenrussell** [comment]
Sorry for the long delay replying to this issue. This is an excellent point and the working group is going to make sure this is possible before the WebGL 2.0 spec is shipped. The only question is the exact form of the API. It's been discussed whether to use the new UNPACK_SKIP_PIXELS and UNPACK_SKIP_ROWS pixel unpack parameters to specify the upper-left corner, and just add new width, height, and depth arguments to the entry points taking DOM elements; or do something else.

Another longstanding issue that will be fixed alongside this one is the ability to upload sub-portions of an ArrayBuffer to a buffer, texture, compressed texture, etc. without generating garbage (small ArrayBufferView instances), similar to Mozilla's proposal https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_subarray_uploads/ .

CC'ing @zhenyao @jdashg @RafaelCintron @grorg .

**Comment by kenrussell** [comment]
This has been fixed with API changes in WebGL 2.0. I'm having a difficult time finding all of the git history, but the most recent spec clarification was in #2149, and some related test changes were made in #2138, #2141, #2145, #2147, and #2158.
