### ISSUE TITLE
Mac Intel drivers do not sample cubemap integer textures correctly with seamless cubemap enabled

### ISSUE THREAD

**Issue by zhenyao** [KhronosGroup/WebGL#1819]
The bug only applies to texture size of 64x64 or smaller.

**Comment by zhenyao** [comment]
Correction: the bug actually exists in any texture sizes.  It's just when the size is big enough and the rendering target isn't, then the incorrect corner pixel (top right, tex coords (1, 1)) won't show.

**Comment by kenrussell** [comment]
Recent drivers seem to have fixed this problem and @kainino0x has removed the workarounds in #2796.
