### ISSUE TITLE
WebGL ES 3.1

### ISSUE THREAD

**Issue by acterhd** [KhronosGroup/WebGL#1821]
Hello. When will new webgl with ES 3.1 features?

**Comment by Kangz** [comment]
Hello.

WebGL2 (ES 3.0) isn't enabled on any browser yet and no spec work has been done on a WebGL 3. So not soon.

**Comment by kenrussell** [comment]
Feel free to ask questions like this on the public_webgl mailing list. Let's use the issue tracker for bugs against the spec and conformance suite.
