### ISSUE TITLE
Running WebGL 2.0 tests with multiple iframes would result in crash.

### ISSUE THREAD

**Issue by gyagp** [KhronosGroup/WebGL#1840]
We can already run the whole WebGL 2.0 tests with Chrome on some platforms, such as Linux with NVidia GPU. However, if we try with multiple iframes (with frames=x URL option), it will result in frequent crashes (webgl hit a snag, and reload is required). 
I don't see same crash during 1.0.4 tests with multiple iframes.

To reproduce the issue, you may simply run with following URL "https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html?version=2.0.0&frames=4".

**Comment by zhenyao** [comment]
Bugs against Chrome should be filed at crbug.com.  Thank you.

**Comment by zhenyao** [comment]
Let me close this as we really don't need to do anything at the test suite side.

**Comment by gyagp** [comment]
These two days, I had intensive tests with 2/4/6/8 iframes many times against latest Chromium code, and found no crashes. So I will not resubmit this bug to Chromium side. 
Currently I still see some unexpected failures for multiple iframes. Let me have a double confirm in another day.
