### ISSUE TITLE
RFE: multisampled renderbuffer support in EXT_color_buffer_float

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1845]
Unity has pointed out in https://bugs.chromium.org/p/chromium/issues/detail?id=625772 that multisampled floating-point renderbuffers are explicitly not supported in https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_float/ .

This is useful functionality and required for parity with native applications. It is also a corner case not tested in the conformance tests; Firefox supports allocation of multisampled floating-point renderbuffers.

The extension specification should be updated to allow the creation of multisampled floating-point renderbuffers, and allocation of them, rendering to them, and blitting from them and resolving to floating-point textures should be tested.

**Comment by kenrussell** [comment]
Note @jdashg @zhenyao @grorg @RafaelCintron in particular.

**Comment by msc-** [comment]
IIRC the underlying native extension does not require multi-sample floating point buffers to be supported. So, if the WebGL extension is to support them, applications will have to check for framebuffer completeness before using them. Perhaps that is why it was decided not to support them. I cannot recall.

The WebGL extension contradicts itself. The overview says there are no behavioral changes but then the notes says multi-sample buffers are not supported which is a behavioral change.

**Comment by kenrussell** [comment]
Changes to the extension and the conformance test were added in #1935 , #1946 , #1956 , and possibly other pull requests. Closing.
