### ISSUE TITLE
No tests for mis-matching uniform precision?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#1966]
I didn't check if there are tests but.... Ken says both Firefox and Chrome are passing all the WebGL conformance tests

Here's an example that runs on Firefox and fails on Chrome. According to @zhenyao it should fail

https://jsfiddle.net/greggman/xy8ygu7o/

According to @zhenyao the issue is `Lights` is `mediump` in the fragment shader but `highp` in the vertex shader

Checking the conformance tests I see this test from WebGL1

https://www.khronos.org/registry/webgl/sdk/tests/conformance/glsl/misc/shader-with-global-variable-precision-mismatch.html?webglVersion=2&quiet=0

But it doesn't cover the issue above.

**Comment by zhenyao** [comment]
I think Ken meant both Firefox and Chrome are passing WebGL 1 conformance tests, and this is WebGL2 specific.

We should have a test case in deqp/gles3, and I vaguely remember we tighten up validation in command buffer to pass that test, but I am not 100% sure.

**Comment by zhenyao** [comment]
It's tested in linkage.html

**Comment by greggman** [comment]
Ok Cool! 

I passed that on

https://bugzilla.mozilla.org/show_bug.cgi?id=1295001
