### ISSUE TITLE
WebGL 2.0 Reference Card

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#1980]
Is anyone making a WebGL 2.0 reference card like the [1.0 card](https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf) or the [ES 3.0 card](https://www.khronos.org/files/opengles3-quick-reference-card.pdf)?

If not is there any way I can help? No idea where the source for the cards are or what software is used to make them but happy to try to edit the ES3 one into the WebGL2 one ... or something

**Comment by kenrussell** [comment]
Thanks @greggman for the offer. :) After the most recent WebGL 2.0 spec change to add offsets and lengths to the various data upload methods (and thank you for the suggestion to do that), Khronos just started working on the WebGL 2.0 reference card. I expect they'll have a draft to look at in a few weeks.

**Comment by lmancini** [comment]
@greggman @kenrussell any news on this? Now that WebGL 2 is gaining support from major browsers, a handy reference card is becoming useful.

**Comment by greggman** [comment]
It just came out

https://www.khronos.org/files/webgl20-reference-guide.pdf
