### ISSUE TITLE
Update non-power of 2 texture section of WebGL2 spec

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2024]
I ran across this today. The spec says

> ### Non-Power-of-Two Texture Access
>
> Texture access works in the WebGL 2 API as in the OpenGL ES 3.0 API. Sampling a non-power-of-two image with wrapping mode other than CLAMP_TO_EDGE and minification filter other than NEAREST or LINEAR does not always return (R, G, B, A) = (0, 0, 0, 1) in the WebGL 2 API, i.e. mipmapping and all wrapping modes are supported for non-power-of-two images.

And I had to do a double take. That's really unclear what it's trying to say. 

> Sampling a non-power-of-two image with wrapping mode other than CLAMP_TO_EDGE 
and minification  filter other than NEAREST or LINEAR does not always return (R, G, B, A) = (0, 0, 0, 1) in the WebGL 2 API

Sounds like it's saying usually WebGL2 returns (0, 0, 0, 1) but not always so I went searching through the ES 3.0 spec for when it returns 0, 0, 0, 1 and when it doesn't.

I think it wants to say something like

> ### Non-Power-of-Two Texture Access
>
> Texture access works in the WebGL 2 API as in the OpenGL ES 3.0 API. In other words, unlike WebGL 1 there are no special restrictions on non power of 2 textures. All mipmapping and all wrapping modes are supported for non-power-of-two images.

Or something along those lines?

**Comment by zhenyao** [comment]
The change looks good to me. Thanks Gregg.  Can you upload a pull request for this change?

**Comment by kenrussell** [comment]
Yes, thanks Gregg for this simplification. It sounds much better. To save you time I've put together a pull request with your suggested change.

**Comment by kenrussell** [comment]
Thanks again Gregg for pointing this out and suggesting the cleanup. The PR above's been merged so closing this issue.
