### ISSUE TITLE
Remove ETC2/EAC compressed texture formats from WebGL 2.0 core

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2030]
On the public_webgl list it has been noted by developers that decompressing ETC2/EAC compressed texture formats in order to claim conformance on devices which don't support them natively is counter-productive; it increases the VRAM consumption by a factor of six. See https://www.khronos.org/webgl/public-mailing-list/archives/1609/threads.php#00000 .

After discussion, it sounds like the best option is to remove these enums from the core WebGL 2.0 specification, and leave them in the WEBGL_compressed_texture_es3 extension:
https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_es3/

So, for concrete steps:

1) Chrome should implement this draft extension, so there are two implementations (Firefox being the other): http://crbug.com/455568
2) It should be promoted to community approved.
3) The enums should be removed from the WebGL 2.0 spec, and the conformance tests updated to only run these tests if the extension is available.

**Comment by msc-** [comment]
Unless you can guarantee that you will never expose the extension when the native OGL advertises ETC2 support but is actually decompressing in software, this proposal is not going to solve the problem.

Also, _if_ the extension is to be carried forward, it should should be renamed from `es3` to `etc`. The current name will cause confusion in the future as ASTC is a required part of OpenGL ES 3.2, as well as OpenGL 4.3+, and I am sure we'll want to expose it to WebGL soon.

**Comment by kenrussell** [comment]
Thanks for your feedback Mark. I think this will address the issue for most problematic cases; Chrome contains ETC texture decompression code for the purpose of advertising universal support for these texture formats, and stopping using it will solve at least most, if not all, of the problem.

It's a good point about the naming of the extension. I'll talk directly with the extension author about renaming it.

**Comment by Maksims** [comment]
Thank you for addressing this issue.

Regarding naming, there is currently ETC1, and ETC2 being backwards-compatible with ETC1 although EAC being very similar, is used for 1/2 channel compression. And is part of ES3 extension.
ETC1 compression (`ETC1_RGB8`) can be decoded using `RGB8_ETC2`, so feels like `WEBGL_compressed_texture_etc` would be more appropriate name for this extension.

**Comment by kenrussell** [comment]
CC'ing @kainino0x who will be helping at least with Chrome's implementation if not also the tests.

**Comment by pyalot** [comment]
Please investigate if you can use:

* https://www.opengl.org/registry/specs/ARB/internalformat_query2.txt
* https://www.opengl.org/registry/specs/ARB/internalformat_query.txt
* https://www.khronos.org/registry/gles/extensions/OES/OES_required_internalformat.txt

to exclude offering ETC when no compression would result. An alternative to this would be ot investigate making a harmonized extension for WebGL of these extensions to achieve that goal for an application programmer.

**Comment by kenrussell** [comment]
For the record, in case it wasn't apparent from the commit from #2031 , the extension name decided upon was WEBGL_compressed_texture_es3_0.

Work is in progress to move it to community approved, and remove the associated enums from the core WebGL 2.0 spec.

**Comment by kainino0x** [comment]
Note: per #2047, this has been renamed again to WEBGL_compressed_texture_etc and moved to community approved.

**Comment by kainino0x** [comment]
Is there anything blocking this, or can we move forward with removing this from core WebGL 2 and merging #2053?

(I don't remember, but I can't find any blockers.)

**Comment by kainino0x** [comment]
I went ahead and updated the spec text in #2053. Once it is reviewed and merged, this issue will be fixed.
