### ISSUE TITLE
binding deleted objects don't generate an error?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2108]
Trying to understand this commit

https://github.com/KhronosGroup/WebGL/commit/0959d01874026c7211eed814e55cb1bd2d998d29

In real GL binding a deleted object makes a new object, at least for buffers, textures, renderbuffers, and framebuffers, since for those types of objects you don't have to call `gl.genXXX`. Delete just makes the id usable so calling bind makes a new object.

Since WebGL requires you to call `gl.createXXX` it seems like binding a deleted object should fail not silently pass. Especially because the behavior is different the GL (creating a new object) so if some emscripten code is counting on that behavior the silent do nothing behavior would lead to subtle bugs

**Comment by kenrussell** [comment]
Sorry Greg for not doing the code archaeology until now.

The spec was recently updated to generate INVALID_OPERATION when binding deleted objects. The conformance tests actually silently allowed this with no error until recently. Firefox had the preferred behavior, which was to generate INVALID_OPERATION.

The pull request making this change was #2002 , and the top-of-tree conformance suite was modified to require the new behavior. However, to avoid invalidating old conformance test results, the old suites had to be changed to allow both the old behavior (NO_ERROR) as well as the new behavior (INVALID_OPERATION). This was done in #2005 . (It's not obvious, but the link to that pull request is actually close to the top of the page of:
https://github.com/KhronosGroup/WebGL/commit/0959d01874026c7211eed814e55cb1bd2d998d29

Sorry again for the long delay getting back to you on this. The top-of-tree conformance tests have the behavior you describe. Closing.
