### ISSUE TITLE
New bufferData/bufferSubData overloads need some prose defining what they actually do

### ISSUE THREAD

**Issue by bzbarsky** [KhronosGroup/WebGL#2143]
WebGL2 adds a new overload of `bufferData` that looks like this:

    void bufferData(GLenum target, ArrayBufferView srcData, GLenum usage,
                              GLuint srcOffset, optional GLuint length = 0);

but doesn't define the behavior anywhere.  The usual "just do what GL ES 3.0 does" thing doesn't work here, because GL ES 3.0 has a single glBufferData which as far as I can tell just takes a pointer to the data and how many bytes to grab.  That has no equivalent for the above overload....  In particular, something needs to define what "srcOffset" and "length" actually mean here.

Similar problem for `bufferSubData`.

Please make sure to define what "srcOffset" and "length" mean here when srcData is a DataView, not a typed array.

**Comment by kenrussell** [comment]
Fixed in above pull request. A follow-on one will address minor concerns with it.
