### ISSUE TITLE
Spec should have a link to the github repo

### ISSUE THREAD

**Issue by bzbarsky** [KhronosGroup/WebGL#2144]
Right now the only feedback option the spec mentions is the public_webgl mailing list, and even that is somewhat hidden in the "Status of this document" section.  Compare how https://heycam.github.io/webidl/ has a "Feedback" section in the header or https://dom.spec.whatwg.org/ has a "Participate" section, both with links to the preferred place for issues.

**Comment by kenrussell** [comment]
Fixed per above.
