### ISSUE TITLE
When based on OpenGL ES 3.1?

### ISSUE THREAD

**Issue by liyuxi** [KhronosGroup/WebGL#2163]

**Comment by liyuxi** [comment]
and add ASTC support

**Comment by kenrussell** [comment]
The current plan is to add the OpenGL ES 3.1 entry points as an extension to WebGL 2.0. This will allow it to be deployed more quickly on the platforms where it can be easily supported (Windows, Linux, Android).

#2172 adds a conformance test for the ASTC extension, which is the needed missing piece to deploying it. Once that new test has been reviewed the extension should ship in browsers soon afterward.

Closing this issue.
