### ISSUE TITLE
TexSubImage3D with no width, height, depth not documented?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2263]
I wrote some code calling TexSubImage3D as

   gl.texSubImage3D(target, level, xoffset, yoffset, zoffset, format, type, canvas)

And it worked but looking at [the spec](https://www.khronos.org/registry/webgl/specs/latest/2.0/) there's no such function. All functions require width, height, depth

```
  void texSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset,
                     GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type,
                     GLintptr pboOffset);
  void texSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset,
                     GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type,
                     TexImageSource source); // May throw DOMException
  void texSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset,
                     GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type,
                     ArrayBufferView? srcData, optional GLuint srcOffset = 0);
```

Am I having a brain fart? 

I just assumed the function existed and would use the image.width for width, image.height for height and 1 for depth and it's working but it doesn't seem to be documented.

**Comment by greggman** [comment]
Nevermind. This is a bug in chrome 55. It's fixed in Canary and works as expected in Firefox (as in the undocumented function has been removed from Chrome and now fails)

**Comment by kenrussell** [comment]
Yes, sorry about that, but the WebGL-specific functions were under-tested and these bugs didn't show up until later. It might be fixed in Chrome 56, which is the official version WebGL 2.0 is enabled in?
