### ISSUE TITLE
[WebGL2.0] are Bit manipulations allowed in shaders, following OpenGL ES 3.0?

### ISSUE THREAD

**Issue by erichlof** [KhronosGroup/WebGL#2269]
Hi @kenrussell and all,

I want to port some OpenCL GPU kernels over to WebGL 2.0 using GLSL.  The original code is ray tracing BVH stuff.  The OpenCL code uses basic Bit manipulations such as shifting ( << and >> ) 'ANDing' ( & ) 'XORing' (^) and 'ORing' ( I ).  I have looked at the OpenGL ES 3.0 and it does indeed allow bit manipulations.

Can I expect to use such functionality when WebGL 2.0 lands in Chrome 56?

Thanks!
-Erich

**Comment by zhenyao** [comment]
Yes, WebGL2 supports them.

**Comment by zhenyao** [comment]
Note that even WebGL 1 supports them.

**Comment by erichlof** [comment]
@zhenyao 
Thank you, that's great news.  Regarding WebGL 1.0, when I try doing something like 
int i = 16 << 1; 
 it gives me an error in Chrome console reading: 
THREE.WebGLShader: gl.getShaderInfoLog() fragment ERROR: 0:182: '<<' : bit-wise operator supported in GLSL ES 3.00 and above only 

Do I have to initialize or enable something at the top of my fragment shader?

Thanks for any clarification!
-Erich

**Comment by zhenyao** [comment]
Ah, sorry for misleading.  I read the GLSL ES 1.0 spec again, bitwise
operators are listed as reserved, which means they are not supported yet.
So no bitwise operators in WebGL1. They are definitely supported in WebGL2.

**Comment by erichlof** [comment]
@zhenyao 
Ok I understand.  Thank you for the clarification!  I look forward to using bit-manipulations when WebGL 2.0 lands.  I'll close this issue.  Thank you all for your efforts - I really enjoy graphics programming right inside my browser using WebGL (coming from the challenging days of Windows 98 and OpenGL 1.2, ha ha)!

**Comment by zhenyao** [comment]
If you don't know it already, you can already play with WebGL2 in Chrome Beta, or Chrome Stable if you enable "WebGL 2.0 Prototype" in about:flags.

**Comment by erichlof** [comment]
Great, thanks for the tip! :-)
