### ISSUE TITLE
Test suite depends on random images on the web

### ISSUE THREAD

**Issue by bzbarsky** [KhronosGroup/WebGL#2273]
Specifically, the test suite requires loading of http://www.opengl.org/img/opengl_logo.jpg (which is not good at all, but at least you could make the argument that the Khronos group controls that image) and of http://mashable.com/wp-content/uploads/2008/08/thunderbird-logo-64x64.png (which is just completely unacceptable, because it could disappear at any time, breaking the test suite).

**Comment by zhenyao** [comment]
Can you point out which tests use these images?

**Comment by bzbarsky** [comment]
readPixelsBadArgs.html, origin-clean-conformance.html, texImage2DHTML.html, texSubImage2DHTML.html

But really, you can probably use grep just as well as I can...

**Comment by zhenyao** [comment]
They are used for cross origin testing and there is an option to use the local url.

**Comment by bzbarsky** [comment]
I understand what they are used for.  I'm saying that using files that you don't control for that purpose is completely nuts.

**Comment by bzbarsky** [comment]
For practical purposes in terms of running this stuff in automation, by the way, it would be a lot more useful if the harness allowed providing a list of possible hostnames it might run at as opposed to hardcoding localhost/127.0.0.1.  But we can solve this in other ways in automation too.  This issue is really about the hosted version of the tests at https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html for example.

**Comment by kenrussell** [comment]
Fixed per above. These resources all now point to the Khronos-controlled domain get.webgl.org.

**Comment by bzbarsky** [comment]
Thank you!
