### ISSUE TITLE
What error for glDrawElements with a negative offset?

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/WebGL#2287]
In the WebGL CTS there is a test checking that INVALID_VALUE is generated when the offset parameter to DrawElements is negative. The check was [originally added](https://github.com/KhronosGroup/WebGL/commit/7980f486de20ed486371c345c43e6eefbbdc3b36#diff-a43003bac86566881758d8c82e4fbb46R57) in a very old commit and is now in [common code](https://github.com/KhronosGroup/WebGL/blob/5f654b7708979d45a8144c6280f1c30db8f52014/sdk/tests/js/tests/out-of-bounds-test.js#L30) used in conformance/rendering/draw-elements-out-of-bounds.html.

Neither of the WebGL or OpenGL ES specifications include an error case for a negative offset. The WebGL specification section 6.5 has an error case for OOB element buffer reads that gives INVALID_OPERATION if offset < 0 and count > 0 but that's it.

Mo pointed out that in multiple places in the OpenGL ES specification there are `offset` intptr arguments that produce INVALID_VALUE if their are negative (such as BindBufferRange and CopyBufferSubData).

Should we specify the behavior tested in the CTS or change the CTS to follow the rules outlined in Section 6.5?

**Comment by kenrussell** [comment]
Sorry for the long delay getting to this.

At this point I think we should specify the behavior that's tested in the CTS. This would be a small addition to the drawElements documentation in section 5.14.11 "Writing to the drawing buffer". Could you put up such a pull request?

**Comment by Kangz** [comment]
Whoops hadn't seen this, will get to it.
