### ISSUE TITLE
check varyings match uniforms?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#229]
I recently ran into an issue where in the vertex shader I had this

```
// -- vertex shader --
...
attribute vec4 color;
varying vec4 v_color
void main() {
  v_color = color;
  ...
}

// -- fragment shader --
...
uniform vec4 v_color
void main() {
  gl_FragColor = v_color;
}
```

I got no error. The error is in the vertex shader I used 'varying" but in the fragment shader I used "uniform". It's not clear to me if this should generate an error or not.

**Comment by jdashg** [comment]
Seems like this is expected behavior when you dig into the specs.
