### ISSUE TITLE
Diff between WebGL and GLES 2.0: no shader binary, SHADER_COMPILER should be always true

### ISSUE THREAD

**Issue by Richard-Yunchao** [KhronosGroup/WebGL#2340]
I read the WebGL spec, but I didn't find such a section among all differences between WebGL and OpenGL ES 2.0: https://www.khronos.org/registry/webgl/specs/latest/1.0/#6. 

In WebGL 2 spec, there is a section <no program binary>: https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.4. 

So should we add a section to WebGL spec to explicitly say that there is no shader binary in WebGL? @kenrussell and @zhenyao

**Comment by zhenyao** [comment]
Right, we should mention it in the difference section.

**Comment by Richard-Yunchao** [comment]
This issue has been resolved. Closing...
