### ISSUE TITLE
WebGL2 implementations not supporting the default transform feedback

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2347]
I might be missing something but ... according to the OpenGL ES 3.0 spec, if there is no transform feedback bound then the default transform feedback object is bound and unless I'm missing it should act exactly the same as any other transform feedback

I thought WebGL2 would probably disallow the default transformfeedback the same way it disallows the default textures.

But, the WebGL2 spec says it's supported

[Section 3.7.15](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.15)

> `void bindTransformFeedback (GLenum target, WebGLTransformFeedback? transformFeedback)` (OpenGL ES 3.0.4 §2.14.1, man page)
> Bind the given WebGLTransformFeedback object. **If transformFeedback is `null`, the default transform feedback object provided by the context is bound**. 

So I tried it but I got errors in both firefox and chrome.

https://jsfiddle.net/greggman/rc2ja9u7/

It's possible I'm doing something wrong. If you just change line

From:

    const tf = null; // Use the default transform feedback  ... gl.createTransformFeedback(); 
 
To:

    const tf = gl.createTransformFeedback(); 

Then it works but AFAICT it should work as well with the default transformfeedback object.

If the test is correct either the implementations need to change or the spec needs to change. If it's the spec to disallow the default transformfeedback object it would seem like it should also require more errors (calling gl.bindBufferBase/gl.bindBufferRange) when no transformfeedback is bound etc. Otherwise the implementations need to change

**Comment by zhenyao** [comment]
Chrome has a fake "default" transformfeedback in GPU command buffer, so in theory you never see the real default one and the fake one just acts the same as any other transformfeedback.

However, we have a bug in WebGL because WebGL needs to create its own "fake" default one. @kenrussell has a CL that might just fix this.

If you can minimize your code into a test case, that would be really appreciated.

**Comment by greggman** [comment]
This brings up the question what happens if I call `gl.getParameter(gl.TRANSFORM_FEEDBACK_BINDING)` when the default transform feedback is bound do I get a `WebGLTransformFeedback`? I assume no, I get `null` but that should probably be specced and tested.

**Comment by kenrussell** [comment]
Explicitly supporting the default transform feedback object might not be the best direction. Perhaps the spec should be revised to require that one is created. I'm not sure. It looks to me like the ported dEQP tests only test the case where a transform feedback object was explicitly created. On the other hand, it was necessary to support the default Vertex Array Object.

Yes, in Chrome, once this is better fixed, querying the TRANSFORM_FEEDBACK_BINDING when the default transform feedback is bound will return null.

If we decide to forbid the default transform feedback object then a conformance test will need to be added.

It will almost surely be necessary to update the buffer binding restrictions that are currently in the spec.

CC @jdashg for comments.

**Comment by greggman** [comment]
I should be clear (mentioned in the PR) that default transform feedback is working on both Firefox and Chrome. My example was bad. Once fixed it started working. That's separate from the binding issues brought up elsewhere.

Personally I think you should keep the default objects. I'd even suggest you add back in the default textures. It doesn't seem like there's some compelling reason to not support all the default objects or if there is I'm unaware if it.
