### ISSUE TITLE
Float32List and Int32List uses WebIDL sequence type not in generic way

### ISSUE THREAD

**Issue by SaschaNaz** [KhronosGroup/WebGL#2356]
```webidl
typedef (Float32Array or sequence) Float32List;
typedef (Int32Array or sequence) Int32List;
```

This should probably use `sequence<GLfloat>` to [match WebIDL spec](https://heycam.github.io/webidl/#idl-sequence): 

>The sequence\<T\> type is a parameterized type whose values are (possibly zero-length) lists of values of type T.

```webidl
typedef (Float32Array or sequence<GLfloat>) Float32List;
typedef (Int32Array or sequence<GLfloat>) Int32List;
```

**Comment by SaschaNaz** [comment]
Just found that WebGL 2 redefined them.

**Comment by kenrussell** [comment]
No, you're right, there's an error in the HTML. The intent was for these to be parameterized, but we didn't escape the angle brackets.
