### ISSUE TITLE
Clarify intended usage of STENCIL_INDEX constant

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/WebGL#2370]
Originally I had [posted this question on StackOverflow](http://stackoverflow.com/questions/43445727/where-is-the-stencil-index-constant-used-in-webgl) and @greggman's answer mentioned I should probably cross-post it here.

> In the [WebGL 1 specification][1], I noticed there is a constant `const GLenum STENCIL_INDEX = 0x1901;` and was wondering how it is used. I have been attempting to use it with either textures or renderbuffers although none of the combinations I've attempted have worked. For example, I've attempted using `STENCIL_INDEX` instead of `STENCIL_INDEX8` for the renderbuffer in the example below, or calling `texImage2D` with `STENCIL_INDEX8` as internal format and `STENCIL_INDEX` as format.
> 
> In either WebGL 1 or 2 (with any extensions enabled if required), I am wondering where the constant `STENCIL_INDEX` could be used in either a texture, renderbuffer, or some attachment configuration. Even if this is hardware specific I'm still interested in knowing how it is used.
> 
> For example, I am curious how the code below could be modified to use `STENCIL_INDEX` (*not* `STENCIL_INDEX8` -- note that this constant already being used in a renderbuffer):
> 
> 
> 
> 
> 
>     const pixel = new Uint8Array([0, 0, 0, 0]);
> 
>     for (const version of ['webgl', 'webgl2']) {
>       const canvas = document.createElement('canvas'),
>         gl = canvas.getContext(version, {stencil: true}),
>         framebuffer = gl.createFramebuffer(),
>         stencilbuffer = gl.createRenderbuffer(),
>         texture = gl.createTexture();
> 
>       canvas.width = 1;
>       canvas.height = 1;
> 
>       gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);
> 
>       gl.bindRenderbuffer(gl.RENDERBUFFER, stencilbuffer);
>       gl.renderbufferStorage(gl.RENDERBUFFER, gl.STENCIL_INDEX8, 1, 1);
>       gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.STENCIL_ATTACHMENT, gl.RENDERBUFFER, stencilbuffer);
> 
>       gl.bindTexture(gl.TEXTURE_2D, texture);
>       gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, pixel);
>       gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
>       gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
>       gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0);
> 
>       const status = gl.checkFramebufferStatus(gl.FRAMEBUFFER);
>       if (status !== gl.FRAMEBUFFER_COMPLETE) {
>         console.error(status, version);
>       }
> 
>       gl.deleteTexture(texture);
>       gl.deleteRenderbuffer(stencilbuffer);
>       gl.deleteFramebuffer(framebuffer);
>     }
> 
> 
> 
> I did see the [`OES_texture_stencil8` extension in OpenGL ES 3.1][2], although even there it states that the `STENCIL_INDEX` constant already exists. So what is the constant's purpose in OpenGL ES and how does this relate to usage in WebGL?
>
>I also found [this line of commented code referencing `STENCIL_INDEX` in Chromium][3], which is why I thought I'd raise it here in case this behavior is known. Likewise Firefox doesn't seem to list [`STENCIL_INDEX` in its formats enum][4] and doesn't seem to reference `STENCIL_INDEX` except conformance tests ensuring that the constant exists and has the value `0x1901`.

@greggman's answer also raises a good point:

> Checking the [OpenGL ES 2.0 spec](https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf) there appears to be no mention of `STENCIL_INDEX` and `STENCIL_INDEX` is also not in the [OpenGL ES 2.0 headers](https://www.khronos.org/registry/OpenGL/api/GLES2/gl2.h)
> 
> There's also no mention of it in the [OpenGL ES 3.0 spec](https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf) nor the [ES 3.0 headers](https://www.khronos.org/registry/OpenGL/api/GLES3/gl3.h). It's not until [ES 3.1](https://www.khronos.org/registry/OpenGL/specs/es/3.1/es_spec_3.1.pdf) that it appears

  [1]: https://www.khronos.org/registry/webgl/specs/latest/1.0/
  [2]: https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_stencil8.txt
  [3]: https://cs.chromium.org/chromium/src/third_party/skia/src/gpu/gl/GrGLCaps.cpp?type=cs&q=STENCIL_INDEX%20package:%5Echromium$&l=1116
  [4]: https://dxr.mozilla.org/mozilla-beta/source/dom/canvas/WebGLFormats.h#20

**Comment by zhenyao** [comment]
STENCIL_INDEX is a desktop GL only format.  It's not part of ES.

**Comment by grovesNL** [comment]
@zhenyao I am not sure I understand -- your statement doesn't appear to be true.

As I stated above, `STENCIL_INDEX` is defined in WebGL. As well OpenGL ES specification and reference pages refer to `STENCIL_INDEX` in many places.

For example OpenGL ES 3.1 references `GL_STENCIL_INDEX` in [`glTexParameter`](https://www.khronos.org/registry/OpenGL-Refpages/es3.1/html/glTexParameter.xhtml), [`glTexImage3D`](https://www.khronos.org/registry/OpenGL-Refpages/es3.1/html/glTexImage3D.xhtml), the [`OES_texture_stencil8`](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_stencil8.txt) extension I referenced above, etc.

Furthermore why is the constant defined in [WebGL 1.0 specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/) as `const GLenum STENCIL_INDEX = 0x1901;` if it's truly not intended to be used anywhere? [That is confusing and at worst misleading for developers converting OpenGL ES code to WebGL](http://stackoverflow.com/questions/33712764/webgl-reading-stencil-buffer#comment55197030_33712764).

**Comment by zhenyao** [comment]
WebGL 1.0 exposes ES 2.0, and WebGL 2.0 exposes ES 3.0.  ES 3.1 is irrelevant.

Also, OES_texture_stencil8 is not exposed to WebGL as an extension, so it's also irrelevant.

I agree exposing the contant in the WebGL 1.0 spec is confusing and misleading.  We should remove it in my opinion.

**Comment by kenrussell** [comment]
@grovesNL this looks like an oversight. Sorry about the confusion. We'll remove this unused constant from the spec and conformance tests.

**Comment by grovesNL** [comment]
Thanks everyone. Removal seems like the best option.

@zhenyao To clarify I mentioned the presence of `STENCIL_INDEX` in OpenGL ES 3.1 only to address your comment that "It's not part of ES." I understand WebGL is not targeting ES 3.1+ yet so I agree that it's irrelevant.

**Comment by zhenyao** [comment]
Sorry for not being precise. Glad we are on the same page.

**Comment by grovesNL** [comment]
Addressed by #2371
