### ISSUE TITLE
Clarify intended behavior for `isEnabled` and `getParameter` for certain capabilities

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/WebGL#2384]
As I wrote [on StackOverflow](http://stackoverflow.com/questions/43613793/difference-between-webglrenderingcontext-isenabledgetparameter-for-capabili/43622669) (some of the question snipped for brevity), the code below shows an inconsistency between browsers responding to `isEnabled` and `getParameter` for `SAMPLE_ALPHA_TO_COVERAGE`, `SAMPLE_COVERAGE`, and `STENCIL_TEST`.

> 
> 
> 
>     var canvas = document.createElement('canvas')
>     ,   gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl')
>     ,   capabilities = [ 'SAMPLE_ALPHA_TO_COVERAGE', 'SAMPLE_COVERAGE', 'STENCIL_TEST' ];
>     for (var i = 0; i < capabilities.length; i++) {
>         var capability = gl[capabilities[i]];
>         gl.enable(capability);
>         var isEnabledResult = gl.isEnabled(capability)
>         ,   getParameterResult = gl.getParameter(capability);
>         if (isEnabledResult !== getParameterResult) {
>             console.log(capabilities[i], isEnabledResult, getParameterResult);
>         }
>     }
> 
> 
> - With WebGL1 on Chrome/Canary I receive the following (`STENCIL_TEST` will be removed here if the stencil buffer is enabled while creating the context):
> 
>         SAMPLE_ALPHA_TO_COVERAGE true null
>         SAMPLE_COVERAGE true null
>         STENCIL_TEST true false
> 
> - With WebGL1 on Firefox/Nightly, IE11, and Edge (regardless of stencil buffer being enabled):
> 
>         SAMPLE_ALPHA_TO_COVERAGE true null 
>         SAMPLE_COVERAGE true null
> 
> - With WebGL2 on Chrome/Canary (`STENCIL_TEST` will be removed here if stencil buffer is enabled):
> 
>         STENCIL_TEST true false
> 
> - With WebGL2 on Firefox/Nightly, I receive nothing.

@jdashg's [answer to my question](http://stackoverflow.com/a/43622669/3190758) suggested that there may be some issues with the behavior of `getParameter` for the above cases and that `isEnabled` and `getParameter` should behave the same in these cases.

There are a couple issues that seem to require clarification in the specification:

- Should both `gl.isEnabled(gl.STENCIL_TEST)` and `gl.getParameter(gl.STENCIL_TEST)` return `true` or `false` when the context is created without the stencil buffer (i.e. without `{stencil: true}`)?
- Should `gl.getParameter(gl.SAMPLE_ALPHA_TO_COVERAGE)` and `gl.getParameter(gl.SAMPLE_COVERAGE)` match behavior between WebGL1 and WebGL2 contexts (i.e. backport WebGL2 `getParameter` behavior for these constants)?

**Comment by zhenyao** [comment]
Looking at both ES2/ES3 spec, it seems STENCIL_TEST/SAMPLE_COVERGAE/SAMPLE_ALPHA_TO_COVERAGE states should all be queried using IsEnabled.  The man pages of ES2/ES3 are incorrectly include them in glGet*() function. I think we should add a conformance test and fix the browser behaviors.

As for STENCIL_TEST specifically, even without stencil:true, we should still allow it to be true because fbo may be created with a stencil image.

@kainino0x @kenrussell @jdashg @grorg @RafaelCintron What do you think?

**Comment by kainino0x** [comment]
The state tables (3.0 Tables 6.7, 6.11, 2.0 Tables 6.6, 6.10) say that all of these are queried using IsEnabled. But at the top of that section (6.2):

>  However, state variables for which IsEnabled is listed as the query command can also be obtained using GetBooleanv, GetIntegerv, GetInteger64v, and GetFloatv.

isEnabled and getParameter should definitely be returning the same values in all of these cases.

**Comment by zhenyao** [comment]
@kainino0x Thanks for finding the spec reference.  So it looks like WebGL 1.0 spec has a bug that getParameter() leaves SAMPLE_COVERGAE/SAMPLE_ALPHA_TO_COVERAGE out while other capabilities are included. I think we should fix the spec and add a conformance test.

**Comment by kenrussell** [comment]
@kainino0x could I ask you to pick this up, clarify these queries and add a targeted conformance test ensuring that (a) these queries succeed, (b) that no exceptions are thrown during them and (c) that no GL errors are generated during them? Thanks.

**Comment by zhenyao** [comment]
two more test cases:
(d) isEnabled() and getParameter() on capabilities are consistent, (e) STENCIL_TEST can be true even if WebGL context is created without {stencil:true} (maybe also DEPTH_TEST can be true if WebGL context is created with {depth:false}).

**Comment by grovesNL** [comment]
Looks great, thanks all.
