### ISSUE TITLE
WebGL2 drawArraysInstanced etc seem to be based on ANGLE but differences not documented

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2419]
Here's a small sample that uses `drawArrays` and `drawArraysInstanced` in WebGL2.

https://jsfiddle.net/greggman/pxqvk4pg/

For `drawArraysInstanced` I get the error

    chrome: GL ERROR :GL_INVALID_OPERATION : glDrawArraysIntancedANGLE: attempt to draw with all attributes having non-zero divisors
    firefox: WebGL warning: drawArraysInstanced: at least one vertex attribute divisor should be 0

AFAICT no such limit exists in OpenGL ES 3.0 and the limit is not documented as a difference in the spec in the WebGL2 docs

The docs probably need to mention that limitation

**Comment by computersarecool** [comment]
Is there a reason this has to be an error?  Here is a reason why it'd be great if this didn't print an error / if there was not this limitation:  

Frequently I start drawing a shape while waiting for its shader to load asynchronously. While loading I use a temp shader for which no attributes have divisors.  With the current settings my program prints errors to the console until the real shader has loaded.

I don't see why this has to be an error in WebGL2 but not in OpenGL.

**Comment by zhenyao** [comment]
@greggman is correct the limitation came from ANGLE.  In [ANGLE_instanced_arrays](https://www.khronos.org/registry/OpenGL/extensions/ANGLE/ANGLE_instanced_arrays.txt), we have a limitation due to D3D: """
    INVALID_OPERATION is generated by DrawArraysInstancedANGLE or
    DrawElementsInstancedANGLE if there is not at least one enabled
    vertex attribute array that has a <divisor> of zero and is bound to an
    active generic attribute value in the program used for the draw command.
"""
@vonture @null77 Can we lift this limit in D3D11? If not, we probably need to add the constraints to WebGL2 spec and add a conformance test (the current test is the WebGL1 extension test).

@jdashg: what do you think?

**Comment by computersarecool** [comment]
Additionally, I can think of situations where I want to instance using only `gl_InstanceID` (to apply an offset or something) in a shader with no `in` attributes at all.

**Comment by kenrussell** [comment]
Not sure whether this restriction is still necessary. @null77 @vonture in ANGLE's current D3D11 backend, do we still need to have at least one vertex attribute with a divisor of 0 for efficiency?

If so then we should just update the WebGL 2.0 spec to document this. There have been other restrictions added to WebGL 2.0 for efficiency on D3D based implementations.

**Comment by null77** [comment]
Did no one look at the extension spec? :)

    1) Should vertex attribute zero be instance-able?

       Resolved: Yes. 
       Discussion: In Direct3D 9 stream 0 must be specified as indexed data
       and it cannot be instanced. In ANGLE we can work around this by
       remapping any other stream that does have indexed data (ie a zero
       attribute divisor) to stream 0 in D3D9. This works because the HLSL
       vertex shader matches attributes against the stream by using the 
       shader semantic index.

    2) Can all vertex attributes be instanced simultaneously?

       Resolved: No
       Discussion: In rare cases it is possible for no attribute to have a 
       divisor of 0, meaning that all attributes are instanced and none of
       them are regularly indexed. This in turn means each instance can only
       have a single position element, and so it only actually renders
       something when rendering point primitives. This is not a very 
       meaningful way of using instancing (which is likely why D3D restricts
       stream 0 to be indexed regularly for position data in the first place).
       We could implement it by drawing these points one at a time (essentially
       emulating instancing), but it would not be very efficient and there
       seems to be little-to-no value in doing so.

       If all of the enabled vertex attribute arrays that are bound to active
       generic attributes in the program have a non-zero divisor, the draw
       call should return INVALID_OPERATION.

I believe for WebGL 2 we could technically omit this restriction since I don't believe D3D11 has any such limitation.

@shannonwoods do you have any additional comments? Likely you were around at the time this was written.

**Comment by shannonwoods** [comment]
Correct, there are no other reasons for the restriction than D3D9. ANGLE doesn't support ES3 over D3D9, and drawArraysInstanced has moved to core, so there's no reason for browsers to enforce the ANGLE extension restrictions on WebGL 2 contexts AFAIK.

**Comment by greggman** [comment]
@computersarecool, if you have no attributes then could you not use `gl_VertexID` instead of `gl_InstanceID` as long as you pass in a count?

    uniform int count;  // number verts per instance

    int instanceID = gl_VertexId / count;
    int vertexId = gl_VertexId % count;

Not saying they shouldn't remove the restriction, only suggesting a solution until then

**Comment by computersarecool** [comment]
@greggman Good idea. Thank you.

**Comment by computersarecool** [comment]
@greggman I could do that but currently I don't think I can even call `drawElementsInstanced` without an attribute that has a divisor or that error will be thrown.

**Comment by greggman** [comment]
@computersarecool yes, I was assuming you'd call `drawArrays` with no attributes enabled

     gl.uniform1i(countLocation, numVertexPerInstance);
     gl.drawArrays(primitiveType, 0, numVertexPerInstance * numInstances);

**Comment by zhenyao** [comment]
We will discuss this in the next working group meeting and make a decision then.

**Comment by zhenyao** [comment]
Fixed.

**Comment by RafaelCintron** [comment]
I agree with the conclusion of this issue and the changes to the conformance suite.

However the WebGL 2 spec still contains the restriction that at least one enabled vertex attribute array needs to have a zero divisor or INVALID_OPERATION must be flagged.  See section [5.6](https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.6)

Unless I am missing something, I think this section of the spec should be clarified or deleted.

**Comment by tolkanabroski** [comment]
Works on Windows 10 x64

Chrome Cannary Version 64.0.3252.1
Opera 48.0.2685.52 

Fails in Firefox 56

**Comment by jdashg** [comment]
Fixed in #2662.

**Comment by kupiakos** [comment]
Is there a bug tracking this change on Firefox's end?

**Comment by jdashg** [comment]
Oops, I'm fixing this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1679693
Thanks for checking!
