### ISSUE TITLE
Calling framebufferRenderbuffer without bindRenderbuffer

### ISSUE THREAD

**Issue by RafaelCintron** [KhronosGroup/WebGL#2423]
While writing conformance tests today, I discovered an interoperability bug between browsers with framebufferRenderBuffer.

Consider the following piece of code:
```javascript
let renderbuffer = gl.createRenderbuffer();
gl.framebufferRenderbuffer(gl.FRAMEBUFFER, attachment.enum, gl.RENDERBUFFER, renderbuffer);
wtu.glErrorShouldBe(gl, gl.NO_ERROR);
assertMsg(renderbuffer === gl.getFramebufferAttachmentParameter(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.FRAMEBUFFER_ATTACHMENT_OBJECT_NAME),"renderbuffer attachment suceeded");
```
On Chrome, the call to framebufferRenderbuffer fails with INVALID_OPERATION but the attachment succeeds, yielding a "pass" for the subsequent assertMsg.
On Firefox and Edge, both the call to framebufferRenderbuffer and subsequent assertMsg succeed.

Angle, on the other hand, forbids calling framebufferRenderbuffer without first calling bindRenderbuffer.  
```C++
// [OpenGL ES 2.0.25] Section 4.4.3 page 112
// [OpenGL ES 3.0.2] Section 4.4.2 page 201
// 'renderbuffer' must be either zero or the name of an existing renderbuffer object of
// type 'renderbuffertarget', otherwise an INVALID_OPERATION error is generated.
if (renderbuffer != 0)
{
    if (!context->getRenderbuffer(renderbuffer))
    {
        context->handleError(Error(GL_INVALID_OPERATION));
        return false;
    }
}
```
Such a restriction is certainly necessary for `bindTexture` before `framebufferTexture2D` because, otherwise, you would have no way to know whether to accept cubemap or non-cubemap texture targets.  So it makes sense to have the same restriction for `bindRenderbuffer` before `framebufferRenderbuffer`.

As I see it, our choices are to either have framebufferRenderbuffer flag no error and for the attachment to succeed OR have frambufferRenderbuffer flag an error and have the attachment fail. Either way, Chrome's current behavior will have to change.

The downside to the latter approach is potential compatibility issues for existing content that, today, freely calls `createRenderBuffer` followed by `framebufferRenderbuffer` without first calling `bindRenderbuffer`.  In spite of this, I'm still inclined to favor the latter behavior.  

Thoughts?

**Comment by zhenyao** [comment]
I also favor the second option, to generate an error when framebufferRenderbuffer is called with a rbo that's not initialized through bindRenderbuffer.

Chrome's behavior is caused by discrepancy between Blink/CommandBuffer and ANGLE.  i.e., we allow framebufferRenderbuffer to succeed in this situation in Blink/CommandBuffer side and cache the attachment on the client side without checking GL errors (which will cause the round loop and very slow). It should be an easy fix and I will not worry too much about breaking existing content because they at least should not run successfully on Windows (ANGLE).

**Comment by RafaelCintron** [comment]
Good point about the code now running successfully on Windows, @zhenyao .  WebGL implemented on top of OpenGL will also have this problem if the OpenGL implementation is a conformant one.

**Comment by msc-** [comment]
The meaning of the phrase "of type 'renderbuffertarget'" is not clear. However "existing renderbuffer object" clearly means the renderbuffer object must have been created which requires binding the name (WebGL object) at some point. But there is no requirement that I can see in the ES 3.0.5 spec. that says the renderbuffer object has to be bound at the time you call `gl.framebufferRenderbuffer()`.

It's not clear to me what ANGLE's `context->getRenderbuffer(renderbuffer)` is doing.  If it is checking that `renderbuffer` is bound to the context's RENDERBUFFER target that is the wrong test.

**Comment by kenrussell** [comment]
The question is only whether the renderbuffer has ever been bound to the RENDERBUFFER target, thereby initializing it as an object of type renderbuffer. There's no requirement that the object currently be bound to the RENDERBUFFER target.

I'm in favor of adopting the stricter behavior: generating INVALID_OPERATION everywhere, and rejecting the framebufferRenderbuffer call, if the WebGLRenderbuffer has never been bound to the RENDERBUFFER target.

**Comment by RafaelCintron** [comment]
I agree with @kenrussell on adopting the stricter behavior.

**Comment by jdashg** [comment]
The base specs definitely require that bind* is called before framebuffer*, so I think we can consider this clarified.

**Comment by kenrussell** [comment]
OK. More tests of this are still needed.
