### ISSUE TITLE
OES_draw_elements_base_vertex as a WebGL extension?

### ISSUE THREAD

**Issue by Groovounet** [KhronosGroup/WebGL#2434]
OpenGL ES has a very useful extension called [OES_draw_elements_base_vertex](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_draw_elements_base_vertex.txt) that was added to OpenGL ES 3.2 specification. 

Unity makes great use of the base vertex functionality to reduce CPU overhead with our static batching and or text rendering. It would be great if this extension was supported in WebGL so that we can render a lot more complex scenes.

Thanks,
Christophe

**Comment by zhenyao** [comment]
I think this has been a part of Desktop GL since 3.X or so. D3D9 also supports this.

My only question is if it's possible to expose this functionality to iOS.

**Comment by jdashg** [comment]
Draw*BaseVertex is core in ES32 and GL32, so support for this should be /fairly/ good, though not universal.

There's a chance that emulating this within webgl implementations may be faster than emulating it from webgl libraries, a la the multi_draw findings. (though clearly not on the same order of magnitude!)

**Comment by shrekshao** [comment]
@Groovounet Hi Christophe. I'm working on proposal and prototype of base vertex extension now. Could you provide a bit more details about the use case of Base Vertex? It seems that gl_VertexID is only available in glsl 300 and doesn't seem that it could be easily emulated (unlike gl_InstanceID). gl_BaseVertex is even less available. But is this variable important in most use cases? I assume if it is only for static mesh batching the builtin variables wouldn't be a must-have.

**Comment by kenrussell** [comment]
Per offline discussion (since not sure Christophe will still comment) -

Let's plan to only expose the gl_BaseVertex and gl_BaseInstance shader variables in WebGL 2.0 contexts, but to expose these APIs on both WebGL 1.0 and 2.0. (gl_VertexID and gl_InstanceID are only available in WebGL 2.0, anyway.)

@sebbi recently asked on Twitter about these extensions and might have more comments.

**Comment by jdashg** [comment]
Tracking #2937.
