### ISSUE TITLE
Rethink object deletion semantics and container objects

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2456]
In #2178 the semantics of deleting objects were rethought and clarified. There are still some concerns about the portability of the new semantics, especially around deletion of objects which are still attached to container objects.

Taking Buffers and one of their container objects (VAOs) as an example, the following behavior is definitely portable:

1) If Buffer B1 is attached to VAOs V1 and V2, V1 is currently bound, and B1 is deleted, it should be unbound from V1 but not V2.

2) If V2 is then bound and B1 is deleted again, it should not be unbound from V2.

3) IsBuffer should probably start returning false for B1 as soon as DeleteBuffer is called on B1; see comments on #2178.

**Comment by greggman** [comment]
Will this be back ported to WebGL1? I notice the conformance tests for WebGL2 test this but not for OES_vertex_array_object in WebGL1

**Comment by RafaelCintron** [comment]
I agree with @kenrussell 's concerns as well as those raised by @zhenyao in the comments for #2178.  

As I understand it, @kenrussell is proposing we do the following:
1. WebGL implementations must reference count all resources.  Attaching a resource to another resource will increment the reference count.  Detaching a resource from another resource will decrement the reference count. 
2. Deleting a resource will mark it as “pending for deletion”.   
3. When a resource is pending for deletion, the underlying hardware resource is kept alive so long as the reference count is greater than zero.  Once the reference count reaches zero, the underlying hardware resource is destroyed.
4. A resource continues to function as a valid attachment so long as its reference count is greater than zero, even if it is marked as pending for deletion.
5. A resource that is pending for deletion cannot be added as a new attachment to another resource.
6. A resource will return false to isXXXX when it is marked as pending for deletion, regardless of the existing reference count.
7. When a resource is first marked as pending for deletion, it will detach itself from all resources that are currently bound to the pipeline regardless of the outstanding reference count. This includes: 
a. The active framebuffer
b. The active vertex array object
c. The active program
d. The active transform feedback buffer
e. The texture binding points
8. Once a resource is marked as pending for deletion, subsequent calls to delete it are ignored.  This includes the unbinding behavior described in 7.  For instance, if you delete a buffer, it will become detached for the current vertex array object.  However, if you later attach a different vertex array object that contains the buffer, deleting the buffer a second time will have no effect on the current vertex array object.  

The above makes sense to me.  Firefox, Edge and Chrome are currently not interoperable when it comes to 6 above.  Consider the following JavaScript code.

````Javascript
var rbo = gl.createRenderbuffer();
gl.bindRenderbuffer(gl.RENDERBUFFER, rbo);
var fbo = gl.createFramebuffer();
gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.RENDERBUFFER, rbo);
gl.bindFramebuffer(gl.FRAMEBUFFER, null);
gl.deleteRenderbuffer(rbo);
gl.isRenderbuffer(rbo);
````
Chrome returns false for isRenderbuffer while Edge and Chrome return true.

**Comment by jdashg** [comment]
I agree. Great run-down.
While 'IsFoo' behavior isn't made super clear by the specs, your clarification is what I vote for: IsFoo asks 'is this object a valid name', and so after Delete is called, the answer should be 'false'.

**Comment by RafaelCintron** [comment]
Apologies, I misspoke when I described the Chrome, Edge and Firefox behavior.  I've fixed it in the comment.

**Comment by RafaelCintron** [comment]
@jdashg you say in your comment "your clarification is what I vote for" but my clarification does not agree with having delete mean "is this object a valid name."  My clarification suggests that isFoo returns the pending object state, not whether the object has a corresponding hardware resource.  

If your vote is for "isFoo should reflect the state of the hardware resource", why do you feel that way?

**Comment by jdashg** [comment]
Sorry for not being clear. In GL an object 'has a valid name' iff it has been bound but not deleted.

Conceptually, I see this as CreateFoo() creates and holds a strong pointer to created object as accessed by a 'valid name', and DeleteFoo() releases that pointer and thus the 'name' becomes invalid, though the underlying resource may still be kept alive by a strong-ref from a background container.

**Comment by jdashg** [comment]
Resolving isRenderbuffer returns false for:
```
const rbo = gl.createRenderbuffer();
gl.bindRenderbuffer(gl.RENDERBUFFER, rbo);
const fbo = gl.createFramebuffer();
gl.bindFramebuffer(gl.FRAMEBUFFER, fbo);
gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.RENDERBUFFER, rbo);
gl.bindFramebuffer(gl.FRAMEBUFFER, null);
gl.deleteRenderbuffer(rbo);
gl.isRenderbuffer(rbo);
```
I believe everyone agrees here.
