### ISSUE TITLE
Suggestion for customizing mixing of rendering result and DOM elements behind of canvas

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/WebGL#2466]
I'm not familiar with suggesting some specification to standardization organizations. 
However, I would rise my idea to discuss how it can be realistic or needed to the other engineers.

> First of all, this is just a my opinion but I need to state. WebGL is just not for gamings. There should be needed some extensions for WebGL that is made for fitting Web development contexts.

# Suggestion

I think there should be some APIs or extensions to fetching texture data behind of canvas element.
When we use HTML elements with a canvas for WebGL, we can put elements behind of canvas. It can make fascinating design if the rendering result containing alpha data.
But we have no access to these elements as texture. That means linear mixing is the only way to use  elements behind of canvas.

### ~~1st suggestion~~(Having security issue)

This is suggestion of API. I guess this should be implemented as an extension like `WEBGL_texture_behind_canvas`(Maybe need better names). 

```js
var ext = gl.getExtension("WEBGL_texture_behind_canvas");
var texture = gl.createTexture();
ext.getTextureBehindCanvas(texture,x,y,width,height); // x, y, width and height should be number
``` 

An API `ext#getTextureBehindCanvas` fill the texture passed as argument with color data that the elements behind of canvas are rendered.

**But this suggestion is not good because of security problem. Attacker can obtain content of page as texture value. [Commented by @greggman ](https://github.com/KhronosGroup/WebGL/issues/2466#issuecomment-319261095)**

### 2nd suggestion

Although my 1st suggestion was already discussed and containing critical security problems, I think I have different background to suggest this problem. I just want more flexibility of mixing canvas and background elements.

This is my 2nd suggestion to overcome this. (But this seems tricky API as far as my feeling. There might be better way)

```js
var ext = gl.getExtension("WEBGL_canvas_mixing_shader");
ext.setMixingShader(shader,srcLocation,dstLocation);
ext.mixingUniform1i(uLocation,value);
....
``` 

`setMixingShader` have 3 arguments shader and uniformLocation. The shader must be `gl.FRAGMENT_SHADER`. `srcLocation` and `dstLocation` is `WebGLUniformLocation`. 
When browser need to mix canvas result and elements behind of canvas, browser will use passed shader for mixing. Browser will call draw with passing canvas texture to uniform variable specified as `srcLocation` and elements texture behind of canvas to uniform variable specified as `dstLocation`.

This shader is only used to create actual visible result by browser. Therefore, we can't read texture data behind of canvas.

There should be the other uniform variables to be passed. For that case, the extension interface should contain `uniformXX` methods also.

## Usecases

This extension can contain benefits.

* We can use canvas for effecting HTML elements being styled Web designers by CSS.
* This can be used for polyfills for `CSS backdrop-filter`
* We can make new usecase of WebGL for better Web design that can't be done by CSS.

I would like to discuss about this feature. How do you think?

**Comment by greggman** [comment]
This has been discussed in large detail in the past. The issue is one of security. Some ad wants to read someone's password, put a canvas on top, call your function, profit!

**Comment by kyasbal-1994** [comment]
@greggman Thanks for comment.  That is problem. I updated my suggestion to overcome the problem.  I'm afraid the 2nd suggestion is also discussed.

**Comment by greggman** [comment]
That was also discussed, unfortunately if you can write a shader you can make the shader take longer based on the colors passed do it. By timing the shader you can extract the data out of the textures.

**Comment by kyasbal-1994** [comment]
@greggman Hmm... You are right. Now I understand why we can't make such API safely.

If there were the other choice of the suggestion, I guess fixed pipeline is only way. However, such feature is not only for WebGL canvas. It should be region of CSS like backdrop-filter feature. I will close this issue since I could not find better suggestion at this point. I wish there were better and secured way to overcome this. 

Thanks a lot.
