### ISSUE TITLE
conformance/glsl/bugs/sampler-array-struct-function-arg.html in wrong directory?

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2514]
This test:
https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/glsl/bugs/sampler-array-struct-function-arg.html

calls:
wtu.create3DContext(canvas, undefined, 2);

but it's in the WebGL 1.0 test directory and marked --min-version 1.0.4.

Is it supposed to be in conformance2/glsl3/ and marked --min-version 2.0.1?

**Comment by zhenyao** [comment]
I don't think this is WebGL2 specific.  We can just get rid of the version in wtu.create3DContext() call.
