### ISSUE TITLE
clientWaitSync: int64 or uint64?

### ISSUE THREAD

**Issue by Ms2ger** [KhronosGroup/WebGL#2516]
clientWaitSync originally took a uint64 argument.

#1130 changed it to int64 and added a note to that effect.

#2110 changed it back, but didn't remove the note.

Please reconcile the IDL and the note.

**Comment by zhenyao** [comment]
Most of the note is still needed. We just need to remove clientWaitSync, only leaves waitSync there.

I'll clean up this.
