### ISSUE TITLE
Alpha value after clear in context-attributes-alpha-depth-stencil-antialias.html

### ISSUE THREAD

**Issue by grorg** [KhronosGroup/WebGL#2525]
I'm 99% sure I'm either misreading the test or misunderstanding the spec, but I'm confused about the alpha values returned in context-attributes-alpha-depth-stencil-antialias.html, specifically when alpha: false is a context creation attribute.

In the function testAlpha, when we're in the alpha = false pass we do two tests. The first is as the context is initialized:

- set alpha: false
- set clear color to (0, 0, 0, 0)
- clear
- read the pixels as RGBA

It expects gl.getParameter(gl.ALPHA_BITS) == 0 and the readPixels result to be (0, 0, 0, 255).

However, the next part of the test does the following:

- set clear color to (0.5, 0.5, 0.5, 0.5)
- clear
- read the pixels as RGBA

This expects the readPixels result to be (127, 127, 127, 127). 

I'm not sure how these are consistent. Either the alpha value is maintained in the buffer, or it isn't. The spec says that no alpha buffer is available, so the latter result should be (127, 127, 127, 255), right? Or if we're supposed to preserve the alpha, the first result should be (0, 0, 0, 0).

Another reason why I know I'm mistaken is that all browsers pass this, including WebKit. I've only hit it because I'm making some changes to the way I composite, which involves always having space for alpha but not using it. It gets initialised to 0, which fails the first part of the test above.

**Comment by zhenyao** [comment]
The second test is not testing the default fbo, but the user created fbo, which is RGBA.

**Comment by greggman** [comment]
Yes, the as @zhenyao points out, the second test is testing an FBO. This test is there to make sure that whatever the browser is doing to make sure alpha is not writable if the context was created with `alpha: false` only affects the canvas, not other user created framebuffers

**Comment by grorg** [comment]
Indeed! I knew I was missing something! Thanks.
