### ISSUE TITLE
ANGLE_instanced_arrays and WebGL2

### ISSUE THREAD

**Issue by fserb** [KhronosGroup/WebGL#2526]
When using instanced arrays, there's no way to start instancing from a particular point in the buffer. This limits the use of instanced buffer to a single draw call (otherwise, you must either repeat the same attributes or call `vertexAttribPointer` to re-arrange the buffer). OpenGL4 noticed this and implemented `glDrawElementsInstancedBaseInstance` that allows one to pass an offset to the base instance.

What are the odds we could have something like that on the WebGL spec (either the new function or a new `offset` arguments to `glDrawElementsInstanced` and `glDrawArraysInstanced`)?

@kenrussell @vonture @Kangz @c0d1f1ed ?? Please? <3

**Comment by zhenyao** [comment]
It's only part of core GL 4.2 and above, which means Mac won't have this (I also checked ARB_base_instance, it's not on my MacBook Pro with AMD).

On ES, it's not part of core. Extension OES_draw_elements_base_vertex isn't on the few mobile platforms I checked (Pixel, Nexus 5).

Therefore, it's not meaningful to expose this in WebGL.

**Comment by kainino0x** [comment]
OES_draw_elements_base_vertex seems to be only available on ARM, NVIDIA, and Intel OpenGL ES drivers:
http://opengles.gpuinfo.org/gles_listreports.php?extension=GL_OES_draw_elements_base_vertex

**Comment by kenrussell** [comment]
There's a little confusion here; there are multiple variants of the instanced draw calls:
  - Regular
  - BaseInstance
  - BaseVertex
  - BaseVertexBaseInstance

ES 3.1 core includes the BaseVertex calls.

We'd need to see if we could reasonably emulate the BaseInstance draw calls if they're not available, similarly to how we emulate VAOs. They could significantly improve applications' ability to batch draw calls.

There's another request for DrawElementsBaseVertex in #2434 . (CC @Groovounet).

**Comment by kenrussell** [comment]
More investigation: there is an OpenGL ES extension for the BaseInstance draw calls:
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_base_instance.txt

Unfortunately, according to gpuinfo.org, only 0.95% of OpenGL ES devices support it:
http://opengles.gpuinfo.org/gles_extensions.php

Essentially the only devices which do support it have NVIDIA GPUs:
http://opengles.gpuinfo.org/gles_listreports.php?extension=GL_EXT_base_instance

However, it seems feasible to emulate this extension in the browser, as long as the BaseVertex draw calls are supported -- this means OpenGL ES 3.1, or essentially all desktop GL devices. (Not exactly sure when it was folded into the core GL spec, but it was before 4.0.) When receiving a BaseInstance draw call, all of the vertex attributes enabled as arrays with non-zero divisors will be temporarily advanced by <code>baseinstance</code>, appropriately scaled, and set back to their original values after the draw call completes.

Even though this will be more expensive than having the driver do it, it should still be cheaper than making those vertex attribute changes from JavaScript.

@fserb: do you have any examples using the BaseInstance draw calls?

**Comment by jdashg** [comment]
Here also (like #2434) there's a chance that emulating this within webgl implementations may be faster than emulating it from webgl libraries, a la the multi_draw findings. (though clearly not on the same order of magnitude!)

However, if support is pretty sparse, I would rather just not implement this instead of emulating everywhere.

**Comment by jdashg** [comment]
Tracking in #2937.
