### ISSUE TITLE
Update WebIDL definition in WebGL 2.0 to use new mixin syntax

### ISSUE THREAD

**Issue by tobie** [KhronosGroup/WebGL#2539]
Hi all!

WebIDL recently introduced [dedicated syntax for mixins][0].

This syntax replaces the `[NoInterfaceObject]` extended attribute and `implements statement` which have been deprecated (except for a few [legacy uses cases][1] explicitely mentioned in the spec).

You can read more about it [here][2].

In most cases, the changes should be relatively straightforward. The now deprecated:

```webidl
interface Foo { };

[NoInterfaceObject]  // (Mostly) DEPRECATED
interface Bar { };
Foo implementes Bar; // DEPRECATED
```

should just be rewritten as:

```webidl
interface Foo { };

interface mixin Bar { };
Foo includes Bar;
```

Additonaly, a section on [when to use partials and mixins][3] has been added to the spec. It's short and might be worth a read.

It seems the following interface in WebGL 2.0 is impacted by this change:

- [ ] WebGL2RenderingContextBase

The suggested syntax change would be as follows:

```webidl
interface mixin WebGL2RenderingContextBase {
  /* ... */
};

interface WebGL2RenderingContext { };
WebGL2RenderingContext includes WebGLRenderingContextBase;
WebGL2RenderingContext includes WebGL2RenderingContextBase;
```

We're sorry for the inconvenience this causes, but our hope is that this ultimately makes things simpler and clearer for everybody.

As always, please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
[1]: https://heycam.github.io/webidl/#NoInterfaceObject
[2]: https://heycam.github.io/webidl/#idl-interface-mixins
[3]: https://heycam.github.io/webidl/#using-mixins-and-partials

***

*Tracked in: heycam/webidl#472* | *Original pull-request: heycam/webidl#433*

**Comment by bzbarsky** [comment]
@kenrussell the new IDL isn't valid because it has a mixin including another mixin, no?

**Comment by kenrussell** [comment]
@bzbarsky where do you see that?

WebGLRenderingContext and WebGL2RenderingContext are the two concrete interfaces, each of which includes multiple mixins. Those mixins don't include other ones.

If you see some problem please file a new issue referencing this one or, better, put up a pull request with a suggested fix. Thanks.

**Comment by bzbarsky** [comment]
@kenrussell I was looking at the changes made in <https://github.com/KhronosGroup/WebGL/pull/2566>, which is what closed this issue.

It looks like since then the problem has been fixed in https://github.com/KhronosGroup/WebGL/pull/2575
