### ISSUE TITLE
Using a browser extension to enhance the conformance tests?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2547]
Given a few recent compositing issues it got me wondering if it would be a good idea to provide a browser extension to run (optional?) conformance tests that can test compositing.

Browser extensions can take screenshots of pages. Browser extensions can be made accessible by the webpage. Therefore it should be possible to make a browser extension that allows a page to get a screenshot and therefore check that compositing is happening as expected (see [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=599285) as example).

Some thoughts:

* It's super dangerous to have an extension that allows a webpage to take a screenshot.

  That could be mitigated in several ways

     * Limit pages that can take screenshots to some user setable filter (like only `/^https:\/\/www\.khronos\.org\/registry\/webgl\/sdk\/tests\//` for example)

     * Limit it that the filter must pass for the main frames and iframes

     * Maybe (optionally) ask "can this domain take a screenshot" and only allow for the next N minutes if you really want to be safe/paranoid.

Of course browsers have their own testing infrastructure that is supposed to test this stuff. There's also things like selenium and other test environments that can do this stuff. My thinking was an extension is light weight, takes less effort to install, and it's nice to to be able to go to the online conformance tests and run the tests even if compositing tests are in their own folder or in some other way not part of the default tests.

From the POV of the tests themselves they'd just check for the existence of some api like `window.testScreeshotAPI` so any browser or test environment that wants to be able to run the tests just needs to expose that api. That could be handled several ways. Either it's up to the that browser team to do whatever or could do something like 

     <script src="/custom/test-screenshot-api.js"></script>

Which would silently fail if the file doesn't exist but allow any team to provide that script in their local test environment to call whatever needs to be called.

could make the api match the extension capture visible tab API [`chrome.tabs.captureVisibleTab`](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab) although personally I'd prefer to be able to choose a smaller rectangle to capture I suppose since that's the API I'd base the extension on it's what we're stuck with anyway. Though maybe given the fact that the tests run in iframes the test harness would need to do some work to give the correct portion of the actually frame the test is in and therefore a different API is better or maybe the wrapper needs to trim the tab result to the page in question.

Thoughts?

**Comment by greggman** [comment]
Well, haha, I actually [wrote the extension](https://github.com/greggman/webgl-conformance-test-helper-extension) and made a test with it and it failed to detect the error. It takes a screenshot but for whatever reason the screenshot comes out the correct colors even though what chrome is displaying is not the correct colors. That's a pretty messed up bug 🤣  I guess the screenshot code is taking a different path to generate the result. It's not actually taking a "screenshot".

<img width="868" alt="webgl-conformane-test-extension-laugh" src="https://user-images.githubusercontent.com/234804/32837282-3e3906ec-ca50-11e7-8603-096464c9a502.png">

**Comment by jdashg** [comment]
Yeah, our codepath is similarly different. In the short term, it's easier for us to make an integration harness that would easily let us hook the pixeltests/reftests up to our respective test runners.

I believe web platform tests is working on (maybe has?) a harness that does this.

Gecko has fairly exhaustive pixel tests for context creation attributes and colors, though as you can tell, we've disabled them for now on Android. (working on this!)
https://github.com/mozilla/gecko/blob/central/dom/canvas/test/reftest/reftest.list

**Comment by kenrussell** [comment]
@gyagp recently contributed a WebDriver based test harness for the WebGL conformance suite in https://github.com/KhronosGroup/WebGL/tree/master/tools . I tested it locally with Chrome on Mac and Chromedriver and it worked. Theoretically it should work with all browsers since they all have WebDriver support.

The intent here was to allow reftests to be added which would be implemented using WebDriver's screenshot functionality. These could verify operations like compositing of WebGL canvases. I'm hoping that WebDriver's screenshots will be higher fidelity than those taken by Chrome's extensions.

@greggman do you have a little time to look into that harness and see whether it would produce good results for your test case? Ideally we would like to start writing WebGL reftests ASAP (#2527).

**Comment by jdashg** [comment]
I think this is WebDriver now.
