### ISSUE TITLE
Consider a "Strict IEEE Float" extension

### ISSUE THREAD

**Issue by kainino0x** [KhronosGroup/WebGL#2554]
The idea of a WebGL extension that exposes something like:
```
#pragma ieee_strict_float
```
was floated by @Oletus on this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=789980#c3
in which the reporter requested the ability to do IEEE floating point math in WebGL (i.e. with IEEE Inf and NaN semantics).

Related issue, in which const and non-const float evaluation differs in those cases:
https://bugs.chromium.org/p/chromium/issues/detail?id=772657#c11

**Comment by jdashg** [comment]
Let's not pursue this for now. No version of ESSL requires IEEE float operations, so it's hard to support.
