### ISSUE TITLE
Feature request: ClippingDistance / GL_EXT_clip_cull_distance

### ISSUE THREAD

**Issue by andrevenancio** [KhronosGroup/WebGL#2556]
Hi all.
Following @kenrussell suggestion on [this](https://groups.google.com/forum/#!topic/webgl-dev-list/0vUJ9r6g_bg) post at the WebGL dev list, I'm kindly requesting a feature request which lacks in WebGL 1.0 and WebGL 2.0 spec.

The feature is the [gl_ClipDistance](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_ClipDistance.xhtml) which will allow us to handle clipping at a vertex shader level instead of discarding pixels on the fragment shader.

This should be a performance improvement as we should have less calls to the fragment shader (?), and should also help on the shader optimisations as we'll get rid of the `discard`.

**Comment by jdashg** [comment]
This was moved to Draft in #2931.

**Comment by lexaknyazev** [comment]
As with other draft extensions, this is work-in-progress. Unfortunately, there are platform-specific issues that have to be resolved before this feature could be exposed to web browsers.

**Comment by lexaknyazev** [comment]
The [WEBGL_clip_cull_distance](https://registry.khronos.org/webgl/extensions/WEBGL_clip_cull_distance/) extension is available behind a flag in Chromium Canary and WebKit Nightly builds.
- Chromium: go to `about://flags/#enable-webgl-draft-extensions`, select Enabled, restart the browser
- WebKit: Preferences → Advanced → Show Develop Menu; then Develop → Experimental Features → WebGL Draft Extensions

**Comment by RenaudRohlinger** [comment]
Since `WEBGL_clip_cull_distance` seems to be now supported on web browsers such as [Safari (16.4 release)](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes) could we hope to see this extension getting promoted to `Approved WebGL Extensions` and finally use it.

Any update on the subject @kenrussell?

Being able to handle clipping at a vertex shader level would be game-changing for the projects in my company. 🙇

**Comment by kenrussell** [comment]
@RenaudRohlinger the WebGL WG approved the extension yesterday! It'll be present in Chrome 119 per https://chromium-review.googlesource.com/c/chromium/src/+/4850622 and https://chromiumdash.appspot.com/commits?commit=1c72951e6a0444dae8820d5f91b5e7256f1cbffb . Will be in Safari Technology Preview soon; no schedule for Firefox yet.
