### ISSUE TITLE
ProvokingVertex missing from API or Diffs

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2567]
[OpenGL ES 3.0 section 2.17](https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf) mentions a function `ProvokingVertex`

> ## 2.17 Flatshading
>
> Flatshading a vertex shader output means to assign all vertices of the primitive the
same value for that output.
>
> The output values assigned are those of the provoking vertex of the primitive.
> The provoking vertex is controlled with the command
>
>       void ProvokingVertex( enum provokeMode );
>
> provokeMode must be either `FIRST_VERTEX_CONVENTION` or `LAST_VERTEX_CONVENTION`,
> and controls selection of the vertex whose values are assigned to
> flatshaded colors and varying outputs, as shown in table 2.12
>
> ...

This seems missing from WebGL 2.0 and it's does not seem to be mentioned as a difference.

Is it just missing from the spec and implementations or does the spec need to be updated to reflect that it's not available in WebGL2 or am I just failing to see it?

**Comment by greggman** [comment]
Even more strange the [OpenGL ES 3.0 headers files](https://www.khronos.org/registry/OpenGL/api/GLES3/gl3.h) are missing `glProvokingVertex` and the enums mentioned above. The enums are listed in [the extension header](https://www.khronos.org/registry/OpenGL/api/GLES2/gl2ext.h) but have the suffix `_OES` and there is no mention of the function there either.

**Comment by greggman** [comment]
Okay, so checking the OpenGL ES 3.1 and 3.2 the function doesn't exist in those specs. Only 3.0. 

In those specs there's a table (12.2) which just list per primitive which vertex the non-interpolated values are from.

For ES 3.1 the values are

>     point                  i
>     independent line       2i
>     line loop              i + 1, if i < n 1, if i = n
>     line strip             i + 1
>     independent triangle   3i
>     triangle strip         i + 2
>     triangle fan           i + 2

For ES 3.3 the values are the same but there are more primitive types.

**Comment by kainino0x** [comment]
It sounds like it was a spec bug that the ProvokingVertex() call was included in the 3.0 prose spec. It's weird that they never fixed it, but 3.0 is quite old and not getting maintained.

**Comment by kainino0x** [comment]
Even the table in the 3.0 spec does not seem to agree with the prose: the table only specifies one mode, not both FIRST and LAST as I think the text implies.

**Comment by kenrussell** [comment]
It seems clear this was an oversight in the ES 3.0 spec. The WebGL 2.0 spec didn't pick up this API since it didn't exist in the ES 3.0 headers. I don't think it's worth pressing the ES working group for a revision to delete this text.
