### ISSUE TITLE
Accessing WebGL types in a worker?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2571]
I'm probably just missing this somewhere but, I have some semi-generic WebGL code that needs to check if an object is `WebGLTexture` or a `WebGLRenderbuffer`. For the last several years I've had code like this

      isTexture = object instanceOf WebGLTexture;

But now I'm trying to run this code in a worker and AFAICT `WebGLTexture` does not exist inside a worker even though WebGL itself is running via `OffscreenCanvas`.

* Is this a known issue? 
* Will the WebGL types be exposed inside a worker?
* Are they exposed somewhere not the global object? 

As it is a few workarounds which seem unclean (some wishy washy feeling I know but ...)

1.  call `gl.isTexture` which requires a `WebGLTexture` but throws if it's not. Seems pretty heavy to generate an exception just to check this stuff.  In other words

         function isTexture(gl, obj) {
           let result = false;
           try {
             result = gl.isTexture(obj);
           } catch (e) {
           }
           return result;
         }

2. call `representative = gl.createTexture()` somewhere then use `objectInQuestion instanceOf representative.constructor`. ugh but it works and at least it's fast and doesn't generate garbage every check as 1 above does but it does generate a bogus object.

3. ???

**Comment by kainino0x** [comment]
This sounds like an oversight to me, but I haven't worked on OffscreenCanvas myself. In Chrome, it looks like it's just a matter of adding `Exposed(Worker ExperimentalCanvasFeatures)` to `WebGLTexture` and the rest of the WebGL interface objects (we [already have it](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webgl/WebGLRenderingContext.idl?l=30&rcl=1378ec8412b3a75df750acc22cdfe0a9adc211b5) for WebGL(2)RenderingContext).

cc @junov

**Comment by foolip** [comment]
This will have to be fixed in the specs as well. As of https://github.com/heycam/webidl/pull/423 `[Exposed]` is mandatory, relevant change deep in https://heycam.github.io/webidl/#idl-interfaces: "Non-callback interfaces which are not annotated with a [NoInterfaceObject] extended attribute, and callback interfaces which declare constants must be annotated with an [Exposed] extended attribute."

**Comment by kenrussell** [comment]
Chromium's implementation has been fixed to expose these interfaces on workers as of https://chromium-review.googlesource.com/1142292 .
