### ISSUE TITLE
Disposing a WebGL rendering context

### ISSUE THREAD

**Issue by annevk** [KhronosGroup/WebGL#2591]
In https://github.com/whatwg/html/issues/2290 it was suggested that it would be nice to be able to dispose a WebGL rendering context in order to free up resources.

**Comment by kenrussell** [comment]
See @jdashg 's and my comments on the other bug regarding both the WEBGL_lose_context extension and the possibility of close() / dispose() across many web object types.

**Comment by antarikshray** [comment]
I am using an asynchronous function and calling the webgl function to render it. But after running 16 times it stops because too many instances are opened. I need a method so that it continues rotating an object.

**Comment by jdashg** [comment]
Consider either reusing the context or calling loseContext on contexts you
don't need.

**Comment by jdashg** [comment]
Here's a polyfill:
```
WebGLRenderingContext.prototype.close = function() {
  const ext = this.getExtension('WEBGL_lose_context');
  ext.loseContext();
};
WebGL2RenderingContext.prototype.close = WebGLRenderingContext.prototype.close;
```
