### ISSUE TITLE
Invalid WebIDL for extensions

### ISSUE THREAD

**Issue by Diggsey** [KhronosGroup/WebGL#2596]
The IDL for some of the extensions is invalid.

For example, here: https://github.com/KhronosGroup/WebGL/blob/master/extensions/EXT_disjoint_timer_query/extension.xml#L68

The parameter type should be `GLenum`, not `enum`.

Similarly, here:
https://github.com/KhronosGroup/WebGL/blob/master/extensions/WEBGL_shared_resources/extension.xml#L343

There are missing semicolons.

And here:
https://github.com/KhronosGroup/WebGL/blob/master/extensions/WEBGL_shared_resources/extension.xml#L333

The callback has the wrong name.

**Comment by kainino0x** [comment]
The semicolons and callbacks still need fixing; reopening
