### ISSUE TITLE
Rendering to 3D texture layer via framebuffer

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2618]
According to [this SO question](https://stackoverflow.com/questions/49474040/layered-rendering-to-3d-texture-using-glframebuffertexturelayer/) rendering to a 3D texture layer via a framebuffer is not working on certain drivers. In particular a GTX 1070 on Windows?

Here's a small test

https://jsfiddle.net/greggman/k2kt58wd/

Can anyone confirm?

**Comment by novalain** [comment]
I can confirm this on Windows 10 Home (Version 1709, Build 16299.309) in Chrome (65.0.3325.181) on GTX 1070

**Comment by greggman** [comment]
Confirmed on Windows 10 Pro 64 ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)

**Comment by zhenyao** [comment]
@Oletus @null77 @vonture

**Comment by jdashg** [comment]
Broken in Firefox with ANGLE, works without ANGLE on Windows. Can we add a conformance test for this?

**Comment by greggman** [comment]
So I started writing a test but I'm running into issues

* In Chrome 67 on Windows the test is flaky. It doesn't appear to be flaky in firefox. Note that I'm just rendering to a 2x2x2 texture and if I change it to a 4x4x4 texture the flakiness disappears.
* It passes in Firefox yet it's doing the same thing as the jsfiddle linked above!?!?

I'm not sure how I should proceed.  Maybe I should check this in and the JSFiddle test as well?

**Comment by kenrussell** [comment]
Your new conformance test is much more complete than the JSFiddle. If you put the verbatim JSFiddle into a conformance test, does it reproduce the failure seen on the JSFiddle site?

If not then I wonder whether it might be caused by context switching during the log() calls you're making in the Fiddle, which cause text to be added into another full HTML document in an iframe on the page.

Either way we should probably add your new conformance test as is, even if it only catches errors intermittently in Chrome.

**Comment by greggman** [comment]
I added the fiddle version, it does seem to reliably repo the issue

**Comment by kkinnunen** [comment]
I tried with default settings FF Nightly and Chrome Canary, NV Quadro and Intel HD.
The fiddle reports no GL error but few failures with the few color channels, but I'm unsure if that's a test error or actual exhibited failure.
`
actual: 0 expected: 0 no gl error
actual: 0 expected: 0 
actual: 0 expected: 255 
actual: 0 expected: 0 
actual: 0 expected: 255 
`

**Comment by jdashg** [comment]
I believe this is related to #2568, as it, too, works on Windows+native-gl, but fails on Windows+ANGLE. It could always be different, but it smells related.

**Comment by jdashg** [comment]
Thanks again!
I also filed an ANGLE bug: https://bugs.chromium.org/p/angleproject/issues/detail?id=4417
