### ISSUE TITLE
Error: WebGL warning: drawArrays: Vertex fetch requires vertex ...

### ISSUE THREAD

**Issue by H91011** [KhronosGroup/WebGL#2622]
Hi, 
I am trying to draw triangles but I get this error: 

`Error: WebGL warning: drawArrays: Vertex fetch requires vertex #2, but attribs only supply 1.`

and when I change `gl.TRIANGLES` to `gl.POINTS` it gives same error again only draw one point I can not draw multiple point  ot a triangle

**Comment by zhenyao** [comment]
Please ask such questions at webgl-dev-list@googlegroups.com
