### ISSUE TITLE
Expose KHR_parallel_shader_compile as a WebGL extension

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2638]
The extension KHR_parallel_shader_compile provides a minimal API which allows a context to opt-in to new, parallelized shader compilation and program linking semantics.

https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_parallel_shader_compile.txt

This should be exposed as a WebGL extension to allow applications to opt-in to background shader compilation. This would allow applications to compile larger and more complex shaders without blocking the browser's UI.

**Comment by Kuranes** [comment]
As both compileShader and linkProgram don't have any return, could they return a promise ?
(resolve on completion, reject on compile/link error)

That would allow user choice on whether to poll or push.

**Comment by kenrussell** [comment]
The WebGL API usually tracks the ES API unmodified unless there's a good reason to deviate, but the working group will consider it.

**Comment by jdashg** [comment]
This is handled by other issues and PRs.
