### ISSUE TITLE
Doc: WebGLActiveInfo Properties Incorrect in Quick Reference

### ISSUE THREAD

**Issue by niedzielski** [KhronosGroup/WebGL#2664]
The [WebGL v1.0 quick reference](https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf) says WebGLActiveInfo has size, type, name, and **location** properties. However, the [WebGL v1.0 spec](https://www.khronos.org/registry/webgl/specs/1.0/#5.11) says that only size, type, and name properties exist. Please remove the incorrect location property.

Sorry, if this isn't the right place for this report. [The wiki](https://www.khronos.org/webgl/wiki/) links [bug reports to Bugzilla](https://www.khronos.org/bugzilla/enter_bug.cgi?product=WebGL) but that says reports are disabled (even with an account).

**Comment by kenrussell** [comment]
Thanks for the report. Will tell the people who maintain the reference card.

**Comment by kenrussell** [comment]
The reference card has been updated:
https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf

Thanks again for the report!
