### ISSUE TITLE
Inconsistent behavior between browsers with EXT_sRGB in WebGL1

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2666]
According to the [EXT_sRGB spec](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_sRGB.txt)

> ## Modify Section 3.7.11: Mipmap Generation
>
>    Add the following sentence to the end of this section:
>    
>    If the format of a texture is sRGB, he error INVALID_OPERATION is 
>    generated.
        
note the spec doesn't say what's supposed to happen to sRGB_ALPHA textures. 

Firefox generates INVALID_OPERATION on both formats. Chrome does not generate an error for either format.

http://jsfiddle.net/greggman/54vzafxk/

**Comment by kenrussell** [comment]
This is a bug in Chrome: http://crbug.com/769989 . Since there's already a conformance test we'll try to fix it soon.

**Comment by kenrussell** [comment]
This has been fixed per http://crbug.com/769989 .
