### ISSUE TITLE
Add a license on the spec document

### ISSUE THREAD

**Issue by saschanaz** [KhronosGroup/WebGL#2668]
We in [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) wants to collect WebGL 1.0/2.0 IDLs to generate TypeScript library file, but it seems the spec does not mention anything about the license. Can you add one so that the TypeScript team can use the spec?

See also https://github.com/Microsoft/TSJS-lib-generator/pull/533#discussion_r202093015

**Comment by hherrada** [comment]
I'm also looking for info on the license. Thanks!

**Comment by kenrussell** [comment]
The same MIT license that is used on the other software files in this repository has now been applied to the generated IDL files. Please open a new issue if there is any concern with this license. Thanks.
