### ISSUE TITLE
 feedback loops with framebuffers where NONE is specified by drawBuffers

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2670]
This part of the spec seems like it might need revisiting?

The issue is if you create a framebuffer, attach 2 or more textures as color attachments, then call `drawBuffers` with either `[gl.NONE, gl.COLOR_ATTACHMENT0 + 1]` or `[gl.COLOR_ATTACHMENT0, gl.NONE]` while reading one of the textures whether or not you should get `INVALID_OPERATION` for a feedback loop as it mentions in [section 6.25 of the spec](https://www.khronos.org/registry/webgl/specs/1.0/#6.25)

There's a test for WebGL1 [here](https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/webgl-draw-buffers-feedback-loop.html) and one for WebGL2 [here](https://www.khronos.org/registry/webgl/sdk/tests/conformance2/rendering/rendering-sampling-feedback-loop.html)

Which Firefox passes and Chrome fails and a 2yr old bug filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=660844)

But it's not clear these tests are correct.

Looking at both the OpenGL ES 2.0 spec and the OpenGL ES 3.0 spec neither say anything about `drawBuffers`. They only say if the texture is attached to the framebuffer and is read in the shader then the results are undefined. They don't stay anything about whether or not setting `drawBuffers` to `NONE` prevents a feedback loop.

This came up from [this SO answer](https://stackoverflow.com/questions/50014874/opengl-and-webgl-sampling-from-a-texture-attached-to-current-framebuffer/51385346#) which links to the [Khronos wiki](https://www.khronos.org/opengl/wiki/Memory_Model#Framebuffer_objects) which suggests that that is still considered a feedback loop and therefore the test is wrong and both Firefox and Chrome are wrong. All 3 cases should generate `INVALID_OPERATION`?

**Comment by jdashg** [comment]
That makes sense but we should stop calling it feedback loops, because
that's not the issue here. In this case it's effectively a simultaneous
usage issue, like our transform feedback woes. I'll reread the spec on this
because I remember being happy with our implementation. (It wouldn't be the
first time the wiki is wrong)

**Comment by jdashg** [comment]
Yep, looks like the deceptive name fooled us. All three subtests in should fail, as drawBuffers has no interaction with "feedback loops".

**Comment by jdashg** [comment]
This is solved by #2727.
