### ISSUE TITLE
Spec says BufferSource but tests also try arrays of numerical strings

### ISSUE THREAD

**Issue by nox** [KhronosGroup/WebGL#2677]
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.5

```webidl
void bufferData(GLenum target, [AllowShared] BufferSource? data, GLenum usage);
```

https://heycam.github.io/webidl/#BufferSource

```webidl
typedef (ArrayBufferView or ArrayBuffer) BufferSource;
```

https://github.com/KhronosGroup/WebGL/blob/master/conformance-suites/1.0.3/conformance/misc/type-conversion-test.html#L71
https://github.com/KhronosGroup/WebGL/blob/master/conformance-suites/1.0.3/conformance/misc/type-conversion-test.html#L90

This calls (AFAICT):

```js
context.bufferData(context.ARRAY_BUFFER, ["2"], context.STATIC_DRAW);
```

**Comment by kainino0x** [comment]
I believe this test is hitting not the BufferSource overload of bufferData, but this one:
```webidl
void bufferData(GLenum target, GLsizeiptr size, GLenum usage)
```
The test is testing that `["2"]` correctly casts to `2`, etc.:
```js
((["2"]) | 0)  // evaluates to 2
```

**Comment by kainino0x** [comment]
(also hi, I recognize your icon/name from lurking in Rust forums :slightly_smiling_face:)

**Comment by nox** [comment]
I'm so glad I was so completely wrong about this because what my issue was suggesting was terrifying. I'll look into the overload resolution in our codegen in Servo then.

(Hi, fellow WebGL implementor with the sound "nox" in their name and an anime avatar!)
