### ISSUE TITLE
Expose KHR_parallel_shader_compile to WebGL

### ISSUE THREAD

**Issue by jchen10** [KhronosGroup/WebGL#2690]
More information at https://bugs.chromium.org/p/chromium/issues/detail?id=849576.

**Comment by greggman** [comment]
Based on other async stuff in WebGL does this need to have extra restrictions?

For example `getQueryParameter` says 

> In order to ensure consistent behavior across platforms, queries' results must only be made available when the user agent's event loop is not executing a task. In other words:

> * A query's result must not be made available until control has returned to the user agent's main loop.
> * Repeatedly fetching a query's QUERY_RESULT_AVAILABLE parameter in a loop, without returning control to the user agent, must always return the same value.

Similarly I wonder if this spec should change to do the same thing.  Should it require not working in a spin loop?

Also, why do I care how many threads at all? It seems to me there's no reason for `MaxShaderCompilerThreadsKHR` nor `MAX_SHADER_COMPILER_THREADS_KHR`. 

All that's needed is being able to pass `COMPLETION_STATUS_KHR` to `getShaderParameter` and `getProgramParameter`.  An implementation that doesn't support parallel compilation will just always return `true` and the next call dealing with info about that shader/program will block (as it does now). Why so I have to opt in by calling `MaxShaderCompilerThreadsKHR`? Basically `COMPLETION_STATUS_KHR` is just asking *"when I check for success or I query locations will my call block, yes or no?"* so what's the point in specifying or querying a number of threads?

Also querying a number of threads is yet more data leak. Not that it matters much at this point for WebGL

**Comment by jchen10** [comment]
@greggman Thank you for the comment.
For the extra async restriction, I am not quite sure about the across platforms consistency.  @kenrussell Maybe you can comment on this.

For your thread number concern, my thoughts are:
    We should keep consistent with the original spec if no strong incompatibility with Web.
    Querying thread number only returns what you have set, or 0xFFFFFFFF.  There is no risk of data leak.
    Setting thread number can offer a fine gained control on CPU resource to be engaged in compilation and linking.

**Comment by kenrussell** [comment]
@greggman We'll consider amending the spec once we have a prototype working and see how well it works in practice. From the standpoints of security and interoperability between browsers and with the rest of the web platform, I think it's OK to let these programs compile and link as quickly as possible.

@jchen10 in Chrome I had been planning to enforce an implementation-specific maximum of 1 background thread per WebGL context. More than that is probably excessive.

**Comment by greggman** [comment]
> I think it's OK to let these programs compile and link as quickly as possible.

What does that mean? Spin loops are ok? I thought part of the point of this is that DirectX can take a really long time (10-20-30 seconds or more) to compile a complex shader which crashes the browser.

Also still don't understand how a webpage is supposed to know what to set `MaxShaderCompilerThreadsKHR` threads to.  That seems like something the browser should handle, not the dev.

Being able to compile shaders async is great but this API is a bad fit for the browser.

**Comment by jchen10** [comment]
@kenrussell  If you still want to enforce an implementation-specific maximum of 1 background thread per WebGL context,  I think we should keep MaxShaderCompilerThreadsKHR. Otherwise we would not best benefit from multi-thread to accelerate compilation/linking tasks.
BTW, probably we need at least 2 background threads by default, one for vertex shader, and the other for fragment shader.

**Comment by litherum** [comment]
See also: 
https://github.com/KhronosGroup/WebGL/issues/2772

**Comment by jdashg** [comment]
Promoted to draft in #2711. I think we can close this.
