### ISSUE TITLE
Revise WEBGL_blend_equation_advanced proposal

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2704]
Per discussion in the WebGL working group, the WEBGL_blend_equation_advanced extension proposal should be revised. The working group's opinion is that it should require the coherent version of the extension and not expose the non-coherent behavior. This should provide the majority of the performance benefits without exposing more undefined behavior to the developer – and without exposing two extensions, which would otherwise likely be needed.

**Comment by AshleyScirra** [comment]
Should the extension be renamed to WEBGL_blend_equation_advanced_coherent as well?

**Comment by kenrussell** [comment]
Yes, it should be.

**Comment by AshleyScirra** [comment]
This should be all done now: WEBGL_blend_equation_advanced_coherent has been proposed and WEBGL_blend_equation_advanced has been deleted.

**Comment by kenrussell** [comment]
Thanks @AshleyScirra . Verified the coherent extension is showing up in the extension registry https://www.khronos.org/registry/webgl/extensions/ .
