### ISSUE TITLE
ASTC tests expect glTexStorage2D to produce a black image

### ISSUE THREAD

**Issue by imirkin** [KhronosGroup/WebGL#2725]
As per the spec at https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.6

> The image contents are set as if a buffer of sufficient size initialized to 0 would be passed to each texImage2D call in the pseudocode in The OpenGL ES 3.0 specification section 3.8.4.

However the test [webgl-compressed-texture-astc.html](https://www.khronos.org/registry/webgl/sdk/tests/conformance/extensions/webgl-compressed-texture-astc.html?webglVersion=2&quiet=0) has

```
gl.texStorage2D(gl.TEXTURE_2D, 1, format, width, height);
...
var clearColor = [0, 0, 0, 0];
wtu.checkCanvas(gl, clearColor, "texture should be initialized to black");
```

Should the tests be adjusted to expect the error color value (1,0,1,1), or just remove the expectation entirely? Or am I misunderstanding something?

**Comment by jdashg** [comment]
Yeah, that should test whatever all-zeros decodes into.

**Comment by imirkin** [comment]
It occurs to me that perhaps there's a bit of subtlety here -- the spec is in terms of texImage2D, but that would of course be invalid for a compressed format. (Unless WebGL requires online compression? I didn't check carefully, but since it's based on GL ES, that seems unlikely.)

Perhaps we can assume that the text was meant to say compressedTexImage2D for compressed formats?

Either way, what's the appropriate thing to do? Send a pull request in github?

**Comment by jdashg** [comment]
PR please! You're correct, in WebGL compressed data can only be uploaded
with compressedTex functions.
