### ISSUE TITLE
Flaw by scr-dump of GPU mem

### ISSUE THREAD

**Issue by FutureFireplace** [KhronosGroup/WebGL#2734]
Hello - can anyone see into this please? 
https://www.contextis.com/en/blog/webgl-more-webgl-security-flaws

/br

**Comment by jdashg** [comment]
We saw into it long ago! Nothing to worry about there these days.

**Comment by kainino0x** [comment]
AFAICT, this article is from 2011 and covers topics that have been long addressed.

**Comment by FutureFireplace** [comment]
Thanks (I work in a big corp where security is paramount)
