### ISSUE TITLE
readPixels issue 

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2747]
There appears to be bugs in both firefox and chrome with readPixels but the spec is sadly ambiguous here. According to the spec, only 2 formats are allowed for readPixels

OpenGL ES 3.0 section 4.3.2

>  Only two combinations of format and type are accepted in most cases. The
first varies depending on the format of the currently bound rendering surface. For normalized fixed-point rendering surfaces, the combination format RGBA and type
UNSIGNED_BYTE is accepted. For signed integer rendering surfaces, the combination
format RGBA_INTEGER and type INT is accepted. For unsigned integer rendering
surfaces, the combination format RGBA_INTEGER and type UNSIGNED_INT
is accepted.
>
> The second is an implementation-chosen format from among those defined
in table 3.2, excluding formats DEPTH_COMPONENT and DEPTH_STENCIL. The
values of format and type for this format may be determined by calling GetIntegerv
with the symbolic constants IMPLEMENTATION_COLOR_READ_FORMAT
and IMPLEMENTATION_COLOR_READ_TYPE, respectively.

So if read that correctly the implementation is not allowed to just pick any format. It must pick a format from table 3.2 which contradictory to the words " implementation-chosen format". Table 3.2 does not leave any choices. It's very explicit.

So back to the 2 browsers. Here's a test that makes an R32F texture and attaches it to a framebuffer. 

http://jsfiddle.net/greggman/6gzsnpcx/

According to table 3.2 that should be format = RED, type = FLOAT

On a 2018 Macbook Air

Firefox reports RGBA / FLOAT
Chrome reports RED / UNSIGNED_BYTE

Further Chrome allows reading with RGBA / FLOAT but should only allow RED / FLOAT (or since it reported RED / UNSIGNED_BYTE it should only allow RED / UNSIGNED_BYTE)

**Comment by jdashg** [comment]
To my understanding, from float color attachments you can always read
RGBA/FLOAT, at least. (Implementation formats don't replace the default)
I'll take a look at the 3.2 spec on Monday.

**Comment by zhenyao** [comment]
Chrome reporting UNSIGNED_BYTE seems like a typo in the code:

https://cs.chromium.org/chromium/src/gpu/command_buffer/common/gles2_cmd_utils.cc?rcl=ce49e44bb7134b097cd8e1d1707336df841026dd&l=1193

**Comment by MarkCallow** [comment]
> On Dec 1, 2018, at 13:10, Jeff Gilbert <notifications@github.com> wrote:
> 
> To my understanding, from float color attachments you can always read
> RGBA/FLOAT, at least. (Implementation formats don't replace the default)
> I'll take a look at the 3.2 spec on Monday.

Yes, the color buffer float extensions modify section 4.3.2 to require the combination RGBA & FLOAT for floating-pint rendering surfaces. That language has been incorporated in OES 3.2 in what is now section 16.1.

Regards

    -Mark

**Comment by greggman** [comment]
Okay so I updated the jsfiddle to expect RGBA/FLOAT to work

In which case

Chrome:

Reports RED/UNSIGNED_BYTE  should report RED/FLOAT?
Fails reading RED/FLOAT

Firefox:

Reports RGBA/FLOAT should report RED/FLOAT?
Fails reading RED/FLOAT

**Comment by greggman** [comment]
Though the ES3.0 spec has the same issue where it says contradictory things

> The second is an implementation-chosen format from among those defined
in table 8.2. 

There is nothing implementation defined in 8.2. It's all explicit for each internal format

**Comment by greggman** [comment]
So I'm throughly confused. The spec calls out one format as special

> Additionally, when the internal format of the rendering surface is RGB10_A2,
a third combination of format RGBA and type UNSIGNED_INT_2_10_10_10_REV
is accepted.

But that's already in table 3.2

<img width="639" alt="screen shot 2018-12-02 at 10 55 53" src="https://user-images.githubusercontent.com/234804/49334796-d0121600-f621-11e8-92fb-e5125bf25757.png">
<img width="636" alt="screen shot 2018-12-02 at 10 56 07" src="https://user-images.githubusercontent.com/234804/49334797-d4d6ca00-f621-11e8-9042-64d988548e3f.png">

In other words the spec says

readPixel accepts

1.  these format/types

    * for fixed point formats like R8 or RGB565 - `RGBA/UNSIGNED_BYTE`
    * for int formats like R8I - `RGBA/INT`
    * for unsigned formats like R8UI - `RGBA/UNSIGNED_INT`
    * for float formats like `R816F` - `RGBA/FLOAT`

2. "an implementation-chosen format from among those defined in table 3.2"

    That seems to suggest for most formats there is only one additional choice an implementation is allowed to return.

3.  for `RGB10_A2` only, it must also return `UNSIGNED_INT_2_10_10_10_REV`

**3** makes zero sense since it seems already covered by **2** which seems to suggest **2** is trying to say something other than the way I'm interpreting it.

I'm interpreting **2** as for a given internal format the implementation must choose one of corresponding format/types. But for `RGB10_A2` the only specified format/type is `RGBA/UNSIGNED_INT_2_10_10_10_REV` so why the need for **3**?

It's possible **2** means any format/type combination listed in 3.2 is valid for any internal format but if that's the case it would mean for example an implementation could decide for `RGB8` to return `RED_INTEGER/INT` if it wanted. It's hard to believe that's the intent so I'm assuming my interpretation is correct. If so I'm lost as what the point of **3** is.

@MarkCallow ?

**Comment by zhenyao** [comment]
Trying to recollect my memory from when implementing this in Chrome, my understanding is we do have multiple choices at selecting the implementation specific pair of format/type. For example, if read buffer is R32F, RED/FLOAT, RG/FLOAT, RGB/FLOAT, RGBA/FLOAT are all possible options, as well as four with HALF_FLOAT.

Integer formats and fixed/float point buffers won't work, and vice versa. However, I think float and fixed points can work with each other. Therefore, for R32B buffers, RED/UNSIGNED_BYTE, RG/UNSIGNED_BYTE, RGB/UNSIGNED_BYTE, RGBA/UNSIGNED_BYTE should also work.

Therefore, Chrome code I quoted earlier is actually intentional rather than a mistake. UNSIGNED_BYTE is chosen for float buffers to avoid conflicting with the basic pair RGBA/FLOAT.

My understanding came from reading the OpenGL 4 core profile spec's ReadPixel behavior, as I believe ES's behavior is simply a more limited version of the GL's behavior.

**Comment by MarkCallow** [comment]
I believe the intent is that implementations must accept the format & type combinations you have listed in 1 & 3 and must accept the symbolic constants  IMPLEMENTATION_COLOR_READ_FORMAT
and IMPLEMENTATION_COLOR_READ_TYPE. I believe 2 means that the implementation can choose any format/type combo from 3.2 so for example an implementation could chose RGB/UNSIGNED_SHORT_5_6_5 for fixed-point buffers. 

Historically this comes from OpenGL ES 1 where we wanted to avoid format and type conversions. So IMPLEMENTATION*TYPE/FORMAT would correspond to the actual color buffer format the implementation was using. So we would expect implementations to make sensible choices from 3.2.

**Comment by greggman** [comment]
Let's put it another way. How do you write a test for readPixels?

It's clear from **1** above that it should check

* for fixed point formats like R8 or RGB565 - RGBA/UNSIGNED_BYTE
* for int formats like R8I - RGBA/INT
* for unsigned formats like R8UI - RGBA/UNSIGNED_INT
* for float formats like R816F - RGBA/FLOAT

For **2** what should it check? 

Let's be concrete. What's are the correct tests for `RGB9_E5` and `RGB5_A1`?

**Comment by jhelferty-nv** [comment]
For a test of case (2), at the ES level you need to be able to validate data in any IMPLEMENTATION_COLOR_READ_FORMAT and IMPLEMENTATION_COLOR_READ_TYPE it gives you as long as it can be found in Table 3.2 (excluding the depth/stencil formats). (*)

Just to add some colour to Mark's answer regarding having multiple ReadPixels formats: I believe the idea is that the GLES 1 implementation could store the texture differently in device memory vs client memory, which means some hardware will need to implement at least one conversion. In those cases, (1) is a client memory-friendly format that's easy for people using the API to use, and (2) is probably going to be a format that more closely matches what's in device memory--so this is probably the fast-path. (Disclaimer: I don't think anything in the spec says it necessarily _has_ to be faster..)

As to your specific questions, assuming no extensions enabled:
* RGB9_E5: Texture-only color format that can't be used as a renderbuffer (See Table 3.13 of GLES 3.0.3 spec, plus it's listed under the texture-only list on page 128), so this is probably an invalid framebuffer error of some sort.
* RGBA5_A1: Renderable; see Table 3.2. (*)
* R16F: Texture-only color format until ES 3.2. In ES 3.2, I'd expect RED/HALF_FLOAT and RED/FLOAT to be possible implementation format/type combos here. (I don't know if this has been exposed yet in WebGL as renderable; if it is, I couldn't find the extension.)

(*) The spec seems to suggest any non-depth/stencil format in that table is legal for IMPLEMENTATION_COLOR_READ_FORMAT and IMPLEMENTATION_COLOR_READ_TYPE. My assumption is that it would have at least as much precision per component as the texture's format, and at least the same components. But I don't know if the spec guarantees that.

**Comment by greggman** [comment]
> * RGBA5_A1: Renderable; see Table 3.2. (*)
>
> (*) The spec seems to suggest any non-depth/stencil format in that table is legal for IMPLEMENTATION_COLOR_READ_FORMAT and IMPLEMENTATION_COLOR_READ_TYPE. My assumption is that it would have at least as much precision per component as the texture's format, and at least the same components. But I don't know if the spec guarantees that.

And there in is the problem.  RED_INTEGER/INT is in table 3.2 so apparently according to the spec RED_INTEGER/INT is a valid combo for RGB5_A1?

It doesn't really seem like the spec intended that but because the spec is ambiguous it's apparently valid ☹️

**Comment by jdashg** [comment]
You've got it, you just don't like it. :)

My read is that IMPL_COLOR_READ_* can be anything at all, and is an alternative to the default accepted format/type for the frambuffer's float/int/uint/norm component type. Among other things, this would expose whatever native format is least-effort (ideally no-effort) to convert. Sometimes this is obvious, like RGBA/HALF_FLOAT for RGBA16F, R/FLOAT for R32F, RGB/UNSIGNED_BYTE for RGB8. Generally what we expect here is that webgl users know that the actual internal format doesn't match RGBA/{UNSIGNED_BYTE,FLOAT,INT,UNSIGNED_INT}, and IMPL_COLOR_READ_* lets them check if they're right that we can give them a better match.

Yes, it's weird that there's an explicit carve-out for RGB10A2, but that's relatively benign. Consider this a choice made to ensure that download of RGB10A2 is never lossy. 

Here's our validation for ReadPixels format/type:
https://searchfox.org/mozilla-central/rev/cfaa5a1d48d6bc6552199e73004ecb05d0a9c921/dom/canvas/WebGLContextGL.cpp#1393

FIrefox exposes what the driver lets us, here, though I think we might only be behaving properly on ES. On Windows with ANGLE Firefox allows RED/FLOAT for R32F.

@greggman Is there anything I missed before we close this issue?

**Comment by greggman** [comment]
No, you're right. I don't like it :P  But it is what it is. I guess except for RGB10A2 all formats can return anything they want. I'd be really surprised if any driver didn't return what we expect so sad the spec doesn't make that more explicit
