### ISSUE TITLE
Invalid Enum error on glGetIntegerv(GL_VERTEX_ARRAY_BINDING,...) with Webgl 1.0

### ISSUE THREAD

**Issue by larsbohn** [KhronosGroup/WebGL#2749]
.. related to https://github.com/KhronosGroup/WebGL/issues/1963

I just stumbled upon this issue in the current ( 46afd23 ) version of emscripten.

glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &aGLInt);

gives INVALID_ENUM in WebGL 1.0 contexts with OES_vertex_array_object present and activated.

This is not expected behaviour, as the rest of the VAO APIs are working correctly.

This seems to be because in

https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js

#if USE_WEBGL2
case 0x85B5: // GL_VERTEX_ARRAY_BINDING
case 0x8919: // GL_SAMPLER_BINDING
case 0x8E25: // GL_TRANSFORM_FEEDBACK_BINDING
#endif

--> only if WebGL2 is used the call is actually executed, but not if just the extension is present...

**Comment by MarkCallow** [comment]
You are using the OES_vertex_array_object extension. In the extension the enum name is `GL_VERTEX_ARRAY_BINDING_OES` so, if that line of code comes from your program you need to fix it. If it comes from some emscripten code that is executed when the extension is active, then it is an emscriptem bug.
