### ISSUE TITLE
GLint vs. GLuint for attribute locations

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/WebGL#2762]
According to the WebIDL, `getAttribLocation` returns a GLint - i.e. a signed integer since it's possible to return `-1` for an unknown location.

However - `vertexAttribPointer` expects the index as a GLuint - i.e. an unsigned integer.

How is it possible for `vertexAttribPointer` to accept values larger than what can be gotten from `getAttribLocation` ?

**Comment by jdashg** [comment]
vertexAttribPointer generates a error for too-large index values, and since
there's no real use for negative values, using an unsigned type there makes
sense.

**Comment by dakom** [comment]
Thanks for the explanation.

I do agree that it makes sense from that perspective. So this is a non-issue for JS:

```
const loc = gl.getAttribLocation(...);
if(loc !== -1) {
  gl.vertexAttribPointer(loc, ...);
}
```

However, when this gets translated into other languages - such as Rust/web_sys which is automatically generated from the WebIDL spec, it then requires casting from an i32 to a u32 which imho seems a bit odd.

I guess "feeling a bit odd" isn't really an issue though, so feel free to close this :)

Thanks!

**Comment by jdashg** [comment]
You can think of it as the cast replacing the unwrapping of an
option/maybe/nullable.

**Comment by dakom** [comment]
Oh - you know what, I had my wrapper around `getAttribLocation` return an `Option<i32>` ... instead I should do the casting there and return `Option<u32>`. Thanks!
