### ISSUE TITLE
gl_VertexID appears to be wrong in ANGLE if offset parameter to gl.drawArrays is non-zero

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2770]
Run this sample http://jsfiddle.net/greggman/fLabtv81/7/

What is the expected output? 

<img width="312" alt="screen shot 2019-01-20 at 5 14 14" src="https://user-images.githubusercontent.com/234804/51431885-65b94180-1c72-11e9-9c89-46e010ceeb08.png">

two sets of 5 red dots. The first set starting from the center of the canvas. The second set starting from 75% across the canvas.

What do you see instead?

<img width="317" alt="screen shot 2019-01-20 at 5 14 38" src="https://user-images.githubusercontent.com/234804/51431889-6c47b900-1c72-11e9-8e7b-4dc378a87d1c.png">

In ANGLE/DirectX both sets of 5 dots start in the center.

Note: Running on Windows 10 with --use-angle=gl works correctly. it also works correctly on MacOS nvidia or intel and on a Pixel2 Android.

Filed a bug on ANGLE here

https://bugs.chromium.org/p/angleproject/issues/detail?id=3090

Probably needs a conformance test.

**Comment by jdashg** [comment]
Huh, I didn't realize that was the behavior! Thanks for finding this.

**Comment by jdashg** [comment]
Test added in #2807.
