### ISSUE TITLE
Separate blend states per color output

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2775]
It should be possible to provide WebGL apps the ability to independently
* enable or disable blending,
* set the blend equations,
* set the blend functions, and
* set the color write masks per color output.

Support seems to be straightforward:

**OpenGL ES**
- Core functionality in OpenGL ES 3.2.
- [`EXT_draw_buffers_indexed`](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_draw_buffers_indexed.txt) for OpenGL ES 3.0/3.1.

**OpenGL**
- Core functionality in OpenGL 4.0.
- [`ARB_draw_buffers_blend`](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_draw_buffers_blend.txt) + [`EXT_draw_buffers2`](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_draw_buffers2.txt) for OpenGL 2.0+.

**Vulkan**
- Core functionality in Vulkan 1.0, see `VkPipelineColorBlendStateCreateInfo.pAttachments`.

**Direct3D**
- Core functionality in Direct3D 11, see `D3D11_BLEND_DESC.IndependentBlendEnable` and `D3D11_RENDER_TARGET_BLEND_DESC`.

**Comment by jdashg** [comment]
Yeah, this would be great!

Do you feel comfortable miming an extension spec together?

**Comment by lexaknyazev** [comment]
I think I can prepare a draft.

**Comment by lexaknyazev** [comment]
@jdashg 
Opened #2777.

**Comment by jdashg** [comment]
Thanks!

**Comment by kenrussell** [comment]
Feedback from @lexaknyazev on utility of this extension:

"The typical use case is to _disable_ blending on the second fragment output (e.g., when it produces non-color data such as Z) while keeping it enabled on the first (e.g., for regular alpha composing)."

**Comment by jdashg** [comment]
Oh! Makes sense. Blend cycles can be precious.
