### ISSUE TITLE
WebGL Quick Reference Guide uses OpenGL identifiers

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2788]
The [WebGL 2.0 reference guide](https://www.khronos.org/files/webgl20-reference-guide.pdf) is full of OpenGL identifiers and enums not WebGL identifiers and enums

That seems not very useful for people using WebGL that don't come from a C/C++/OpenGL background

The [WebGL 1.0 reference guide](https://www.khronos.org/files/webgl/webgl-reference-card-1_0.pdf) does not have this issue

**Comment by greggman** [comment]
Looking closer it's just a section at the top and page 5. The rest of it seems to use WebGL identifiers

<img width="513" alt="screen shot 2019-02-01 at 13 13 18" src="https://user-images.githubusercontent.com/234804/52102356-5eefde80-2623-11e9-87c5-96601b689327.png">

<img width="787" alt="screen shot 2019-02-01 at 13 13 52" src="https://user-images.githubusercontent.com/234804/52102358-62836580-2623-11e9-9b8f-b84b185d6e6f.png">

**Comment by kenrussell** [comment]
Thanks for the report @greggman .

Will contact Khronos about this. To clarify:

The creation of types like WebGLBuffer should be documented like:

"Created by createBuffer, bound by bindBuffer, destroyed by deleteBuffer"

and the types in the "Sized texture color formats" table should all have the GL_ prefixes removed.

**Comment by kenrussell** [comment]
Khronos' marketing has updated the reference guide addressing these problems:
https://www.khronos.org/files/webgl20-reference-guide.pdf

**Comment by greggman** [comment]
oops

Now it references stuff that does not exist in WebGL2 `genBuffers`, `genTextures` etc...

<img width="522" alt="screen shot 2019-02-11 at 0 15 54" src="https://user-images.githubusercontent.com/234804/52535481-46ee2c80-2d92-11e9-8b2c-91cdae97fcb3.png">

**Comment by kenrussell** [comment]
Oops. My mistake. Have asked Khronos to update once more.

**Comment by kenrussell** [comment]
This has now been fixed in https://khronos.org/files/webgl20-reference-guide.pdf .
