### ISSUE TITLE
Support for OES_tessellation_shader extension

### ISSUE THREAD

**Issue by BenjaminTrapani** [KhronosGroup/WebGL#2791]
This extension depends on ES 3.1, while WebGL 2 seems to target 3.0. Loading an extension with string     GL_OES_tessellation_shader fails in WebGL 2. Is there an extension to enable OpenGL ES 3.1? This should enable the tesselation extension to load correctly. Is it correct to use GL_OES_tessellation_shader instead of GL_EXT_tessellation_shader? I have the app compiling and running locally with ES 3.2.

**Comment by kainino0x** [comment]
The only extensions available in WebGL are those listed here:
https://www.khronos.org/registry/webgl/extensions/

Indeed, WebGL 2.0 is equivalent to ES 3.0, but it does not expose the same set of extensions. Some 3.1 features are available for experimentation behind a flag in Chrome as webgl2-compute, but not this one. (see comment 14 here: https://crbug.com/859249#c14 )

In the long run you should expect to look to WebGPU for advanced features beyond ES 3.0. However it won't have tessellation at launch either; possibly later on.

**Comment by jdashg** [comment]
I'll close this, since plan-of-record is to defer support for non-vert/frag shaders to webgpu.
