### ISSUE TITLE
conformance/misc/webgl-specific.html changes need to be ported to 1.03

### ISSUE THREAD

**Issue by slacka** [KhronosGroup/WebGL#2801]
This change https://github.com/KhronosGroup/WebGL/commit/14dc185472c2679ceba016521d2275a0b149ed10#diff-45bd8a34d1959df4d69ffe026e04ce8a

needs to be backported to 1.03 to follow the new expected behavior

https://bugs.chromium.org/p/chromium/issues/detail?id=930309

The 3 tests that are failing on Chrome need to be changed  `gl.INVALID_OPERATIONs` with `[gl.INVALID_OPERATION, gl.NO_ERROR]`.

**Comment by slacka** [comment]
@jdashg Can you please backport https://github.com/KhronosGroup/WebGL/commit/14dc185472c2679ceba016521d2275a0b149ed10#diff-45bd8a34d1959df4d69ffe026e04ce8a to 1.03 ?

**Comment by jdashg** [comment]
It sounds like Chrome is early-outing too early again. DrawArrays() should generate an error if there's a stencil mismatch, even if called with count:0.

**Comment by kainino0x** [comment]
Chrome passes the current version of the test, but not the old version. So I suggested the new behavior be allowed in the old snapshot. But it's not critical.

**Comment by kainino0x** [comment]
Oh, just looked at the linked diff. I didn't realize the test change on ToT was not just changing the expected values, but more involved. Maybe not worth trying to backport allowances then.

**Comment by jdashg** [comment]
The 1.0.3 behavior looks valid to me, so TBH we should forward port the part that Chrome's failing so that we get coverage there.

**Comment by jdashg** [comment]
Reopen if you think it's still an issue.
