### ISSUE TITLE
Expose extension for EXT_texture_norm16

### ISSUE THREAD

**Issue by jdashg** [KhronosGroup/WebGL#2810]
Even with incomplete support on mobile, this is still probably nice to expose.

**Comment by lexaknyazev** [comment]
FWIW, ANGLE already supports it.

**Comment by lexaknyazev** [comment]
Rationale:
- Integer formats do not support filtering.
- Floating point formats with comparable memory consumption provide less precision.
  - `float16` can represent only about 15K distinct values in `0.0 .. 1.0` range.
  - `float11` and `float10` - fewer than 1K and 500 respectively.
- DOM image sources (e.g. PNG) with 16 bits per channel could be copied to GPU without intermediate floating point processing.

**Comment by kenrussell** [comment]
SGTM. Could someone please contribute an extension proposal?

**Comment by astojilj** [comment]
+1
Thanks. Important for 16-bit (depth, IR) camera capture ([W3C mediacapture-depth](https://w3c.github.io/mediacapture-depth/#upload-video-frame-to-webgl-texture)) that is now [using gl.FLOAT](https://w3c.github.io/mediacapture-depth/#upload-video-frame-to-webgl-texture) texture as the only way to access the data, with minor data loss.

**Comment by riju** [comment]
> SGTM. Could someone please contribute an extension proposal?

I will put up an extension proposal soon.

**Comment by jdashg** [comment]
Moved to PR #2837.
