### ISSUE TITLE
Invalid function signature in WebGL 2.0 Quick Reference Guide

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2812]
At the end of page 3:
![image](https://user-images.githubusercontent.com/3479527/53483990-2dd8c180-3a9c-11e9-85d7-f8663a820a89.png)

IDL:
```c
void renderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat,
                                    GLsizei width, GLsizei height);
```

**Comment by kenrussell** [comment]
Thanks for the report. Have asked Khronos to fix the documentation.

**Comment by kenrussell** [comment]
The reference card has been revised fixing this issue:
https://www.khronos.org/files/webgl20-reference-guide.pdf
