### ISSUE TITLE
Program handling is different across browsers

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2842]
My understanding of the spec is that a `WebGLProgram` (or GL program) has internal state like this

```
class WebGLProgram {
   Shader vertexShader;
   Shader fragmentShader;

   // status from last time you called gl.linkProgram
   int linkStatus;

   // message from last time you called gl.linkProgram  
   string infoLog;

   // internal program created by last SUCCESSFUL linkProgram
   Program validProgram; 
}

class Program {
  map<string, int> attribLocations;
  map<string, WebGLUniformLocation> uniformLocations;
  GPUProgramCode compiledProgram
}

class Shader {
  string src;

  // status from last time you called gl.compileShader
  int compileStatus;

  // message from last time you called gl.compileShader  
  string infoLog;

  // internal shader created from last successful compile
  GPUShaderCode compiledShader;
}
```

And that the only thing that really matters at render time is that `someProgram.validProgram` points to valid code. `someProgram.validProgram` is only set when `gl.linkProgram` is successful.

That means after a successful link if you detach or delete shaders there is no problem. 

Similarly if you change the source of a shader and compile that shader but don't link the program has not yet been affected

Further, if you call `gl.linkProgram` and the link fails the previously valid program is still set on `someProgram.validProgram` and is still usable and locations are still valid.

It is only after a **successful** link that `someProgram.validProgram` is updated and that locations become invalid

So, believing this I wrote a test

https://jsfiddle.net/greggman/qkn3mju9/

---

Firefox shows the behavior I expect

<img width="658" alt="Screen Shot 2019-03-29 at 12 51 02" src="https://user-images.githubusercontent.com/234804/55258866-54b42000-5221-11e9-9f94-3ce51fbc5b43.png">

---

Chrome, after calling `gl.linkProgram` with a failed link appears to invalidate the locations but keep the `validProgram` so I can no longer set uniforms but I can still render

<img width="603" alt="Screen Shot 2019-03-29 at 12 52 30" src="https://user-images.githubusercontent.com/234804/55258958-9349da80-5221-11e9-8701-07789388eb56.png">

---

Safari appears to make the failed link make the program unusable

<img width="618" alt="Screen Shot 2019-03-29 at 12 54 01" src="https://user-images.githubusercontent.com/234804/55259015-beccc500-5221-11e9-8411-57002f42cbd8.png">

the quirk in the spec is that you can't call `gl.useProgram` with a program that failed to link. But if you don't call `useProgram` then your previously successful linked program is still usable. And, further, if you cal `useProgram` with a program that failed to link it's effectively a noop. Whatever program was previously the current program is still the current program.

**Comment by shrekshao** [comment]
Just FYI: there's a one in cur conformance test suite https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/programs/program-test.html#L325-L336. But since it's a trivial program it doesn't reveal real problems. Current Angle implementation fail to restore state some cached masks after a failure linkage. The jsfiddle test could possibly sit in that location.
