### ISSUE TITLE
Specify behavior of no-output fragment shader with active draw buffer attachments

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/WebGL#2845]
Some of the early discussion happened under this thread: https://github.com/KhronosGroup/WebGL/pull/2780#issuecomment-476877226

**Comment by shrekshao** [comment]
CC @jdashg @null77

**Comment by kenrussell** [comment]
Updated the synopsis slightly. Need to resolve this in order to finish the conformance tests in this area.

**Comment by shrekshao** [comment]
@jdashg @null77 A reminder for finishing this discussion after Jeff finishing with some experiments.
What we have so far based on latest comment (correct me if there's anything wrong): 
For a no-output fragment shader:
* A version 100 es shader would be considered to have an implicit output gl_FragColor/gl_FragData[0].  Thus making the case with a `gl.COLOR_ATTACHMENT0` or `gl.BACK` unaffected.
* A version 300 es shader would be considered to have exactly no output, under which circumstances, any active `gl.COLOR_ATTACHMENTi` or `gl.BACK` would lead to a `gl.INVALID_OPERATION` error.

**Comment by jdashg** [comment]
We should try this, though I have some fear of breaking content here.

**Comment by kenrussell** [comment]
Also concerned about the potential compatibility impact of this change. I think it may be better to change the rule to not make this an INVALID_OPERATION.

**Comment by jdashg** [comment]
Investigation by @shrekshao in #2856 seems to point towards this being ok to restrict.

**Comment by kenrussell** [comment]
Yes. Real-world content does not seem affected by this restriction.
