### ISSUE TITLE
Transform Feedback is still inconsistent across browsers

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2851]
Note: this is effectively a continuation of https://github.com/KhronosGroup/WebGL/issues/2346

a Transform Feedback Object (TFO) is the output analog of a Vertex Array Object (VAO). It's typical to make hundreds or even thousands of VAOs. One for each thing you want to draw. A VAO contains all of the attribute state so in one command, `gl.bindVertexArray(someVAO)`, you can effectively setup all of the attribute state, what buffers they are reading from, what types of data to pull for each attribute, etc.

Transform Feedback Object is the exact same thing except for output of varyings instead of input of attributes. You make a TFO just like a VAO, you then bind all the output buffers with `gl.bindBufferBase` ro `gl.bindBufferRange`. That state is saved in the TFO.  When you actually want to use transform feedback it's a single command to setup that state. Just `gl.bindTransformFeedback(someTFO)`.

Just like VAOs you'd expect to have lots of TFOs and when needed just bind the one you need.

But, that's not how the browsers seem to be treating them, this time Firefox, is treating them wrong AFAICT. Instead it's almost treating them like global state. At `getBufferSubData` time it's checking, or appears to be checking, every single transform feedback object to see if any of them have any of the current buffers about to be read bound to any TFO. This makes no sense AFAICT. It would be like checking all VAOs at draw time when the only VAO that has any baring on anything is the currently bound one. Similarly for transform feedback the only TFO that has any baring whatsoever is the currently bound one. Any other iterpretation of the spec seems like it makes the spec make absolutely no sense. If you need to search through all transform feedback objects, then there was no reason to have them in the first place since you can never keep any state in them. There would just be global state for the varying outputs that you have to always clear.

In any case there are two issues with Firefox AFAICT

1. Running [this example](https://jsfiddle.net/greggman/9t4Lrdyu/) firefox fails with INVALID_OPERATION on this test because even thought there is no transform feedback bound firefox is checking the unused/unbound transform feedbacks objects when the code calls `getBufferSubData`.

2. Firefox prints superfulous and misleading warnings running [this sample](http://twgljs.org/examples/transform-feedback.html)

> Error: WebGL warning: drawArrays: Vertex attrib 1's buffer is bound for transform feedback.

Even though no transform feedback is bound.

I posted this here rather than filing a bug on Firefox as maybe you want to discuss the spec more. But hoping to get the browsers to run the same here. Seems like more conformance tests are needed.

**Comment by jdashg** [comment]
I think what's happening is the buffer is still bound to the generic
TRANSFORM_FEEDBACK target slot, since bindBufferBase binds the buffer to
both the generic and the indexed slots. Firefox treats this as 'bound in
for TF', though maybe we shouldn't.

**Comment by jdarpinian** [comment]
Yes, I added a test for that in #2659.

**Comment by kenrussell** [comment]
If this is already covered under the conformance tests then this sounds like a Firefox-specific bug.

**Comment by greggman** [comment]
>  since bindBufferBase binds the buffer to both the generic and the indexed slots

What is this generic slot you're referring to? I thought there is no generic slot. There are only the slots on the Transform Feedback Objects. Just like there are no generic attributes, there are only attributes on Vertex Array Objects and there is the default (id = 0) vertex array object. Similarly there is a default (id = 0) transform feedback object (in OpenGL ES).

**Comment by greggman** [comment]
filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1544087

**Comment by jdashg** [comment]
The generic binding point is the non-indexed binding point:
https://jsfiddle.net/k7dyotzc/

* bindBufferBase/Range binds the buffer to both the indexed binding point *and* the generic binding point.
* The generic binding point was moved to context state, previously transform feedback object state.
* Firefox treats the generic binding point as 'bound for transform feedback', which fails the test added in #2659
