### ISSUE TITLE
Constants named DEPTH_STENCIL_* are duplicated in WebGL 1/2

### ISSUE THREAD

**Issue by saschanaz** [KhronosGroup/WebGL#2872]
Both `WebGLRenderingContextBase` and `WebGL2RenderingContextBase` have same `DEPTH_STENCIL` and `DEPTH_STENCIL_ATTACHMENT`. I think we can safely remove them from `WebGL2RenderingContextBase` without any breaking change, thoughts?

**Comment by jdashg** [comment]
Let's remove them.

**Comment by foolip** [comment]
While this is unlikely to break anything, the change is still observable. `WebGL2RenderingContext.hasOwnProperty('DEPTH_STENCIL_ATTACHMENT')` and `WebGL2RenderingContext.hasOwnProperty('DEPTH_STENCIL')` should be false, but is still true in at least Chrome and Firefox.

What would be the right place to add a test asserting that constant *isn't* on the `WebGL2RenderingContext` interface?

**Comment by saschanaz** [comment]
`WebGL2RenderingContext` includes both `WebGLRenderingContextBase` and `WebGL2RenderingContextBase` so I think it shouldn't be observable?

**Comment by foolip** [comment]
You're right, both are still on the WebGLRenderingContextBase mixin, so this shouldn't have any effect. Presumably the previous state of affairs was just invalid Web IDL.

It seems like a bug that https://github.com/web-platform-tests/wpt/pull/16465 changed the test results, I'll investigate.
