### ISSUE TITLE
Add tests for DEPTH_STENCIL renderbuffer allocated and attached in different orders

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#289]
Looking at sdk/tests/conformance/renderbuffers/framebuffer-object-attachment.html , it seems tests are needed for the following situations:

1) allocating a DEPTH_STENCIL renderbuffer with renderbufferStorage, and then attaching it to a framebuffer
2) attaching a renderbuffer to a framebuffer's DEPTH_STENCIL attachment, and then allocating it with renderbufferStorage

On platforms not supporting OES_packed_depth_stencil, an implementation emulating the DEPTH_STENCIL attachment point with two separate renderbuffers may well get case (2) wrong. A rendering test is needed ensuring that the depth and stencil buffers are working properly for these two cases.

**Comment by jdashg** [comment]
I believe we have this.
