### ISSUE TITLE
getBufferParameter is in 2.0 html, but not in the corresponfing .idl file

### ISSUE THREAD

**Issue by yurivict** [KhronosGroup/WebGL#2904]
It is in https://www.khronos.org/registry/webgl/specs/latest/2.0/ but not in https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl

2.0 are supposed to describe functions that were added by the OpenGL ES3 specification. The html says that it was added by ES3, but .idl file doesn't contain it.

Same is true for ```getFramebufferAttachmentParameter``` and many other functions.

**Comment by jdashg** [comment]
The webgl2 interface in the idl is a mixin on top of the webgl1 interface, so functions that were already in webgl1 won't be re-listed in webgl2. (except for possibly some overloads)
