### ISSUE TITLE
Is there a special speed increase for 1 to 1 pixel canvases?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2922]
Emscripten has this in their "Optimizing WebGL" document

> Pay close attention to the visible size of the canvas (the CSS pixels size of the DOM element) versus the physical render target size of the initialized WebGL context on the canvas, and make sure these two match in order to render 1:1 pixel perfect content.

AFAICT that advice has no positive optimization affect.  Is there something I don't know?

Is there even an API to get 1x1 pixel canvases? I thought the answer was no based on [this](https://github.com/KhronosGroup/WebGL/issues/587) and [this](https://github.com/KhronosGroup/WebGL/issues/2460)

**Comment by jdashg** [comment]
I don't think anyone does a slightly-faster-path for this. @kenrussell @greggman 

As I contend in #587, I think 1:1 rendering is possible in most cases, but let's leave that discussion there.

**Comment by kenrussell** [comment]
Agree, there's no special casing in Chrome for this and I doubt there is in any browser.

If you'd like the Emscripten folks to update their docs to illustrate cases where they might actually want to scale up a smaller back buffer size to a larger on-screen size (like consoles frequently do), please put up a pull request on their repo.

We are still working through the issues of providing web APIs to allow 1:1 pixel accurate rendering, which is desired for some use cases.
