### ISSUE TITLE
[EXT_draw_buffers_indexed] Constant Alpha Blend Factors

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2938]
D3D11 supports only "constant color" blending factors, so ANGLE emulates "constant alpha" factors by rewriting the constant color to `aaaa`. See [`StateManager11::syncBlendState`](https://github.com/google/angle/blob/087f1384f233792921d34c0ca5b5a90fac75b070/src/libANGLE/renderer/d3d/d3d11/StateManager11.cpp#L1246-L1264).

This is reflected in the WebGL spec, [Blending With Constant Color](https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.15):
> In the WebGL API, constant color and constant alpha cannot be used together as source and destination factors in the blend function. A call to `blendFunc` will generate an `INVALID_OPERATION` error if one of the two factors is set to `CONSTANT_COLOR` or `ONE_MINUS_CONSTANT_COLOR` and the other to `CONSTANT_ALPHA` or `ONE_MINUS_CONSTANT_ALPHA`. A call to `blendFuncSeparate` will generate an `INVALID_OPERATION` error if `srcRGB` is set to `CONSTANT_COLOR` or `ONE_MINUS_CONSTANT_COLOR` and `dstRGB` is set to `CONSTANT_ALPHA` or `ONE_MINUS_CONSTANT_ALPHA` or vice versa.

The OpenGL ES `EXT_draw_buffers_indexed` extension (and the corresponding OpenGL 4.0 feature) enables separate blend factors per each color output, but the constant color remains the same for all of them. This means that the WebGL `EXT_draw_buffers_indexed` extension has to have an additional restriction to work on D3D11.

There are two options.
- Disallow use of `CONSTANT_ALPHA` and `ONE_MINUS_CONSTANT_ALPHA` factors with indexed blend state completely (easier to implement).
- Extend existing WebGL restriction to indexed blend states. That would require more runtime validation on D3D11.

**Comment by jdashg** [comment]
I think we should just extend our existing restrictions.

**Comment by jdarpinian** [comment]
That sounds reasonable to me. We'll discuss in the meeting tomorrow.

**Comment by lexaknyazev** [comment]
With this WebGL-specific behavior driven by D3D11 limitations, should we change the prefix to `ANGLE_` or `WEBGL_`?

**Comment by kenrussell** [comment]
I think it's fine to just leave it as EXT_draw_buffers_indexed and describe the WebGL-specific limitations in the extension - there's a space for this in https://www.khronos.org/registry/webgl/extensions/EXT_draw_buffers_indexed/ which isn't filled out.

We still need help implementing this as an enable-able extension in ANGLE. If that were done then hooking it up to WebGL would be easy.
