### ISSUE TITLE
3th draw black arrays may fail?

### ISSUE THREAD

**Issue by guan-ln** [KhronosGroup/WebGL#2949]
https://github.com/KhronosGroup/WebGL/blob/2701c130839edbeb226735b0775966b6423d9e83/sdk/tests/conformance2/vertex_arrays/vertex-array-object-and-disabled-attributes.html#L120

in my tests, both 2th and 3th draw is green, but in this test case,  3th draw expect to be black, so case fail;
case fail may due to the following reason,  please confirm? thanks
1. in case line 87, program vertex shader is singlevshader,  API gl.vertexAttribPointer, set vertexArray's postion attribute, first parameter (index) is singlePositionLocation;  but in line 120, program vertex shader is dualvshader, position attribute location is positionLocation;  
2. in singlevshader and dualvshader,  input variable position with no location assigned in the shader text, so when a program is linked, GL API automatically assigned location; these two position location in different shaders may not equal;  
3. if var positionLocation is not equal to singlePositionLocation,  then 3th draw black array failed; 
4. in my tests, i find singlePositionLocation is 0, but positionLocation is 1, colorLocation is 0, so 3th draw black fail;

**Comment by jdashg** [comment]
Yep, the test is buggy.

**Comment by kenrussell** [comment]
Thanks for the report. Agree that there is a bug in the test.

Filed https://bugs.chromium.org/p/angleproject/issues/detail?id=4049 about fixing this in the original ANGLE test from which the WebGL conformance test was ported. Uploaded pull request #2950 fixing the test. (The test didn't exist in the 2.0.0 conformance suite snapshot so the fix doesn't need to be backported.)
