### ISSUE TITLE
Does getShaderPrecisionFormat return new objects?

### ISSUE THREAD

**Issue by jdashg** [KhronosGroup/WebGL#2965]
`getActiveAttrib` is clear that it returns a new object, so this one probably should too, but there's no spec-text either way.

**Comment by kenrussell** [comment]
Yes, it does. The documentation in this section:
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.9

says:

"Return a new WebGLShaderPrecisionFormat..."

**Comment by jdashg** [comment]
Weird, I missed that somehow!
