### ISSUE TITLE
WebGL 2.0 CTS conformance2/textures/video test tolerance needs adjustment

### ISSUE THREAD

**Issue by yzhang-verisilicon** [KhronosGroup/WebGL#2973]
WebGL 2.0 CTS conformance2/textures/video  mp4 tests currently have tolerance = 5 for pixel value difference. However, this tolerance value is too small for some VeriSilicon mobile GPUs to pass. So VeriSilicon would like to request WebGL WG to adjust

    var tolerance = 5;
in
2.0.0/js/tests/tex-image-and-sub-image-2d-with-video.js
2.0.0/js/tests/tex-image-and-sub-image-3d-with-video.js
to

    var tolerance = 6;

We believe this is within WebGL 2.0 and OpenGL ES Spec requirements.

**Comment by jdarpinian** [comment]
We discussed this at the WebGL working group meeting today and there were no objections to this change. Please go ahead and make a pull request and I will merge it.

**Comment by kenrussell** [comment]
Fixed by the pull request above.
