### ISSUE TITLE
getFramebufferStatus -> checkFramebufferStatus

### ISSUE THREAD

**Issue by Elchi3** [KhronosGroup/WebGL#2976]
In https://www.khronos.org/registry/webgl/extensions/OVR_multiview2/

> Calling **get**FramebufferStatus for a framebuffer in this state returns FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR.

Should probably be:

Calling **check**FramebufferStatus for a framebuffer in this state returns FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR.

**Comment by jdarpinian** [comment]
Thanks!
