### ISSUE TITLE
GLSL Shader in conformance2/textures/video/tex-2d-* needs proper #version directive

### ISSUE THREAD

**Issue by yzhang-verisilicon** [KhronosGroup/WebGL#2981]
The following CTS tests

conformance2/textures/video/tex-2d-rg8ui-rg_integer-unsigned_byte.html
conformance2/textures/video/tex-2d-rgb9_e5-rgb-half_float.html
conformance2/textures/video/tex-2d-srgb8_alpha8-rgba-unsigned_byte.html
conformance2/textures/video/tex-2d-rgba8ui-rgba_integer-unsigned_byte.html

include this GLSL shader:

#extension GL_OES_EGL_image_external : enable
#ifdef GL_ES
precision mediump float;
#ifdef GL_FRAGMENT_PRECISION_HIGH
#define TexCoordPrecision highp
#else
#define TexCoordPrecision mediump
#endif
#else
#define TexCoordPrecision
#endif
#define TextureType uvec4
#define ZERO 0u
#define MAX_COLOR 255u
#define ScaleValue 255.0
#define TextureLookup texture2D
#define VARYING varying
#define FRAGCOLOR gl_FragColor
#define SamplerType samplerExternalOES
uniform SamplerType u_sampler;
uniform mat4 u_tex_coord_transform;
VARYING TexCoordPrecision vec2 v_uv;
void main(void) {
  TexCoordPrecision vec4 uv = u_tex_coord_transform * vec4(v_uv, 0, 1);
  vec4 color = TextureLookup(u_sampler, uv.st);
  FRAGCOLOR = TextureType(color * ScaleValue);
}

However, this shader uses ESSL 3.0 features:

1) builtin type "uvec4"
2) implicit type conversion in "FRAGCOLOR = TextureType(color * ScaleValue);"

without declaring “#version 300 es” in the first line. So our GLSL compiler treats this shader as version 1.00 according to ESSL 3.0 spec, and reports shader grammar errors as ESSL version 1.00 does not support "uvec4" data type and implicit type conversion.

A proper version directive
#version 300 es
needs to be added in the first line of the shader.

**Comment by kainino0x** [comment]
Can you clarify where this shader text is coming from? I can't find it anywhere in the code for this test. Is this output from a shader translator (i.e. ANGLE shader translator from webgl to gles)? What browser and OS is this running on?

**Comment by yzhang-verisilicon** [comment]
1. The shader text is captured in GLES API glShaderSource() in our driver.
2. Not sure if the shader is from a shader translator.
3. The browser is "google_chrome_71.0.3578.83_androidapksbox.apk". The OS is Android 9.

**Comment by kainino0x** [comment]
I was very confused about where this shader could be coming from since it seems like it's not a shader from the test.

Someone in the WebGL WG meeting realized this might be coming from Chrome's internal CopyTextureCHROMIUM. And, indeed, it is:
https://cs.chromium.org/chromium/src/gpu/command_buffer/service/gles2_cmd_copy_texture_chromium.cc

I've re-filed this under Chrome. https://crbug.com/1031255
