### ISSUE TITLE
compressedTexSubImage2D in Firefox

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2994]
When a texture is uploaded from a PBO, `compressedTexSubImage2D` entrypoint accepts `imageSize` and `offset` parameters.

Why does Firefox expect that a PBO cannot have any data after the texture (i.e. buffer's length must be equal to `offset+imageSize`)?
https://hg.mozilla.org/mozilla-central/file/tip/dom/canvas/WebGLTextureUpload.cpp#l206

/cc @jdashg

**Comment by jdashg** [comment]
Please file a bug.

**Comment by lexaknyazev** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1606830.
