### ISSUE TITLE
ASTC tests do not cover LDR/HDR profiles support

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3010]
The extension declares `sequence<DOMString> getSupportedProfiles()` function that should provide accurate information about supported profiles. Currently, tests do not even call it.

**Comment by lexaknyazev** [comment]
@kenrussell @jdarpinian 
This function `getSupportedProfiles` is not even present in Chromium's WebIDL.

Compare:
https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/modules/webgl/webgl_compressed_texture_astc.idl

and

https://github.com/KhronosGroup/WebGL/blob/e2d87d086888da34c9c954877963e6327a64a853/extensions/WEBGL_compressed_texture_astc/extension.xml#L307-L342

What should we do here: remove it from the extension, add to the CTS, or make it optional (is it even allowed)?

**Comment by kenrussell** [comment]
That's an oversight - sorry about that. Filed http://crbug.com/1049806 about it.
