### ISSUE TITLE
ETC1/ETC2 detection

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3014]
ETC2/EAC formats are a part of OpenGL ES 3.0 core spec, but they were deliberately omitted from WebGL 2.0 as there's no support for them on many target platforms (e.g. D3D11).

The situation with OpenGL drivers is quite interesting. According to the spec, desktop OpenGL drivers can advertise support for these formats through `GL_ARB_ES3_compatibility` extension or simply by supporting OpenGL 4.3+ core. __This does not mean that these formats are actually supported in hardware.__

For this reason, Chromium/ANGLE has a quite sophisticated feature detection.

- **ANGLE**
  - When running on OpenGL 4.3 (or higher) or `GL_ARB_ES3_compatibility` extension is present, ANGLE enables these formats and exposes them using dedicated extension strings like `OES_compressed_ETC2_*_texture` and `OES_compressed_EAC_*_texture`.
  - When running on native OpenGL ES 3.0+, ANGLE additionally exposes `GL_ANGLE_compressed_texture_etc` extension string.
- **Chromium**
  - Completely ignores context version or dedicated format strings and checks only for `GL_ANGLE_compressed_texture_etc` so that the `WEBGL_compressed_texture_etc` extension is enabled only on OpenGL ES contexts.
  - By the way, this does not apply to `WEBGL_compressed_texture_etc1` extension. It is exposed in Chromium on all OpenGL contexts (bug?).

---

On the other hand, Firefox simply checks for OpenGL 4.3 or `GL_ARB_ES3_compatibility` and enables `WEBGL_compressed_texture_etc` if either is available.

This leads to at least two sub-optimal cases:
- When an application tries to guess what compressed format to use at runtime (either out of pre-encoded variants or by relying on Basis transcoding), it may see `_etc*` extension and use it despite the lack of hardware support.
- Some hardware (e.g. recent Intel GPUs) actually has proper ETC2 support in their OpenGL (and even Vulkan) drivers. There seems to be no way to reliably query that.

**Comment by kainino0x** [comment]
> * By the way, this does not apply to `WEBGL_compressed_texture_etc1` extension. It is exposed in Chromium on all OpenGL contexts (bug?).

Have you observed that this extension is available on desktop systems? If so, could you file a short chromium bug report including the about:gpu from that system?

From inspecting the code it seems like it should be correct:
`WEBGL_compressed_texture_etc` requires `OES_compressed_ETC1_RGB8_texture`.
We [only enable](https://cs.chromium.org/chromium/src/gpu/command_buffer/service/feature_info.cc?l=1058&rcl=3e53cb46f6b9ad399e782233147ad3b921e7e0ca) that if the driver (system or ANGLE) exposes it, and it should only be there if the underlying driver is ES (mobile or ANGLE).
And according to this comment, ANGLE only exposes it if it's natively supported. (This is different from ETC2 because ETC2 is core in ES3.) Though that comment could be wrong.

**Comment by lexaknyazev** [comment]
That comment is wrong. ANGLE exposes `GL_OES_compressed_ETC1_RGB8_texture` regardless of the context.

**Comment by lexaknyazev** [comment]
> Have you observed that this extension is available on desktop systems? If so, could you file a short chromium bug report including the about:gpu from that system?

I'm seeing `WEBGL_compressed_texture_etc1` on all my Windows machines (two NV and one Intel) when switching ANGLE to OpenGL.

**Comment by kainino0x** [comment]
Makes sense. ANGLE probably enables it now if GL_ARB_ES3_compatibility is available. (I don't think ANGLE is emulating it, or we would be seeing it on ANGLE-on-D3D too.)

**Comment by lexaknyazev** [comment]
> ANGLE probably enables it now if GL_ARB_ES3_compatibility is available.

Or when the context version is 4.3+. There's no intermediate check like with ETC2.

---

Anyway, this and ETC2 availability in Firefox realistically affect only Linux desktops for now since macOS stays on 4.1 and Windows uses D3D by default.

**Comment by kainino0x** [comment]
Filed https://crbug.com/1048244

**Comment by kainino0x** [comment]
The Chromium bug affects any platform using ANGLE-on-desktop-GL, which (does|will) be Mac and Linux. (Not sure of the shipping status of ANGLE on Mac/Linux right now.)

**Comment by lexaknyazev** [comment]
Both issues have been fixed in ANGLE for OpenGL:
- `OES_compressed_ETC1_RGB8_texture` is no longer exposed for desktop contexts.
- `ANGLE_compressed_texture_etc` is now exposed on newer Intel GPUs that have native support for ETC2/EAC.

---
@jdashg 
Could Firefox' handling of `WEBGL_compressed_texture_etc` be refined?
* At the very least, the extension should be disabled on desktop OpenGL contexts because ETC2/EAC formats are almost always emulated there. 
* Optionally, the extension could be enabled on newer Intel GPUs. The condition for "newer Intel GPUs" is:
  > All Intel GPUs that support `GL_ARB_ES3_compatibility` except "Sandy Bridge", "Ivy Bridge", and "Haswell" (ANGLE source has the relevant PCI device ids).
