### ISSUE TITLE
ASTC NaN-to-magenta conversion does not work on Intel OpenGL

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3016]
According to the ASTC spec, a block filled with zeros is considered to have "Reserved" mode. For such a case, the spec says:
> Decoders are required to recognize all illegal blocks and emit the standard error color value upon encountering an illegal block. Here is a comprehensive list of situations that represent illegal block encodings:
>- The block mode specified is one of the modes explicitly listed as Reserved.
>- ...

> For linear RGB decode, the error color may be either opaque fully-saturated magenta `(1.0, 0.0, 1.0, 1.0)` or a vector of four NaNs.

Tests convert NaNs to magenta in GLSL (added in #2962):
```glsl
vec4 c = texture2D(tex, texCoord);
if (all(notEqual(c, c))) {
    gl_FragData[0] = vec4(1, 0, 1, 1);
} else {
    gl_FragData[0] = texture2D(tex, texCoord);
}
```

This snippet does not work as expected on Intel OpenGL and produces (0, 0, 0, 0) for NaNs.

For this reason, WebGL 2.0 CTS fails with
```
FAIL texture should be initialized to error color at (0, 0) expected: 255,0,255,255 was 0,0,0,0
```

/cc @jdarpinian

**Comment by kenrussell** [comment]
@lexaknyazev This is on a recent Mesa driver on an Intel GPU, correct?

You should probably file this on https://bugs.freedesktop.org/describecomponents.cgi?product=Mesa , possibly in the subcomponent "Mesa core". They will probably want a small native test case.

CC @gyagp @Richard-Yunchao - do either of you have advice on how this bug can be reported?

**Comment by lexaknyazev** [comment]
I don't think that it's necessarily a driver issue. The shader code in question relies on compare operators with NaN argument. AFAIK, this is undefined in GLSL ES 1.0 and very loosely defined in GLSL ES 3.0.

**Comment by lexaknyazev** [comment]
> This is on a recent Mesa driver on an Intel GPU, correct?

That's on Windows 10 1909 (10.0.18363.592), Intel UHD Graphics 600, driver version 26.20.100.7755.

**Comment by Richard-Yunchao** [comment]
@kenrussell , looks like that  https://bugs.freedesktop.org/describecomponents.cgi?product=Mesa is obsolete and mesa team uses gitlab right now: https://gitlab.freedesktop.org/mesa/mesa/issues

**Comment by kenrussell** [comment]
@lexaknyazev looking through the GLSL ES 1.0 and 3.00 specs again, you're right, isnan() was only introduced in ESSL 3.00, and NaN behavior is barely discussed in the 1.00 spec.

Could you locally try upgrading that test to use WebGL 2.0 and ESSL 3.00, and the isnan() primitive, to make the comparison more precise and understand whether the texture sampling is returning NaNs, or all black? Thanks.

**Comment by lexaknyazev** [comment]
Will do. This would have to wait until tomorrow because I don't have remote access to that machine.
By the way, ANGLE emulates `isnan` on Intel OpenGL, hopefully this won't affect the results.

**Comment by lexaknyazev** [comment]
I have verified locally with ESSL 3.0 shaders - texture sampling returns NaNs as expected. I'll make a PR that updates ASTC tests for all recently discussed issues.
