### ISSUE TITLE
Viability of other specs enabling WebGL extensions automatically.

### ISSUE THREAD

**Issue by toji** [KhronosGroup/WebGL#3021]
In the Immersive Web working group we have been discussing an API to surface a WebGL texture that contains float or half float data. Given that this is not feature of the WebGL 1.0 core spec, though it is available as an extension, the question of how to handle returning that data when the developer is using a WebGL 1.0 context has come up. There seems to be three possible approaches:

1. Restrict the API to only be accessible with WebGL 2.0, which includes float/half float textures in core. This is the most straightforward option, but may be unnecessarily restrictive.
2. Only allow the texture to be returned if the developer previously (successfully) queried the appropriate extension. This is also relatively straightforward but has a bit of a "spooky action at a distance" feel to it where the API may or may not work depending on whether you ever looked at a largely unrelated object, probably in a significantly different part of the code.
3. Have the new API attempt to query the API itself. This has the advantage of always working as long as hardware support for the feature is available, but also introduces the reverse "spooky action at a distance" problem, where now certain WebGL calls may become valid depending on when it was called relative to the new API.

Option 3 was raised as a possibility by @grorg at the most recent WebGL face to face, and it's attractive in terms of allowing our API to "just work". Despite that, it's also definitely something we wanted the WebGL working group to weigh in on before exploring further.

**Comment by kenrussell** [comment]
Given the WebGL WG's recent focus to try to support WebGL 2.0 everywhere, my personal preferences would be first #1, then #3. Other opinions?

**Comment by kainino0x** [comment]
Is it possible to require the extension already be enabled by the time you try to use it for XR? This would be the least surprising and can be easily explained through a console error/warning message.

**Comment by kainino0x** [comment]
(I.e. not make it "just work", but have it tell you exactly what to do to make it work)

**Comment by jdashg** [comment]
#1 for sure, though even in WebGL 2, you can't render-to-float without
EXT_color_buffer_float. (and don't forget EXT_blend_float!)

What's the goal that float surfaces aim to satisfy?

**Comment by toji** [comment]
I've been part of a few different discussions on this topic now and the general sens that I get from them is, unsurprisingly, that we probably shouldn't be "magically" enabling extensions when you make otherwise unrelated calls.

The options of limiting the API in question to WebGL 2.0 or requiring that the extension be enabled beforehand for WebGL 1.0 are both still tractable and the WebXR group will have to discuss further to see which route we want to take. @jdashg suggested that for the WebGL 1.0 path we could require that the floating point texture extension actually be passed in as a parameter to the WebXR function call if we really want to make absolutely sure that it's enabled before hand. I find that idea amusing, but it seems like a bit of a blunt instrument for beating API users into compliance. 😆 Still, it's something we'll consider moving forward.

In any case, I think we can consider this issue closed from the WebGL side.
