### ISSUE TITLE
Which error code should be returned by gl.readPixels()?

### ISSUE THREAD

**Issue by asajeffrey** [KhronosGroup/WebGL#3036]
Which error code should be returned by `gl.readPixels()` when it is given an invalid format?

The spec (https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.12) says `INVALID_OPERATION`.

The test says `GL_INVALID_ENUM` https://github.com/KhronosGroup/WebGL/blob/b49347b2c51eba1a60e63046bd8b9db0f2f8efba/sdk/tests/conformance/reading/read-pixels-test.html#L158-L162

**Comment by asajeffrey** [comment]
This is causing test failures in Servo, which follows the spec. https://github.com/servo/servo/issues/12859

**Comment by jdashg** [comment]
The INVALID_ENUM from "unrecognized enum" comes before INVALID_OP from "unrecognized combo of otherwise-vaild enums", if I remember the previous discussions right.

**Comment by jdashg** [comment]
I guess we do that sometimes, but not other times: #2452 #2552

**Comment by jdashg** [comment]
In Gecko we have special code for detecting these cases:
ReadPixels: https://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextGL.cpp#1043
TexImage: https://searchfox.org/mozilla-central/source/dom/canvas/WebGLTextureUpload.cpp#946

**Comment by jdashg** [comment]
I can't find a reference in this repo, so maybe it's in meeting notes somewhere, but historically we have this behavior that I described and linked to in Gecko. I believe it was me who wanted this to accept either historically, but the WG decided against it, and the validation isn't that hard to add.

**Comment by asajeffrey** [comment]
Hmm, where in the spec does it say `readPixels` can generate `INVALID_ENUM`? Does it inherit this behaviour from OpenGL ES?

**Comment by jdashg** [comment]
Yes, unless stated otherwise, all GLES behavior is implied, including
errors.

**Comment by asajeffrey** [comment]
OK, I guess this answers my question... `INVALID_ENUM` should be returned, and the relevant bit of the WebGL spec is https://www.khronos.org/registry/webgl/specs/latest/1.0/#1.1 saying that the GLES spec has precedence over the WebGL spec.
