### ISSUE TITLE
Switch statement tests

### ISSUE THREAD

**Issue by samsinsane** [KhronosGroup/WebGL#3058]
I encountered this bug the other day in both Chrome and Firefox, and I'm not entirely sure what to do about it. The `default` case is not executed in this scenario:
```glsl
switch(0)
{
  default:
    ...
}
```
Bit of backstory: At work we use Shader Conductor to convert our DirectX shaders to Metal, OpenGL, and OpenGL ES/WebGL shaders. This pattern seems to be generated due to functions being inlined into `main`, and the functions with multiple returns end up generating this `switch` statement. For what it's worth, this pattern worked fine for OpenGL on Windows, and Metal on macOS.

I was able to workaround this issue by replacing `default` with `case 0`, but figured I should at least report this somewhere and I stumbled across this repo while trying to find out if this was "by design" in WebGL. Since I couldn't find anything saying that `default` statements can be ignored under certain conditions, and since it seems to be browser independent, I figure that it's a conformance test problem and should be reported here? Unfortunately, I don't really have that much time to dedicate to this, so chasing individual browser vendors around on this isn't feasible, but I can add more tests to `switch-case.html` if that gets the ball rolling?

**Comment by kenrussell** [comment]
This sounds like a bug. Yes, please create a pull request adding more tests to switch-case.html.

Please also provide the contents of about:gpu from Chrome or about:support from Firefox on the machines where this isn't working. That will help narrow down whether this is a browser, shader translator, OS-specific, or graphics driver problem. Thanks.

**Comment by samsinsane** [comment]
> This sounds like a bug. Yes, please create a pull request adding more tests to switch-case.html.

No worries, I can do that.

> Please also provide the contents of about:gpu from Chrome or about:support from Firefox on the machines where this isn't working.

Both have a "Copy to Clipboard" button which seems to contain significantly less information but seems more inline with what you want? Is this the data that I should post, or do you need the full thing, tables and all?

**Comment by kainino0x** [comment]
In chrome at least, the button should include everything (it just uses JS to select-all and copy).

**Comment by samsinsane** [comment]
Strange, it seems to be copying more than 7 lines today, I must have done something wrong yesterday. I've attached the reports here:
[HomeDesktopFirefox.txt](https://github.com/KhronosGroup/WebGL/files/4534657/HomeDesktopFirefox.txt)
[HomeDesktopChrome.txt](https://github.com/KhronosGroup/WebGL/files/4534659/HomeDesktopChrome.txt)
[WorkLaptopChrome.txt](https://github.com/KhronosGroup/WebGL/files/4534658/WorkLaptopChrome.txt)

**Comment by kenrussell** [comment]
Thanks for the new tests; they've been merged now. Filed http://crbug.com/angleproject/4807 about this; Microsoft indicates that a workaround in ANGLE's shader translator is probably the best bet.

Closing this issue since the tests are in place and there's an ANGLE bug tracking potential workarounds.

**Comment by samsinsane** [comment]
@kenrussell Thanks for merging the PR and adding the ANGLE bug link! 😄
