### ISSUE TITLE
Image loading tests have become flaky after #3052

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3076]
#3052 seems to have introduced significant flakiness into the tests which load cross-origin images. On Chromium's automated testing system, the following bugs have been found:

WebGL origin-clean-conformance-* test fail because image loading failed
http://crbug.com/1082525

conformance/textures/misc/origin-clean-conformance.html is flaky
http://crbug.com/1083100

@jdashg @shrekshao @jdarpinian how can we fix this flakiness? In hindsight, 1000 ms is too short a timeout for some slow bots.

**Comment by kenrussell** [comment]
One more bug:

conformance/more/functions/readPixelsBadArgs.html is flaky
http://crbug.com/1083320

**Comment by jdashg** [comment]
Make the delay bigger I guess.
