### ISSUE TITLE
Malformed comment at top of draw-with-changing-start-vertex-bug.html

### ISSUE THREAD

**Issue by kainino0x** [KhronosGroup/WebGL#3090]
@jdashg I think this happened when you replaced the license headers.

**Comment by kainino0x** [comment]
(Doesn't affect the test behavior, though.)

**Comment by jdashg** [comment]
Oops, yep, probably.

**Comment by jdashg** [comment]
It's a pain to grep for multiline content! It looks like this is the only bug of this type though.
