### ISSUE TITLE
WebGL 2.0 can't render to FP textures on devices with only EXT_color_buffer_half_float

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3093]
While adding support for EXT_color_buffer_half_float to WebKit's ANGLE backend for WebGL in https://bugs.webkit.org/show_bug.cgi?id=212181 , it was discovered that the OpenGL ES 3.0 implementation on iOS advertises EXT_color_buffer_half_float, but not EXT_color_buffer_float.

WebGL's https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_half_float/ extension declares that it was subsumed by https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_float/ in WebGL 2.0. EXT_color_buffer_float is only allowed to be exposed if the device supports FP32 render targets, which iOS does not.

How can this be resolved? Options include:

- Allow EXT_color_buffer_half_float to be exposed from WebGL 2.0 implementations, with behavioral differences from WebGL 1.0, like dropping support for rendering to GL_RGB half-float textures.
- Define a new half-float renderability extension for WebGL 2.0.
- Expose EXT_color_buffer_float on WebGL 2.0, but allow implementations to say that framebuffers with 32-bit floating-point texture attachments are incomplete.

Thoughts on other options and opinions on these?

**Comment by kenrussell** [comment]
CC @jdarpinian @shrekshao @kainino0x @jdashg @grorg @RafaelCintron in particular for thoughts.

**Comment by jdashg** [comment]
I vote #1, to fixup EXT_color_buffer_half_float for webgl2.

**Comment by kenrussell** [comment]
That's my preference too.

**Comment by kenrussell** [comment]
Note this came to mind while reading this PlayCanvas pull request which adds floating-point texture-based morph target support: https://github.com/playcanvas/engine/pull/2123 .

**Comment by grorg** [comment]
I agree with @jdashg and @kenrussell that option 1 is the best.
