### ISSUE TITLE
WebGL application hosted on Azure App Service Plan taking time to load unityweb

### ISSUE THREAD

**Issue by vermaaditya** [KhronosGroup/WebGL#3104]
Hi, 

We are having a WebGL project which we are trying to host in an Azure App service plan. When we host the site in the App Service plan in Central US region and try to access the same from either Azure VM (P1v2: 1) in Central US or a machine in Asia region the time for a file to load is very high. 

Please find the network trace screenshot of one such request - 
![image](https://user-images.githubusercontent.com/20763984/85306948-d64e3880-b4cc-11ea-8a47-13b6c327dd0c.png)

The above took around 1.1 min. 
When we host the application in Southeast Asia region the time is reduced to ~20 seconds. 

And when we are hosting the same application in Github pages the load time is less then 5 seconds - 
![image](https://user-images.githubusercontent.com/20763984/85307179-3349ee80-b4cd-11ea-82fc-256a741cbfef.png)

Kindly help us in why is the time taken for a unityweb file so high. 

PS: the internet speed is not a factor as the same is being tested via Azure VMs.

**Comment by jdashg** [comment]
This is a Unity issue, not WebGL.
