### ISSUE TITLE
Move OES_draw_buffers_indexed to community approved

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3107]
ANGLE (D3D11 and OpenGL/ES) and Chromium implementations are ready (available in Canary with `#enable-webgl-draft-extensions`).

- [x] We need either WebKit or Firefox implementations to move OES_draw_buffers_indexed to community approved.

**Comment by kenrussell** [comment]
Possible for you to file bugs on bugs.webkit.org and bugzilla.mozilla.org about implementing this extension?

**Comment by lexaknyazev** [comment]
WebGL CTS was added in #3066.
Chromium's implementation (complete): https://crbug.com/1058744.
ANGLE implementation is complete for OpenGL, D3D11, and Vulkan. Metal support is coming.

WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=222430
