### ISSUE TITLE
Consider moving EXT_clip_cull_distance forward

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3109]
As pointed out on the public_webgl mailing list here:
https://www.khronos.org/webgl/public-mailing-list/public_webgl/2006/msg00007.php

a use case for the EXT_clip_cull_distance extension is 2D rendering. From Kevin Rogovin:

"""
The main place is for 2D (UI rendering). One example is in a public
repo, https://github.com/intel/fastuidraw. There, I use HW-clip planes
together with the depth buffer to make clipping changes (severe
changes, like clip against a filled path, rotated rects and so on)
really cheap and almost entirely handled by the GPU. I also find it
really useful for an offscreen rendering technique I use in a current
(but closed source) project. I can emulate with discard, but tests
show that this has a large negative performance impact.
"""

The working group should consider moving this extension forward - first by providing one implementation.

**Comment by krogovin** [comment]
As a side note, when discard is used instead of clip-planes, anti-aliasing from MSAA does not work since the discard would broadcast to all samples.

**Comment by krogovin** [comment]
I've filed a PR: https://github.com/KhronosGroup/WebGL/pull/3110 to allow for the number of supported cull planes to be 0; this allows for the extension to supported on a much larger class of devices and drivers.

**Comment by lexaknyazev** [comment]
The `GL_EXT_clip_cull_distance` OpenGL ES extension provides clipping planes toggling via `gl.enable`/`gl.disable` and `gl_ClipDistance` / `gl_CullDistance` built-ins for vertex shaders (out) and fragment shaders (in).

Here's how backend implementation requirements would look like:
| Feature | OpenGL | OpenGL ES | Direct3D 11 | Metal |
|---|---|---|---|---|
| Clipping planes toggling via `gl.enable`/`gl.disable` | 3.0+ | `GL_APPLE_clip_distance` or<br>`GL_EXT_clip_cull_distance` | Needs emulation | Needs emulation |
| `gl_ClipDistance` vertex output | 3.0+ | `GL_APPLE_clip_distance` or<br>`GL_EXT_clip_cull_distance` | ✅ | ✅ |
| `gl_ClipDistance` fragment input | 3.0+ | `GL_EXT_clip_cull_distance` | ✅ | Needs emulation |
| `gl_CullDistance` vertex output | `GL_ARB_cull_distance`<br>or 4.5+ | `GL_EXT_clip_cull_distance` | ✅ | ❌ |
| `gl_CullDistance` fragment input | `GL_ARB_cull_distance`<br>or 4.5+ | `GL_EXT_clip_cull_distance` | ✅ | ❌ |

Besides making cull distance support optional (or removing it altogether?), the extension may need to omit `gl_ClipDistance` from fragment shaders to make Metal implementation easier. With that many changes, it should probably have `WEBGL_` prefix.

@kenrussell @kdashg WDYT?

**Comment by krogovin** [comment]
One comment: the extension has a minor tweak making it OK for the number of **_CULL_** planes to be zero, so it is already optional.

**Comment by lexaknyazev** [comment]
`gl_ClipDistance` behaves like a varying. So emulating it in fragment shaders would involve allocating and aliasing a real varying.

**Comment by krogovin** [comment]
For me, I do NOT use the value of gl_ClipDistance in the fragment shader at all, so yes still super useful even it is not present in the fragment shader.

Though if that becomes the case, then the extension should get the WEBGL_ prefix is my opinion since it then varies quite a bit.

I know that Metal and D3D11 have hardware clip planes (atleast that is what the docs claim they are), I strongly suggest that the extension is only present on desktop devices and those embedded devices that advertise GL_APPLE_clip_distance or GL_EXT_clip_cull_distance. Never emulate the triangle clipping is my strong suggestion.

**Comment by lexaknyazev** [comment]
Let's start with a prototype implementation as `WEBGL_clip_distance`, which would be functionally identical to `GL_APPLE_clip_distance`, using only hardware clip planes.

Then, we would be able to reasonably evaluate whether providing interpolated clip distance value in fragment shaders and/or exposing optional cull distance built-ins are worth the effort.
