### ISSUE TITLE
Make EXT_texture_norm16 exposed to WebGL 2 only and promote to community approved.

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/WebGL#3114]
@jdashg We agreed on https://gitlab.khronos.org/webgl/member-tools/-/wikis/26-Mar-2020#issues-and-pull-requests-issues-and-pull-requests that we would make EXT_texture_norm16 to only exposed to WebGL 2 and make it public then. I found https://github.com/emscripten-core/emscripten/pull/10227 and seems emscripten and unity would expect this change back in Jan -_-!!
I think we've done the implementation and cleared known issues in Chromium (http://crbug.com/1000354). Would you mind modifying the spec and promote this extension to community approved? Thanks!

**Comment by kenrussell** [comment]
Let me take this since it seems Jeff is busy.

**Comment by kenrussell** [comment]
Good work Shrek getting this over the finish line!
