### ISSUE TITLE
Relax implicit power-of-two restrictions for mipmapped textures in WEBGL_compressed_texture_s3tc

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3117]
Context:
https://github.com/BinomialLLC/basis_universal/issues/154
https://github.com/KhronosGroup/KTX-Software/issues/254
https://github.com/KhronosGroup/KTX-Specification/issues/123

https://bugs.chromium.org/p/angleproject/issues/detail?id=4841
https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc/
https://www.khronos.org/registry/OpenGL/extensions/ANGLE/ANGLE_texture_compression_dxt.txt

It appears that longstanding restrictions in the ANGLE_texture_compression_dxt extension, which were lifted into WebGL's WEBGL_compressed_texture_s3tc extension, have had the following consequences:

1) Because all texture levels beyond those of width/height 1 or 2 have to have width/height divisible by 4, this implies that all levels have to be power-of-two sized.

2) Because this restriction exists for S3TC, and because this is one possible transcoding target of Basis Universal textures, this implies that all textures processed with this pipeline have to obey the power-of-two restriction in case they are transcoded at runtime to S3TC.

The WebGL WG must figure out a solution to this problem. https://bugs.chromium.org/p/angleproject/issues/detail?id=4841
 tracks investigation at the ANGLE layer, which will inform a specification-level solution.

**Comment by lexaknyazev** [comment]
More context from D3D specs.
- D3D9: https://docs.microsoft.com/en-us/windows/win32/direct3d9/compressed-texture-resources
  > All texture compression formats are powers of two. While this does not mean that a texture is necessarily square, it does mean that both x and y are powers of two. For example, if a texture is originally 512 by 128 bytes, the next mipmapping would be 256 by 64 and so on, with each level decreasing by a power of two. 
- D3D11: https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#19.5.1%20Overview
  > BC format surfaces are always multiples of full blocks, each block representing 4x4 pixels. For mipmaps, the top level map is required to be a multiple of 4 size in all dimensions. The sizes for the lower level maps are computed as they are for all mipmapped surfaces, and thus may not be a multiple of 4, for example a top level map of 20 results in a second level map size of 10.

**Comment by kenrussell** [comment]
@RafaelCintron mentioned during the last WebGL conference call that he thought there were D3D9 texture capability bits affecting its behavior, and indeed there are:

https://docs.microsoft.com/en-us/windows/win32/api/d3d9caps/ns-d3d9caps-d3dcaps9

The `D3DPTEXTURECAPS_POW2` and `D3DPTEXTURECAPS_NONPOW2CONDITIONAL` bits in TextureCaps control the support. D3D9 can support full mipmapped non-power-of-two (NPOT) textures if neither of these two bits are set. If `D3DPTEXTURECAPS_POW2` and `D3DPTEXTURECAPS_NONPOW2CONDITIONAL` are set, then "conditional" NPOT support is present (see the page for the full definition), but this explicitly disallows NPOT DXT compressed textures.

Upon further thought, there might be a simple solution to this problem. WebGL 1.0, being based on OpenGL ES 2.0, already doesn't support mipmapped non-power-of-two textures, compressed or not. (And fortunately, the WebGL working group resisted adding an NPOT extension to WebGL 1.0, as that would have made most WebGL content non-portable to mobile devices at the beginning of the specification's lifetime.) WebGL 2.0, based on OpenGL ES 3.0, supports NPOT textures, and it's not possible to implement WebGL 2.0 on top of D3D9. What if the NPOT restrictions for WEBGL_compressed_texture_s3tc were simply removed in WebGL 2.0 contexts? It doesn't even seem necessary to change the behavior in WebGL 1.0 contexts.

**Comment by vonture** [comment]
The fixes for these have landed in ANGLE and Chrome (soon):
https://chromium-review.googlesource.com/c/angle/angle/+/2380237
https://chromium-review.googlesource.com/c/chromium/src/+/2416748

The newly supported features are:
 - texture level 0 must be block size aligned
 - other mip levels can be any size (but the texture won't be complete if they don't form the mip pyramid)

The test coverage we'll need is:
 - Test NPOT DXT textures with non-block-sized mip levels. Ex: 12x12, 6x6, 3x3, 1x1
 - Coverage of CompressedTexImage2D, CompressedTexSubImage2D and TexStorage2D

**Comment by kenrussell** [comment]
Expanding the conformance tests in this area is urgent - otherwise it's likely regressions will creep in. Could someone help expand WebGL's S3TC conformance tests for these new scenarios? CC @lexaknyazev @shrekshao

**Comment by kenrussell** [comment]
Note: https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc/ might require changes as well - not completely sure.

**Comment by lexaknyazev** [comment]
@kenrussell 
The WebGL extension specs (WEBGL_compressed_texture_s3tc and WEBGL_compressed_texture_s3tc_srgb) should be updated to relax the requirement in WebGL 2.0 contexts.

@vonture
> the texture won't be complete if they don't form the mip pyramid

Would something like this be valid with overridden TEXTURE_BASE_LEVEL and TEXTURE_MAX_LEVEL?
- level 0: 12x12, omitted
- level 1: 6x6 (8x8), present
- level 2: 3x3 (4x4), present
- level 3: 1x1 (4x4), omitted

**Comment by vonture** [comment]
This is the case I'm still thinking about. It won't work right now but I recognize that it's a useful use case for PBR.

It's maybe possible to support non-zero TEXTURE_BASE_LEVEL if the texture is mip complete from level 0 to TEXTURE_MAX_LEVEL AND TEXTURE_BASE_LEVEL to TEXTURE_MAX_LEVEL but extra logic in the D3D backend will be needed.

**Comment by lexaknyazev** [comment]
Are immutable textures easier to support? It's fine to have missing levels filled with zeros as long as they are not sampled.

**Comment by vonture** [comment]
Yes, immutable textures are easier. If the texture is specified as non-immutable in ANGLE's D3D backend, we only create a final storage texture for the base to max level, not the entire thing (as it may not be mip complete). We don't currently have logic to see if it's possible to create a larger-than-requested texture. This could possibly be done though.

**Comment by kenrussell** [comment]
@vonture with your recent changes in ANGLE, is it expected that NPOT support for WEBGL_compressed_texture_s3tc is working well in WebGL 2.0?

@lexaknyazev do you think you might be able to expand out the WebGL conformance tests in this area to make sure this functionality doesn't regress? It's critical for Basis Universal.

**Comment by kenrussell** [comment]
The test case from https://github.com/BinomialLLC/basis_universal/issues/158 :
http://ahyoomee.miru.hk/basis/demo/threejs.html

is working correctly on Chrome with the above bug fixes from @vonture .

It's still failing in Firefox Nightly and Safari Technology Preview, though it does work in Safari.

Have filed the following browser bugs to track this:

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1675410
WebKit: https://bugs.webkit.org/show_bug.cgi?id=218595

**Comment by lexaknyazev** [comment]
@kenrussell 
Porting tests added in #3112 should do the trick. Will do.  

In the meantime, could we agree on the base level issue and clarify the specs? Here's an expected use case: to start rendering as soon as possible, an app could override the TEXTURE_BASE_LEVEL and upload lower-resolution images first, even before level 0 is ready. Assuming that level 0 dimensions are multiples of 4, this should be quite straightforward for immutable textures (maybe works already?). If supporting this for non-immutable textures is impractical, we could further refine the specs. Since the overridden base level behavior is expected to be the same for all sixteen BC formats, we'd need another test for that.

**Comment by kenrussell** [comment]
Sorry for taking so long to reply @lexaknyazev .

@vonture is on vacation now so let me reply in his place. I think that he found it easier than expected to support this in ANGLE: please see the changes in https://bugs.chromium.org/p/angleproject/issues/detail?id=4841 .

Could you try writing the test and include various scenarios like the ones you pointed out in https://github.com/KhronosGroup/WebGL/issues/3117#issuecomment-697998046 , ideally both for immutable and non-immutable textures, and see whether it's currently passing?

Thanks for your help.
