### ISSUE TITLE
Expand EXT_texture_norm16 conformance test to test uploading DOM elements / ImageBitmaps / etc. to texture image

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/WebGL#3141]
I'm gonna add this one.

**Comment by kenrussell** [comment]
Thanks Shrek - assigned this one to you.

**Comment by shrekshao** [comment]
I have a stupid question (some basic concept understanding issue....)
For passing image src data/imageBitmaps to texImage2D, is the webgl expecting an 8bit input image (png and jpg only seems to support 8bit image)? (But the EXT_texture_norm16 spec doesn't expect a valid combination of UNSIGNED_BYTE as the type and RGBA16_EXT as the internalformat)
Or is the webgl expecting an 16bit input image as input? (But tif is not supported for dom img object)

**Comment by lexaknyazev** [comment]
PNG supports 16-bit pixels: https://www.w3.org/TR/2003/REC-PNG-20031110/#11IHDR

**Comment by shrekshao** [comment]
Ah... Thanks for the pointer. It's a shame I didn't know that

**Comment by kenrussell** [comment]
In a meeting this week, @juj from Unity asked whether WebP supports 16 bits per channel - we're investigating that.

**Comment by jaikrishnan** [comment]
> In a meeting this week, @juj from Unity asked whether WebP supports 16 bits per channel - we're investigating that.

WebP assumes 8-bits per channel for [lossless](https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification?hl=en#1_introduction)

**Comment by shrekshao** [comment]
Thanks for the detail.

Closing this as we now put DOM elements uploading for 16 bpcc into a new extension. Proposal is here: https://github.com/KhronosGroup/WebGL/pull/3191
