### ISSUE TITLE
Add [AllowShared] support to WEBGL_multi_draw

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3219]
In https://github.com/emscripten-core/emscripten/pull/11650#issuecomment-780691935 it was pointed out that the [WEBGL_multi_draw extension](https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw/) doesn't apply the [AllowShared] attribute to the typed arrays it receives. In WebAssembly applications compiled via Emscripten, this typically means the incoming arrays need to be copied out of the WebAssembly heap.

The WEBGL_multi_draw extension should be updated to allow the incoming typed arrays to come from a SharedArrayBuffer.

**Comment by kenrussell** [comment]
@shrekshao would you be able to take this? It's a relatively small spec and implementation change that just needs a small addition to the conformance test.

**Comment by jdashg** [comment]
This is OK but beware the risks of validating-then-operating-on shared data! You may not have to copy it out of the heap, but you will have to snapshot (at least pieces of) it at some point!

**Comment by kenrussell** [comment]
Good point @jdashg . The implementation will take care of this - as it does for the [AllowShared] uses in the core WebGL 1.0 and 2.0 APIs.

**Comment by jdashg** [comment]
Yep, we have to handle this already e.g. for index buffer uploads. (we copy into our index buffer validation cache and then upload from that copy)

**Comment by kenrussell** [comment]
Let me help make this small spec update.
