### ISSUE TITLE
Disallowing filtering when using sampler2DShadow?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#3359]
> The texture is not multisample; either the magnification filter is not NEAREST, or the minification filter is neither NEAREST nor NEAREST_MIPMAP_NEAREST; and...the effective internal format specified for the texture arrays is a sized internal depth or depth and stencil format (see table 8.11), and the value of TEXTURE_COMPARE_MODE is NONE.

Apparently filtering of depth textures is not allowed but most (all?) implementations are allowing it if the sampler is `sampler2DShadow`

https://jsgist.org/?src=1d175927a891af5fdc203a3cccd3964e

Stable Windows/Macos/Firefox/Safari/Chrome all look like this
<img width="317" alt="chrome-macos-sampler2DShadow" src="https://user-images.githubusercontent.com/234804/141187561-7083bb87-5967-4123-b500-55b76b9d807f.png">

iOS Safari they are not filtered when set to LINEAR but they do render

**Comment by kenrussell** [comment]
So I can find these more easily: this is a follow-on to #3353 . That quote's from GLES 3.0.6 section 3.8.13 "Texture Completeness" p. 161.

In the jsgist above, the TEXTURE_COMPARE_MODE is set to COMPARE_REF_TO_TEXTURE - so, per the spec, the texture should be considered complete even though the magnification filter is set to LINEAR.

**Comment by greggman** [comment]
It seems strange to me that d32f would be allowed to be LINEAR filtered if R32F is not (requires OES_texture_float_linear)

**Comment by kenrussell** [comment]
Agreed. It looks like OES_texture_float_linear should govern whether D32F textures are filterable. This is an oversight in implementations and the conformance suite.

**Comment by greggman** [comment]
Is gating on OES_texture_float_linear right? It doesn't mention depth textures, and nothing that I can find mentions filtering DEPTH_COMPONENT16 or DEPTH_COMPONENT24.

**Comment by kenrussell** [comment]
This seems like an underspecified area of the GLES 3.0 spec and extensions. As you pointed out, filterability of 32-bit floating point texture formats in general is a hardware feature, not supported universally on mobile hardware. It seems likely to me that hardware that supports filtering of D32F formats would also support OES_texture_float_linear and filtering of 32F color formats.

I'm not sure we should make a spec change in this area right now - if we required WebGL applications to enable OES_texture_float_linear to regain their current `sampler2DShadow` behavior, that could break web content.

**Comment by greggman** [comment]
Well, that depends on your definition of "break". Those apps are already broken on mobile unless they are doing their own "if (mobile) don't filter" check.  My guess is they'll just look worse.

I asked here https://github.com/KhronosGroup/OpenGL-API/issues/84 but I don't see any ligit way to know if a depth texture is ever fiterable in ES.

It seems to me they need to have OES_depth_texture_linear (for D16 and D24) and OES_float_death_texture_linear (for D32F)

I get pragmatically, doing nothing might be fine but as it is, the only way to check if you can linear filtered depth textures is to try rendering with them and checking the result.

**Comment by kenrussell** [comment]
It is unfortunate that DEPTH_COMPONENT32F is a required texture format but that mobile hardware might (silently, in the ES specs) not support filtering it.

For completeness, this came up in WebKit bug https://bugs.webkit.org/show_bug.cgi?id=232071 , where filtering of DEPTH_COMPONENT16 textures using TEXTURE_COMPARE_MODE == COMPARE_REF_TO_TEXTURE (I think) wasn't working in WebGL 2.0 on iOS on top of ANGLE's Metal backend.

Applications could probably portably use DEPTH_COMPONENT16 on mobile hardware and expect filtering to work.

Let's see what the OpenGL working group has to say. Hopefully they watch the above issue tracker; if not we can notify them via other channels.

**Comment by kdashg** [comment]
We discussed this just now in meeting.

AIs:
1. **I will add errata to the depth-texture extension and webgl2 specs** that say it's currently "implementation-defined", to reflect our current situation explicitly.
2. **I want to add at least an (unconditional one-shot) warning in Firefox when users rely on this behavior**, and I think KR was in favor of doing this in Chrome as well.

**We briefly discussed whether we might want to restrict to NEAREST and require some new WEBGL_depth_texture_linear extension for LINEAR**. There's tension here because when we do restrict to NEAREST (e.g. on some Macs?), that constitutes a bug for some applications, and we don't want to be too hasty to regress such apps everywhere, even if this would force them to improve the portability of their apps. For now we're going to try the AIs listed above, and hope that the ecosystem corrects based on those changes.

**Comment by kdashg** [comment]
Oops, this really is webgl2-only, isn't it? WEBGL_depth_texture doesn't include shadow samplers.

**Comment by kdashg** [comment]
Btw here's where we mark it as filterable in Firefox: https://searchfox.org/mozilla-central/rev/4bce7d85ba4796dd03c5dcc7cfe8eee0e4c07b3b/dom/canvas/WebGLTexture.cpp#317-318

**Comment by greggman** [comment]
Here's an example detection function

```js
function isDepthFormatFilterable(gl, format) {
  const oldViewport = gl.getParameter(gl.VIEWPORT);
  const oldTexture = gl.getParameter(gl.TEXTURE_BINDING_2D);
  const oldProgram = gl.getParameter(gl.CURRENT_PROGRAM);

  gl.viewport(0, 0, 1, 1);

  const vs = `#version 300 es
  out vec2 v_uv;
  void main() { 
    // generate a 0 to 1 quad
    vec2 xy = vec2(gl_VertexID % 2, (gl_VertexID / 2 + gl_VertexID / 3) % 2);
    // convert to a -2 to +2 quad
    gl_Position = vec4(xy * 4. - 2.0, 0, 1);
    v_uv = xy;
  }
  `;

  const fs = `#version 300 es
  precision mediump float;
  uniform highp sampler2DShadow tex;
  in vec2 v_uv;
  out vec4 fragColor;
  void main() {
    float d = texture(tex, vec3(v_uv, 0.5));
    fragColor = vec4(d, 0, 1, 1);
  }
  `;
  const createShader = (gl, type, src, prg) => {
    const sh = gl.createShader(type);
    gl.shaderSource(sh, src);
    gl.compileShader(sh);
    gl.attachShader(prg, sh);
    gl.deleteShader(sh);
  };
  const prg = gl.createProgram();
  createShader(gl, gl.VERTEX_SHADER, vs, prg);
  createShader(gl, gl.FRAGMENT_SHADER, fs, prg);
  gl.linkProgram(prg);
  gl.useProgram(prg);

  const formatToTypeDataMap = new Map([
    [ gl.DEPTH_COMPONENT16,  { type: gl.UNSIGNED_SHORT, data: new Uint16Array([0, 0xFFFF]), }, ],
    [ gl.DEPTH_COMPONENT24,  { type: gl.UNSIGNED_INT,   data: new Uint32Array([0, 0xFFFFFFFF]), }, ],
    [ gl.DEPTH_COMPONENT32F, { type: gl.FLOAT,          data: new Float32Array([0, 1]), }, ],
  ]);

  const {type, data} = formatToTypeDataMap.get(format);
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  gl.texImage2D(gl.TEXTURE_2D, 0, format, 2, 1, 0, gl.DEPTH_COMPONENT, type, data);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_COMPARE_MODE, gl.COMPARE_REF_TO_TEXTURE);
  gl.clear(gl.COLOR_BUFFER_BIT);
  // Draw's a 4x4 quad on 1x1 pixel viewport with a 2x1 texture
  // If textures are filtered then the color drawn should be between
  // the 2 values in the texture. If it's not filtered the color
  // will be 0 or 1 (0x00 or 0xFF)
  gl.drawArrays(gl.TRIANGLES, 0, 6);
  const pixel = new Uint8Array(4);
  gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixel);
  const canFilter = pixel[0] !== 0 && pixel[0] !== 255;

  gl.viewport(...oldViewport);
  gl.bindTexture(gl.TEXTURE_2D, oldTexture);
  gl.useProgram(oldProgram);
  gl.deleteTexture(tex);
  gl.deleteProgram(prg);

  return canFilter;
}
```

which you can call like this

```js
const gl = document.createElement('canvas').getContext('webgl2');
const isFilterable = isDepthFormatFilterable(gl, gl.DEPTH_COMPONENT16);
```

example:

```js
const gl = document.createElement('canvas').getContext('webgl2');
console.log(`DEPTH_COMPONENT16: ${isDepthFormatFilterable(gl, gl.DEPTH_COMPONENT16) ? 'can' : 'can not'} be filtered`);
console.log(`DEPTH_COMPONENT24: ${isDepthFormatFilterable(gl, gl.DEPTH_COMPONENT24) ? 'can' : 'can not'} be filtered`);
console.log(`DEPTH_COMPONENT32F: ${isDepthFormatFilterable(gl, gl.DEPTH_COMPONENT32F) ? 'can' : 'can not'} be filtered`);
```

On my M1 it return true for all formats, on my iPhone it returns false
