### ISSUE TITLE
Chromium-based web browser webgl issue in Windows operating system

### ISSUE THREAD

**Issue by youga114** [KhronosGroup/WebGL#3365]
Hi.
I found an webgl issue.

https://codepen.io/youga114/pen/ExwxRjG
I repeatedly called the webgl.clear function through the window.requestAnimationFrame function and I called the loseContext function.

Whenever the loseContext function is called, the canvas area blinks white.
This can only be seen in the Windows operating system, Chromium-based web browser and WebGLRenderingContext(There is no problem with WebGL2RenderingContext).

Thanks for reading.

**Comment by youga114** [comment]
I want to fix it.
I'm analyzing the code.
thank you. =)

**Comment by kenrussell** [comment]
When the WebGL context is lost there is no guarantee that the browser will be able to display the previous contents of the WebGL-rendered canvas.

I see a brief white flash in Chrome on macOS as well.

Apologies, but I don't see a bug in the browser here.
