### ISSUE TITLE
Links broken for reference [GLES30] and [GLES30GLSL]

### ISSUE THREAD

**Issue by SuperSodaSea** [KhronosGroup/WebGL#3373]
The reference link for **[GLES30]** and **[GLES30GLSL]** are broken and both of them went to 404:

https://github.com/KhronosGroup/WebGL/blob/44a1ee1d15ac80bd08041c1c9f5bc0bfca79d13e/specs/latest/2.0/index.html#L4299-L4308

The link for **[GLES30GLSL]** (GLSL ES 3.00.6):

> http://www.khronos.org/registry/gles/specs/3.0/GLSL_ES_Specification_3.00.pdf

can be simply replaced with

> https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf

now.

However the link for **[GLES30]**:

> http://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.4.pdf

refers to GLES **3.0.4**, but I can only find the latest pdf for GLES **3.0.6** on khronos' pages

> https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf

which I think cannot be replaced directly.

**Comment by Khronoswebmaster** [comment]
@kenrussell are the suggested links the best ones to use?

**Comment by SuperSodaSea** [comment]
By the way, the link for reference **[WEBIDL]** https://heycam.github.io/webidl/ is still working but being a redirection to https://webidl.spec.whatwg.org/ .
https://github.com/KhronosGroup/WebGL/blob/44a1ee1d15ac80bd08041c1c9f5bc0bfca79d13e/specs/latest/2.0/index.html#L4318-L4322

**Comment by Khronoswebmaster** [comment]
Thank you @SuperSodaSea. You are welcome of course to make a PR for these link changes. We can then ask for reviews and approve if all looks good.
