### ISSUE TITLE
Reject WEBGL_compress_texture

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3376]
The 10-year-old draft is still in the `proposals` folder:
https://github.com/KhronosGroup/WebGL/blob/main/extensions/proposals/WEBGL_compress_texture.html

**Comment by kdashg** [comment]
+1 from me.

**Comment by kenrussell** [comment]
Agreed, let's reject this proposal. The common use case is to compress art assets offline. Online compression of video frame textures, for example, would not work in real time regardless.
