### ISSUE TITLE
Consider adding extensions similar to EXT_debug_marker and EXT_debug_label

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/WebGL#3384]
[GL_EXT_debug_label](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_debug_label.txt) and [GL_EXT_debug_marker](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_debug_marker.txt). Similar functionality has been added to WebGPU and developers are finding it extremely useful. It would allow annotating the trace found in spector.js or other graphical debuggers.

This extension seems to already be present in ANGLE so maybe it's just a matter of piping things through (at least on browsers configurations that use ANGLE).

FYI @magcius

**Comment by greggman** [comment]
I don't know if anyone would actually use it but it would relatively easy (1-2 days work) to refactor [webgl-lint](https://github.com/greggman/webgl-lint) to implement WEBGL_debug as a polyfill

**Comment by magcius** [comment]
What I would really like is for object labels and debug markers to be passed through to the native backend, for debugging in RenderDoc.
