### ISSUE TITLE
[webgl1] Web IDL syntax error

### ISSUE THREAD

**Issue by autokagami** [KhronosGroup/WebGL#3407]
🤖 This is an automatic issue report for Web IDL syntax error. 🤖

[webidl2.js](https://github.com/w3c/webidl2.js) says:

```
Syntax error at line 438 in webgl1,12, since `interface mixin WebGLRenderingContextBase`:
    attribute PredefinedColorSpace drawingBufferColorSpace = "srgb";
                                                           ^
```

> Error: Unterminated attribute, expected `;`

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

**Comment by dontcallmedom** [comment]
(the error is that attributes can't take default values)
