### ISSUE TITLE
Revisit constant blend color clamping test

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3413]
The `conformance/rendering/blending.html` test and ANGLE do not agree whether the constant blend color should be clamped when floating-point color buffers are not supported.

Specifically, ANGLE clamps the color value on store on non-extended ES 2.0 contexts (likely following the example [here](https://chromium-review.googlesource.com/c/angle/angle/+/1541723/comments/36d38fdf_067eb122)). While the WebGL test has different expectations.

/cc @kdashg @kenrussell

**Comment by kdashg** [comment]
ES 3.0.6 p182 `BlendColor`:
> The constant color can be used in both the source and destination blending
functions. If destination framebuffer components use an unsigned normalized
fixed-point representation, the constant color components are clamped to the range
[0, 1] when computing the blend factors.

ES 2.0.25 p100 `BlendColor`:
> The four parameters are clamped to the range [0, 1] before being stored. The
constant color can be used in both the source and destination blending functions.

https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_color_buffer_half_float.txt:
>  (modify Blend Color section removing the clamp, p. 98) The constant color
    C_c to be used in blending is specified with the command

ES's EXT_color_buffer_float is technically ES3-only, and doesn't mention BlendColor.

Our WebGL 1 extension https://www.khronos.org/registry/webgl/extensions/WEBGL_color_buffer_float/ does have the es3-style behavior though:
> NOTE: fragment shaders outputs gl_FragColor and gl_FragData[0] will only be clamped and converted when the color buffer is fixed-point and blendColor() and clearColor() will no longer clamp their parameter values on input. Clamping will be applied as necessary at draw time according to the type of color buffer in use.

---

Effectively I think we have es3-style don't-clamp behavior spec'd everywhere except technically webgl1-without-color_buffer_[half_]float-enabled. (which should pedantically clamp-on-store still)
I think that's what I relied on when I wrote blending.html, but I could have messed it up somewhere in there!

**Comment by kdashg** [comment]
Ah yeah, ok this part is technically wrong for unextended es2:
```
        debug('');
        debug("State queries don't clamp.");

        const gl = wtu.create3DContext();
        gl.blendColor(1000, 1, 1, 1);
        const was = gl.getParameter(gl.BLEND_COLOR);
        expectArray(was, [1000, 1, 1, 1]);
```

**Comment by lexaknyazev** [comment]
RGBA16F and RGBA32F subtests also do not pass on unextended WebGL 1.0 because they set the blend color before enabling the extensions.

**Comment by lexaknyazev** [comment]
When a WebGL 1.0 implementation exposes `EXT_color_buffer_half_float` and/or `WEBGL_color_buffer_float` but cannot technically support unclamped blend color (e.g. ANGLE on D3D9), should it still store the value unclamped?

In general, are state queries supposed to reflect the effective or the requested values?
