### ISSUE TITLE
Clarify implicit clears with blitFramebuffer and clearBuffer*

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3436]
From WebGL 1.0, Section 2.2:
> WebGL presents its drawing buffer to the HTML page compositor immediately before a compositing operation, but only if at least one of the following has occurred since the previous compositing operation:
>
> - Context creation
> - Canvas resize
> - `clear`, `drawArrays`, or `drawElements` has been called while the drawing buffer is the currently bound framebuffer

With WebGL 2.0, one could use `blitFramebuffer` and/or `clearBuffer*` with the default back buffer as a destination. Does this operation trigger an implicit clear? Whatever the answer is, the CTS should cover it.

**Comment by greggman** [comment]
Do `drawArraysInstanced`, `drawElementsInstanced`, and `drawRangeElements` also need to be mentioned? and also all the added draw methods on extensions?

**Comment by lexaknyazev** [comment]
Since multi-draw and instanced commands are defined as repeating the basic draw ops with different parameters, I think that's implied. Nothing wrong with mentioning all of them explicitly, though. Given the recent findings, the tests should nevertheless be exhaustive.

**Comment by kkinnunen-apple** [comment]
In many ways `clearBuffer()` is repeating the basic draw op of `clear()` so in that way it seems to be implied, similar to the multi draw and instanced.

**Comment by kenrussell** [comment]
Agreed, the new WebGL 2.0 commands do imply this implicit clear. Let's update the WebGL 2.0 specification to amend the WebGL 1.0 spec section.

Some work has been done in this area previously. #2628 added one related conformance test, covering the Chromium fix in https://crbug.com/828262 . #3183, covering https://crbug.com/1149176 , is also related. Others would be welcome.

**Comment by lexaknyazev** [comment]
From ES 3.0, Section 4.3.3, **BlitFramebuffer**:
> If _mask_ is zero, no buffers are copied.

From ES 3.0, Change Log for 3.0.1:
> Clarify that _mask_ may be zero for **BlitFramebuffer** indicating no action be taken (Bug 9748).

Does it mean that `gl.blitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, 0, filter)` to the default framebuffer should not cause a WebGL implicit clear?

**Comment by kdashg** [comment]
We discussed this in meeting today and decided that it should indeed cause presentation even if the func is a no-op, same as drawArrays(count=0) or clear(0).
