### ISSUE TITLE
Allow extra IDL members when appropriate

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#3479]
Some tests assert that WebGL context objects do not have any unknown members. This approach fails when a browser implements another specification that extends `WebGLRenderingContextBase`.

For example, `conformance/offscreencanvas/methods.html` fails in Chromium because of [`makeXRCompatible`](https://immersive-web.github.io/webxr/#dom-webglrenderingcontextbase-makexrcompatible).

**Comment by kdashg** [comment]
I thought we had a PR to fix this somewhere!

**Comment by kdashg** [comment]
#3198
