### ISSUE TITLE
How to add a large number of test items in the include option of conformance-suites's url

### ISSUE THREAD

**Issue by shliar** [KhronosGroup/WebGL#3493]
I want to perform many tests on conformance-suites/2.0.0, which account for about 60% of the total. When I want to add the include option or the skip option to the url in China, I cannot include all the test items I need in a url, because I find that when the length of the url is close to 8000 characters, the web page will not load correctly. Can I add some code to a file so that a letter can represent many test items? For example, adding include: test1 to the url can cover 60% of the test items I need

**Comment by greggman** [comment]
I don't know if you'd find this useful or confusing but as an example you can see how Chrome runs the tests here

https://source.chromium.org/chromium/chromium/src/+/main:content/test/gpu/gpu_tests/webgl_conformance_integration_test.py

It injects JavaScript that uses existing hooks into the CTS.

It reads a list of tests to NOT run.
