### ISSUE TITLE
Should check disjoint after available is true in EXT_disjoint_timer_query_webgl[2] samples?

### ISSUE THREAD

**Issue by qjia7** [KhronosGroup/WebGL#3497]
In [EXT_disjoint_timer_query](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt), it says that `In order to know if the value returned from GetIntegerv or GetQuery is valid GPU_DISJOINT_EXT needs to be used to make sure the GPU did not perform any disjoint operation. This can be done through GetIntegerv by using GPU_DISJOINT_EXT for <pname>.`. So we can see in the examples there, `glGetIntegerv(GL_GPU_DISJOINT_EXT, &disjointOccurred)` is always called after available is true in `glGetQueryObjectiv(queries[N-1], GL_QUERY_RESULT_AVAILABLE, &available)`, which can make sure that disjoint is checked after all commands are finished. However, in [EXT_disjoint_timer_query_webgl2](https://registry.khronos.org/webgl/extensions/EXT_disjoint_timer_query_webgl2/)’s sample code, specially for Example (3), it uses it as below:
```
          let disjoint = gl.getParameter(ext.GPU_DISJOINT_EXT);
          let available;
          if (disjoint) {
            // Have to redo all of the measurements.
          } else {
            if (useTimestamps) {
              available = gl.getQueryParameter(endQuery, gl.QUERY_RESULT_AVAILABLE);
            } else {
              available = gl.getQueryParameter(timeElapsedQuery, gl.QUERY_RESULT_AVAILABLE);
            }

            if (available) {
            …
            }
          }

```
Per my understanding, disjoint checking should be called after available checking is true. Otherwise, it may happen that available is true, but disjoint is also true. But we never check disjoint again in above code. Is this a problem for the example?

@kenrussell @kdashg

**Comment by kenrussell** [comment]
Re-reading https://registry.khronos.org/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt , it's legal to query the disjoint flag at any time; the disjoint flag is cleared whenever it's queried. You make a good point that the repeated querying of the disjoint flag in example (3) seems to make the code less precise - the disjoint flag could be set at a time that wouldn't necessarily invalidate the queries' results. This seems like it would be a pretty rare race condition though. The main point of example (3) is to span both timestamp queries and elapsed time queries. If you can think of a way to simplify the code, please feel free to open a pull request. (Note that in Chrome, at least, timestamp queries were disabled on all platforms due to their non-portability, so example (3) is only there for completeness. Example (1) is the recommended pattern.)

**Comment by qjia7** [comment]
```
// Clear the disjoint state before starting to work with queries
let disjoint1 = gl.getParameter(ext.GPU_DISJOINT_EXT);
...
gl.beginQuery(ext.TIME_ELAPSED_EXT, timeElapsedQuery);
gl.drawElements(...);
gl.endQuery(ext.TIME_ELAPSED_EXT);
...
let disjoint2 = gl.getParameter(ext.GPU_DISJOINT_EXT);
if (!disjoint2) {
  let available = gl.getQueryParameter(timeElapsedQuery, gl.QUERY_RESULT_AVAILABLE);
  if (available )
  {
    // let disjoint3 = gl.getParameter(ext.GPU_DISJOINT_EXT);
    // collect the time
  }
}
```
I know it's legal to query the disjoint flag at any time. What I want to stress is that the last disjoint checking position should be behind available is true. Otherwise, how do you know whether any disjoint happens during `disjoint2` and `disjoint3` in above code. Is it better to change the code like below:
```
// Clear the disjoint state before starting to work with queries
let disjoint1 = gl.getParameter(ext.GPU_DISJOINT_EXT);
...
gl.beginQuery(ext.TIME_ELAPSED_EXT, timeElapsedQuery);
gl.drawElements(...);
gl.endQuery(ext.TIME_ELAPSED_EXT);
...
let available = gl.getQueryParameter(timeElapsedQuery, gl.QUERY_RESULT_AVAILABLE);
if (available )
{
    let disjoint2 = gl.getParameter(ext.GPU_DISJOINT_EXT);
   if (!disjoint2 )
   {
    // collect the time
   }
}
```

**Comment by kdashg** [comment]
It is not better to change the code that way, and doing so will increase the false-disjoint-detected rate. (through probably not by much)

Ideally, `gl.getParameter(ext.GPU_DISJOINT_EXT)` should happen as close before beginQuery(TIME_ELAPSED), and as close after endQuery(TIME_ELAPSED) as possible. (Or for queryCounter, as close before the first queryCounter and as close after the last queryCounter that you want to compare)

As such,
```
gl.getParameter(ext.GPU_DISJOINT_EXT);
gl.beginQuery(ext.TIME_ELAPSED_EXT, query);
gl.drawElements(...);
gl.endQuery(ext.TIME_ELAPSED_EXT);
let disjoint = gl.getParameter(ext.GPU_DISJOINT_EXT);
let available = gl.getQueryParameter(query, gl.QUERY_RESULT_AVAILABLE);
```
is more ideal than
```
gl.getParameter(ext.GPU_DISJOINT_EXT);
gl.beginQuery(ext.TIME_ELAPSED_EXT, query);
gl.drawElements(...);
gl.endQuery(ext.TIME_ELAPSED_EXT);
let available = gl.getQueryParameter(query, gl.QUERY_RESULT_AVAILABLE);
let disjoint = gl.getParameter(ext.GPU_DISJOINT_EXT);
```

The query is already ended, (or for queryCounter, the timestamp already taken) and DISJOINT cannot affect the results of QUERY_RESULT_AVAILABLE, though querying QUERY_RESULT_AVAILABLE can technically cause a DISJOINT.

**Comment by qjia7** [comment]
@kdashg Thanks for your detailed explanation. Sounds good for me. Will close this issue.
