### ISSUE TITLE
a link does not work in this link https://registry.khronos.org

### ISSUE THREAD

**Issue by letochagone** [KhronosGroup/WebGL#3503]
a link does not work in this page :
https://registry.khronos.org/webgl/specs/latest/1.0/#5.14.3

![image](https://user-images.githubusercontent.com/7129968/204126095-57c1eb7d-bf92-4003-b4e8-28b390294124.png)

![image](https://user-images.githubusercontent.com/7129968/204126108-704e57bc-4150-4af9-8777-cc12f5146421.png)

**Comment by kdashg** [comment]
It works for me today, at least!
