### ISSUE TITLE
all links to OpenGL ES 2.0 fail.

### ISSUE THREAD

**Issue by letochagone** [KhronosGroup/WebGL#3522]
when I visit the page:
https://registry.khronos.org/webgl/specs/latest/1.0/#5.9
all links to OpenGL ES 2.0 fail.

![image](https://user-images.githubusercontent.com/7129968/220270073-f440c5f1-55dd-4acd-b9fc-e576ef0ad335.png)

![image](https://user-images.githubusercontent.com/7129968/220270149-ad3631e3-56ac-493d-a8a1-7ae447490d36.png)

**Comment by kenrussell** [comment]
Thanks for the report.
