### ISSUE TITLE
Contribution guidelines do not mention CLA

### ISSUE THREAD

**Issue by kkinnunen-apple** [KhronosGroup/WebGL#3526]
Contribution guidelines do not mention CLA

A link to the CLA would be good

**Comment by kenrussell** [comment]
@outofcontrol - could you please point us to the text of the CLA? It's handled by the CLA assistant tool but I can't figure out how to view it.

**Comment by KhronosWebservices** [comment]
MIT CLA: https://gist.github.com/KhronosWebservices/8f6da941cd2bb316e1f32e40a7f94429

**Comment by kenrussell** [comment]
Thanks @KhronosWebservices . I'll add this to the top-level README.
