### ISSUE TITLE
unexpected result after a for loop in a shader

### ISSUE THREAD

**Issue by letochagone** [KhronosGroup/WebGL#3544]
here are 2 links leading to WebGL code. Both should give the same result, one has a "for" loop, the other has a copy paste of statements into this loop. What intrigues me is that the code with the "for" loop does not give the expected result on my laptop. I would like to know the cause

https://jsfiddle.net/56jey9mf/

![image](https://github.com/KhronosGroup/WebGL/assets/7129968/c7e7f3c2-5f91-41db-ac3c-178fb9a49152)

https://jsfiddle.net/nk2Lb1xh/

![image](https://github.com/KhronosGroup/WebGL/assets/7129968/a70a33bf-7234-4007-8133-103cbaceafa0)

**Comment by kkinnunen-apple** [comment]
You should report it to the browser vendor bug tracker. Also remember to report which hardware the failure occurs.
For current Mac Safari, it appears that both cases work.

This might also be an issue with the underlying hardware or drivers.

The PointSize of 300 might be too big for some GL drivers for some cases.
