### ISSUE TITLE
WebGL is missing interface for offscreen context that has commit() method

### ISSUE THREAD

**Issue by kkinnunen-apple** [KhronosGroup/WebGL#3638]
WebGL is missing interface for offscreen context that has commit() method
It appears to be mandatory for OffscreenCanvas:

https://html.spec.whatwg.org/multipage/canvas.html#offscreencontext-commit

> [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas) object. The bitmap of the [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas) object is pushed to the [placeholder canvas element](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas-placeholder) by calling the commit() method of the [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas) object's rendering context. All rendering context types that can be created by an [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas) object must implement a [commit()](https://html.spec.whatwg.org/multipage/canvas.html#offscreencontext-commit) method. The exact behavior of the commit method (e.g. whether it copies or transfers bitmaps) may vary, as defined by the rendering contexts' respective specifications. Only the [2D context for offscreen canvases](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvasrenderingcontext2d) is defined in this specification.

**Comment by kenrussell** [comment]
`OffscreenCanvas.commit()` was supposed to have been removed from the specification after `requestAnimationFrame` was added to web workers, but https://github.com/whatwg/html/pull/9979 was blocked due to disagreement among vendors. I hope that that PR will be unblocked and can land, cleaning up this method.

In the interim, I oppose adding a `commit()` method to `WebGLRenderingContextBase` because it moves the WebGL spec backward.

**Comment by kdashg** [comment]
I don't think it moves the spec backwards in general. Wanting to move forward as discussed in the whatwg issue is worth discussing, but let's phrase it that way rather than using a contentious adjective.

**Comment by kenrussell** [comment]
After much discussion, the requirement of a `commit()` method on `OffscreenCanvas`'s contexts was removed in https://github.com/whatwg/html/pull/9979 . Closing this issue.
