### ISSUE TITLE
CSP violation breaks https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/offscreencanvas-transfer-image-bitmap.html

### ISSUE THREAD

**Issue by kdashg** [KhronosGroup/WebGL#3663]
https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/offscreencanvas-transfer-image-bitmap.html

Firefox error:
> Content-Security-Policy: The page’s settings blocked a worker script (worker-src) at blob:https://registry.khronos.org/c6514fd7-ef4a-461d-aab3-4d3dbda1c6b7 from being executed because it violates the following directive: “script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com/ https://www.googletagmanager.com/ https://www.google-analytics.com/”

Chrome errors:
> offscreencanvas-tran…mage-bitmap.html:40 Refused to create a worker from 'blob:https://registry.khronos.org/101b13d6-456d-480f-a877-96c4439435b4' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' cdnjs.cloudflare.com www.googletagmanager.com www.google-analytics.com". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
(anonymous)	@	offscreencanvas-tran…mage-bitmap.html:40
> 
> offscreencanvas-tran…mage-bitmap.html:40 Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'blob:https://registry.khronos.org/101b13d6-456d-480f-a877-96c4439435b4' is denied by the document's Content Security Policy.
(anonymous)	@	offscreencanvas-tran…mage-bitmap.html:40
﻿

**Comment by kdashg** [comment]
@kenrussell FYI

**Comment by kenrussell** [comment]
James Riordon, Khronos' webmaster, updated khronos.org's Content Security Policy settings to allow `worker-src: blob:`. This fixes this test, but now there are other failures.

https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/methods-worker.html

Firefox:
> Content-Security-Policy: The page’s settings blocked a worker script (worker-src) at https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/methods-worker.js from being executed because it violates the following directive: “worker-src blob:”

Chrome:
> methods-worker.html:25 Refused to create a worker from 'https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/methods-worker.js' because it violates the following Content Security Policy directive: "worker-src blob:".
> 
> (anonymous) @ methods-worker.html:25
> methods-worker.html:25 Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/methods-worker.js' is denied by the document's Content Security Policy.
>     at methods-worker.html:25:16

**Comment by kenrussell** [comment]
Other tests failing for the same reason in the same directory:

https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/context-creation-worker.html

https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/context-lost-restored-worker.html

https://registry.khronos.org/webgl/sdk/tests/conformance/offscreencanvas/context-lost-worker.html

**Comment by KhronosWebservices** [comment]
These have been fixed.

**Comment by kenrussell** [comment]
Thank you @KhronosWebservices . For completeness could you please tell us here what the server configuration change was?

**Comment by KhronosWebservices** [comment]
When adding worker-src directive to our Content-Security-Policy for the initial issue, I left out 'self', which ended up blocking local features. Final entry is: 
```
worker-src 'self' blob:;
```

**Comment by kenrussell** [comment]
Thank you @KhronosWebservices !

@kdashg please reopen if you're still seeing problems.
