### ISSUE TITLE
Glitch occur when texture resolution is biggr than 4096 in mobile browser.

### ISSUE THREAD

**Issue by stonetuskboar** [KhronosGroup/WebGL#3700]
https://longtime168.itch.io/webgl-texture-resolution-glitch
 
If you open this page in PC, every text is fine, if you open it in Mobile Browser, you can only see the 4096 atlas resolution text.

**Comment by kenrussell** [comment]
This is as expected. OpenGL and WebGL have certain GPU-specific limitations. If you go to https://webglreport.com/ on your mobile device you'll see that the `MAX_TEXTURE_SIZE` parameter is `4096` (at least, it is on my mobile). It's necessary to call `gl.getParameter(gl.MAX_TEXTURE_SIZE)` in your code and make decisions based on the result.

**Comment by stonetuskboar** [comment]
> This is as expected. OpenGL and WebGL have certain GPU-specific limitations. If you go to https://webglreport.com/ on your mobile device you'll see that the parameter is (at least, it is on my mobile). It's necessary to call in your code and make decisions based on the result.`MAX_TEXTURE_SIZE``4096``gl.getParameter(gl.MAX_TEXTURE_SIZE)`

Thank you sir! I'm not familar with WebGL. Moreover, there is quite limited information about this on the internet; when I searched on Google, I could only find discussions from ten years ago https://www.html5gamedevs.com/topic/6762-max-texture-size-for-webgl/. 
Then again, I'm glad to receive your accurate answer!

**Comment by kenrussell** [comment]
You're welcome!
