### ISSUE TITLE
EXT_texture_norm16 and linear texture filtering support

### ISSUE THREAD

**Issue by slak44** [KhronosGroup/WebGL#3706]
The types introduced by EXT_texture_norm16 are texture filterable (if I'm understanding [this](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_norm16.txt) correctly).

However, not all mobile GPUs support linear filtering, only nearest. For example, [this webgpu proposal](https://github.com/gpuweb/gpuweb/issues/3839) contains a separate norm16-filterable extension, because doing linear filtering needs an optional vulkan feature, SAMPLED_IMAGE_FILTER_LINEAR ("loses Samsung Xclipse 920 and a lot of Mali devices + all Adreno 5XX devices").
I can confirm at least that the Adreno 750 (S24 Ultra) doesn't support linear filtering with norm16. Here's a jsfiddle I found that reproduces this (if you have a phone with the issue): https://jsfiddle.net/sedghi/hxLegk5y/

Am I misunderstanding something here? It seems that either A) browsers should not advertise support for this extension if they can't do linear filtering, or B) the standard should mention that linear filtering is optional.

It would be useful at the very least to have a standard way to detect if the current device supports linear filtering. EXT_texture_norm16 is present, and it does work with nearest, so you can't rely on that. For float textures, you can check for [OES_texture_float_linear](https://registry.khronos.org/OpenGL/extensions/OES/OES_texture_float_linear.txt), but its presence doesn't mean it also works with norm16.

**Comment by lexaknyazev** [comment]
Devices with Arm Mali GPUs do not support 16-bit normalized textures so the extension should not be exposed on them in the first place. If it's not the case, please provide specific examples.

Some devices with Qualcomm Adreno GPUs may not support linear filtering despite exposing the extension string. This should be seen as a driver bug that will hopefully become less relevant over time. For the time being, apps may use a simple runtime test to check whether linear filtering is actually supported.

**Comment by slak44** [comment]
>Devices with Arm Mali GPUs do not support 16-bit normalized textures so the extension should not be exposed on them in the first place

You're right, only Adreno devices claim to support the extension.

>This should be seen as a driver bug that will hopefully become less relevant over time

So the standard is right, and claiming to support the extension in this case is the bug. Though  I don't have much hope for users updating their devices even if there is a driver fix. Thank you for confirming my assumptions.

>apps may use a simple runtime test to check whether linear filtering is actually supported

In case anyone else wants to do this, here's a function that tests for it:
```javascript
  function supportsNorm16Linear() {
    const canvasSize = 4;
    const texWidth = 2;
    const texHeight = 1;
    const texData = new Int16Array([0, 2**15 - 1]);
    const pixelToCheck = [1, 1];

    const canvas = document.createElement('canvas');
    canvas.width = canvasSize;
    canvas.height = canvasSize;
    const gl = canvas.getContext('webgl2')
    if (!gl) {
      return false;
    }

    const ext = gl.getExtension('EXT_texture_norm16');
    if (!ext) {
      return false;
    }

    const vs = `#version 300 es
    void main() {
      gl_PointSize = ${canvasSize.toFixed(1)};
      gl_Position = vec4(0, 0, 0, 1);
    }
  `;
    const fs = `#version 300 es
    precision highp float;
    precision highp int;
    precision highp sampler2D;

    uniform sampler2D u_image;

    out vec4 color;

    void main() {
        vec4 intColor = texture(u_image, gl_PointCoord.xy);
        color = vec4(vec3(intColor.rrr), 1);
    }
    `;

    const vertexShader = gl.createShader(gl.VERTEX_SHADER);
    gl.shaderSource(vertexShader, vs);
    gl.compileShader(vertexShader);
    if (!gl.getShaderParameter(vertexShader, gl.COMPILE_STATUS)) {
      return false;
    }

    const fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
    gl.shaderSource(fragmentShader, fs);
    gl.compileShader(fragmentShader);
    if (!gl.getShaderParameter(fragmentShader, gl.COMPILE_STATUS)) {
      return false;
    }

    const program = gl.createProgram();
    gl.attachShader(program, vertexShader);
    gl.attachShader(program, fragmentShader);
    gl.linkProgram(program);

    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      return false;
    }

    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texImage2D(
        gl.TEXTURE_2D,
        0,
        ext.R16_SNORM_EXT,
        texWidth,
        texHeight,
        0,
        gl.RED,
        gl.SHORT,
        texData
    );

    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.useProgram(program);
    gl.drawArrays(gl.POINTS, 0, 1);

    const pixel = new Uint8Array(4);
    gl.readPixels(pixelToCheck[0], pixelToCheck[1], 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixel);
    const [r, g, b, _a] = pixel;

    const webglLoseContext = gl.getExtension('WEBGL_lose_context');
    if (webglLoseContext) {
      webglLoseContext.loseContext();
    }

    return r === g && g === b && r !== 0;
  }

```
