### ISSUE TITLE
Add or update per-file licenses

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#435]
The WebGL repository is now being pulled wholesale into the Chromium repository for testing purposes. Chromium requires that all third-party files pass the Linux licensecheck utility. Currently many files in the WebGL repository fail this check, either because of missing or unrecognized per-file licenses.

A separate bug regarding the html5lib library has been filed at https://github.com/html5lib/html5lib-python/issues/125 . The complete list of files failing licensecheck follows. Ideally all of these files will be fixed.

'third_party/webgl/src/sdk/demos/google/san-angeles/gles/bob/compare.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/t/build.sh' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/t/include/GLES/egltypes.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/t/include/GLES/egl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/t/include/GLES/gl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/t/app-linux.c' has non-whitelisted license 'MIT/X11 (BSD like) LGPL (v2.1 or later)'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/build.sh' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/include/GLES/egltypes.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/include/GLES/egl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/include/GLES/gl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/gles/app-linux.c' has non-whitelisted license 'MIT/X11 (BSD like) LGPL (v2.1 or later)'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/app-glut.c' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/build.sh' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/include/GLES/egltypes.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/include/GLES/egl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/include/GLES/gl.h' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/sdk/demos/google/san-angeles/glut/app-linux.c' has non-whitelisted license 'MIT/X11 (BSD like) LGPL (v2.1 or later)'
'third_party/webgl/src/sdk/demos/google/nvidia-vertex-buffer-object/VertexBufferObject2.java' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/specs/1.0/extract-idl.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/specs/latest/1.0/extract-idl.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/specs/latest/2.0/extract-idl.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/specs/1.0.2/extract-idl.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/index.php' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/inputstream.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/html5parser.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/pulldom.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/etree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/lxmletree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/**init**.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/soup.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/dom.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/_base.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/simpletree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treewalkers/genshistream.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/sanitizer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/ihatexml.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/inject_meta_charset.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/lint.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/sanitizer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/optionaltags.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/_base.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/whitespace.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/filters/formfiller.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/etree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/etree_lxml.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/__init__.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/soup.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/dom.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/_base.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/treebuilders/simpletree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/utils.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_stream.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/runparsertests.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_treewalkers.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/tokenizertotree.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_sanitizer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_serializer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_whitespace_filter.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/__init__.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_encoding.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_formfiller.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/support.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_tokenizer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/test_parser.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/performance/concatenation.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/runtests.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tests/mockParser.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/serializer/htmlserializer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/serializer/xhtmlserializer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/serializer/**init**.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/**init**.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/constants.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/resources/html5lib/src/html5lib/tokenizer.py' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/atom.xsl' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/schematron/iso_dsdl_include.xsl' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/schematron/webgl_message_patch.xsl' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/schematron/iso_svrl_for_xslt1.xsl' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/standards.xsl' has non-whitelisted license 'UNKNOWN'
'third_party/webgl/src/extensions/rev_utils.xsl' has non-whitelisted license 'UNKNOWN'

**Comment by jdashg** [comment]
@kenrussell Is this still relevant?

**Comment by kenrussell** [comment]
Let's close this. These files were whitelisted in Chromium some time ago and it would be a lot of work to chase down licenses in these files for unclear benefit.
