### ISSUE TITLE
More tests for set() needed in Typed Array tests

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#449]
Stephen Adams from Google has pointed out that the tests for typed arrays' set() methods are insufficient. In particular, the tests must verify the case where set() is called with a different type of typed array view than the receiver's, due to how Web IDL's overloads work. (The original intent was that one could only pass a Float32Array to Float32Array.set, but it was discovered some time ago that a different view type like Uint8Array will match the overload taking "type[]".)

**Comment by pyalot** [comment]
Since the typed array spec is no longer maintained by Khronos, I'd assume the test suite is no longer up to date in this repository for it. Could you point out where the current test suite for typed arrays lives and if so, close the bug for this repository?

**Comment by kenrussell** [comment]
While it's true that typed arrays have been subsumed into the ECMAScript 6 spec, the typed array tests in the WebGL repository still have good value. First, it looks like the ES6 tests are still heavily under development: http://bocoup.com/weblog/stabilizing-es6/ indicates a substantial fraction are being ported from the V8 project's test suite. Second, the typed array tests in the Khronos repo are guaranteed to test uses of typed arrays that matter to WebGL implementers, and that every implementer passes these tests. For this reason I think these tests should be maintained in the WebGL repo and that we should consider extending them. If that's done I would also encourage submitting the revised tests to an upstream repository like V8's or, better, test262 when available.

**Comment by jdashg** [comment]
Subsumed by JS tests, I imagine.
