### ISSUE TITLE
get.webgl.org: invalid SSL certificate

### ISSUE THREAD

**Issue by dlazerka** [KhronosGroup/WebGL#813]
While implementing browser-supports-WebGL check and showing user a link to `//get.webgl.org`, I found that get.webgl.org presents an invalid certificate. We certainly want to use HTTPS, so browser won't show any warnings.
![screenshot from 2014-12-17 01 05 24](https://cloud.githubusercontent.com/assets/592184/5468824/cd10786a-8588-11e4-9a06-502ef1b3a1dd.png)
And in general, HTTPS forever: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

**Comment by kenrussell** [comment]
Khronos' webmaster fixed this a while ago and just pointed out that this should be closed. Please open a new issue if problems persist.
