### ISSUE TITLE
Adapt ANGLE DrawArraysWithOffset test into WebGL conformance suite

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#862]
http://crbug.com/457269 and http://crbug.com/447140 describe a bug in ANGLE's instancing implementation for which a test was written in https://chromium.googlesource.com/angle/angle/+/master/tests/angle_tests/InstancingTest.cpp (DrawArraysWithOffset). This test should be ported into sdk/tests/conformance/extensions/angle-instanced-arrays.html .

**Comment by toji** [comment]
I can knock this out pretty quick, I'll take it.
