### ISSUE TITLE
WebGL 2.0 spec must specify VERSION and SHADING_LANGUAGE_VERSION

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#899]
Similarly to the WebGL 1.0 spec, WebGL 2.0 must specify the VERSION and SHADING_LANGUAGE_VERSION strings.

Thanks to Janusz Sobczak from Mobica for pointing out this omission.

**Comment by djg** [comment]
Is WebGL 2 going to use something like `#version 200 webgl` to keep with the `#version 300 es` theme?

**Comment by kenrussell** [comment]
I think it's best to not change this, and use vanilla "#version 300 es" in the shaders. The spec says that it accepts shaders written in the OpenGL ES shading language version 3.00.
