### ISSUE TITLE
Remove comment about drawRangeElements and define behavior

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#900]
In recent working group meetings the TODO around exposure of drawRangeElements has basically been resolved in favor of leaving it in the specification. The TODO should be removed and the undefined behavior defined. In particular:
- If the implementation supports KHR_robust_buffer_access_behavior's semantics (as defined in the WebGL 1.0 spec), then drawRangeElements may use that for handling any out-of-range indices, and not generate any error if there are indices outside the given range.
- Otherwise, if any indices are referenced outside the range specified by the caller, it should generate an INVALID_OPERATION error, similarly to how drawElements behaves.

**Comment by jdashg** [comment]
It looks like this was done, though we decided that being outside the specified range is not an error. (that is, the specified range is a hint only)
