### ISSUE TITLE
offset/stride multiple of type for vertexAttribPointer

### ISSUE THREAD

**Issue by pyalot** [KhronosGroup/WebGL#914]
The WebGL 1/2 specification defines an INVALID_OPERATION error for offsets/strides to vertexAttribPointer that are not multiples of the passed type.

This restriction/error does not exist in OpenGL ES 1/2/3 or Desktop GL 1/2/3/4.

It is possible this was introduced because of severe performance concerns or to keep D3D compatibility (I don't know). The WebGL 1/2 specification does not say.

* Clarify in the specification why that restriction was introduced to WebGL OR
* Remove the restriction if there isn't a good reason for it (I doubt that would be the case, there's got to be some reason right?)

**Comment by kenrussell** [comment]
As has been pointed out on the public_webgl mailing list, this restriction is in fact present in section 2.9 "Buffer Objects" of the OpenGL ES 2.0 specification:

"Clients must align data elements consistent with the requirements of the client platform, with an additional base-level requirement that an offset within a buffer to a datum comprising /N/ basic machine units be a multiple of /N/."

Catching the illegal inputs during the call to vertexAttribPointer prevents the illegal state from occurring. I don't feel that additional specification text is required.
